### ISSUE TITLE
Ansible hangs in Python 3 code when creating a secret via kubernetes.core.k8s on openshift

### ISSUE THREAD

**Issue by darac79** [ansible-collections/kubernetes.core#137]
##### SUMMARY

Creating a secret on openshift using the kubernetes.core.k8s fails. The ansible playbook hangs in the python 3 code execution of the module. The generated python code from the temporary file will be attached too.

Here's the last output:
```
TASK [create jms secrets] *******************************************************************************************************************************************************************************************************
task path: /cygdrive/c/iFAO/workspaces/polaris2/git/ansible_artemis_host/playbook-broker-k8s.yml:62
redirecting (type: action) kubernetes.core.k8s to kubernetes.core.k8s_info
redirecting (type: action) kubernetes.core.k8s to kubernetes.core.k8s_info
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dostricki
<127.0.0.1> EXEC /bin/sh -c 'echo ~dostricki && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dostricki/.ansible/tmp `"&& mkdir "` echo /home/dostricki/.ansible/tmp/ansible-tmp-1623844911.565056-7143-145021102811153 `" && echo ansible-tmp-1623844911.565056-7143-145021102811153="` echo /home/dostricki/.ansible/tmp/ansible-tmp-1623844911.565056-7143-145021102811153 `" ) && sleep 0'
Using module file /home/dostricki/.ansible/collections/ansible_collections/kubernetes/core/plugins/modules/k8s.py
<127.0.0.1> PUT /home/dostricki/.ansible/tmp/ansible-local-7029r1b5sbgg/tmpaf31uhsk TO /home/dostricki/.ansible/tmp/ansible-tmp-1623844911.565056-7143-145021102811153/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/dostricki/.ansible/tmp/ansible-tmp-1623844911.565056-7143-145021102811153/ /home/dostricki/.ansible/tmp/ansible-tmp-1623844911.565056-7143-145021102811153/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/dostricki/.ansible/tmp/ansible-tmp-1623844911.565056-7143-145021102811153/AnsiballZ_k8s.py && sleep 0'
 [ERROR]: User interrupted execution
```
The ansible playbook commands can be found below. Publishing the generated yaml via openshift console succeeds - therefore it is not a syntactical issue in the definition. 
Besides that other types of objects have been created sucessfully on openshift using this module in the same playbook - so it's also not a general connectivity/security issue.

$ oc create -f ./secret.yml
secret/artemis-jmsconnector-secret created

``` contents of the secret.yml  ------ password and keystore contents removed -----
apiVersion: v1
kind: Secret
metadata:
  name: "artemis-jmsconnector-secret"
  namespace: testproject
type: Opaque
data:
  broker.ks: BASE64encodedkeystorecontents===
  client.ts: BASE64encodedtruststorecontents===
stringData:
  keyStorePassword: somepasswordinplaintext  
  trustStorePassword: somepasswordinplaintext
``` 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s creation of a secret object on openshift

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.11.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dostricki/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/dostricki/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, May 20 2021, 11:41:59) [GCC 10.2.0]
  jinja version = 3.0.1
  libyaml = False
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Win 10
Cygwin v3.2.0(0.340/5/3)
Python v3.8.10
Ansible v2.11.1
kubernetes.core collection v2.0.1
Openshift is running Kubernetes Version v1.19.0+d670f74

##### STEPS TO REPRODUCE

```yaml
# I tried out to use the module in different ways - it always hangs.
# variant 1 - inline definition
    - name: create jms secrets
      kubernetes.core.k8s:
        api_version: v1
        namespace: "{{ openshift.project.name }}"
        validate_certs: no
        ca_cert: "{{ playbook_dir }}/roles/artemis/global_certs/iFAO-Root-CA.crt"
        host: "{{ openshift_url }}"
        api_key: "{{ openshift.login.service_account_token }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ openshift.object_prefix }}-jmsconnector-secret"
            namespace: "{{ openshift.project.name }}"
          type: Opaque
          data:
            broker.ks: "{{ keystore_file.content }}"
            client.ts: "{{ truststore_file.content }}"
          stringData:
            keyStorePassword: "{{ openshift.security.broker_keystore_password }}"
            trustStorePassword: "{{ openshift.security.broker_truststore_password }}"        
        state: present
        force: yes
```

Variant 2+3 - usage of the templated definition via lookup (old way) or template - both fail

__secret.yaml - I use this file as a template for the secret__
```yaml
# secret.yaml -template
apiVersion: v1
kind: Secret
metadata:
  name: {{ openshift.object_prefix }}-jmsconnector-secret
  namespace: {{ openshift.project.name }}
type: Opaque
data:
  broker.ks: {{ keystore_file.content }}
  client.ts: {{ truststore_file.content }}
stringData:
  keyStorePassword: {{ openshift.security.broker_keystore_password }}
  trustStorePassword: {{ openshift.security.broker_truststore_password }}
```

```yaml
# variant 2+3 - usage of the templated definition via template and lookup
    - name: create jms secrets
      kubernetes.core.k8s:
        api_version: v1
        namespace: "{{ openshift.project.name }}"
        validate_certs: no
        ca_cert: "{{ playbook_dir }}/roles/artemis/global_certs/iFAO-Root-CA.crt"
        host: "{{ openshift_url }}"
        api_key: "{{ openshift.login.service_account_token }}"
##        definition: "{{ lookup('template', './roles/artemis/templates/secret.yaml') }}"
        template: ./roles/artemis/templates/secret.yaml
        state: present
```

##### EXPECTED RESULTS

The secret should have been created on the openshift cluster

##### ACTUAL RESULTS

The ansible playbook execution hangs in the python 3 code when executing this step.

```paste below

```

**Comment by darac79** [comment]
I attached the generated python code - but removed sensitive data from it.
[AnsiballZ_k8s.py.txt](https://github.com/ansible-collections/kubernetes.core/files/6663101/AnsiballZ_k8s.py.txt)

**Comment by tgdfool2** [comment]
Same issue here, could be reproduced on an AKS v1.19.7 cluster; secret creation using template and lookup hangs forever.

**Comment by gravesm** [comment]
@darac79 There's a bug in cloud.common. See here: https://github.com/ansible-collections/cloud.common/issues/61. Duplicate issue here: https://github.com/ansible-collections/kubernetes.core/issues/140. As a workaround until the PR gets merged and released, you can remove cloud.common.

**Comment by darac79** [comment]
@gravesm Thx for the quick support and pointing out a possible workaround. 
As I am quite new to this tech stack need to find out how I could possibly remove the dependency from kybernetes.core to cloud.common? Are there some instructions/documentation I can follow? Is it maybe by simply deleting the folder {home}\.ansible\collections\ansible_collections\cloud\common?
I would appreciate some guidance

**Comment by gravesm** [comment]
@darac79 Yes, you can just delete the cloud\common directory.

**Comment by tgdfool2** [comment]
@gravesm: Thanks for pointing out the issue!

@darac79: I didn't find a proper way to do this through the `requirements.yml` file, so I make sure that the directory is removed at the beginning of my Playbook:
```
    - name: Prerequisites | Ensure cloud.common collection is removed
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        # AWX Path
        - /runner/requirements_collections/ansible_collections/cloud/common
        # Local Path
        - collections/ansible_collections/cloud/common
```
