### ISSUE TITLE
in-memory kubeconfig rather than file

### ISSUE THREAD

**Issue by hassenius** [ansible-collections/kubernetes.core#139]
##### SUMMARY
Have a method to use non-file-based kubeconfig

##### ISSUE TYPE
Feature or documentation improvement if already possible

##### COMPONENT NAME
kubernetes.core.k8s

##### ADDITIONAL INFORMATION
In our case we store the relevant kubernetes auth information in an external secret store, so we can easily retrieve the content of a kubeconfig file which has all the relevant information to connect to the cluster.
It appears that the kubernetes.core.k8s component expects to find kubeconfig as a file: https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html#parameter-kubeconfig
with no way to feed ca/client_cert/key in as direct values.

This means for us we'd need to save the relevant information to temporary files after retrieving them from external secret store.

**Comment by bigfleet** [comment]
e.g.

```
- name: Store kube/config in tempfile
  ansible.builtin.tempfile:
    state: file
  register: aks_kubeconfig_tmpfile
- name: Place kubeconfig onto filesystem temporarily
  copy: 
    content: "{{ azure_aks_cluster.kube_config }}"
    dest: "{{ aks_kubeconfig_tmpfile.path }}"
    mode: '0600'
- name: Get Cluster information
  kubernetes.core.k8s_info:
    kind: namespace
    kubeconfig: "{{ aks_kubeconfig_tmpfile.path }}"
 ```
