### ISSUE TITLE
[bug] getting stuck while applying configmap entry into k8s.

### ISSUE THREAD

**Issue by itaru2622** [ansible-collections/kubernetes.core#140]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

not sure but may be kubernetes.core.k8s

##### ANSIBLE VERSION

```paste below
ansible --version
ansible [core 2.11.1] 
  config file = /home/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, May 12 2021, 15:46:43) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True

pip list | grep ansible
ansible             4.1.0
ansible-core        2.11.1

ansible-galaxy collection list 
# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
cloud.common      2.0.2  
community.general 3.2.0  
kubernetes.core   2.0.2  
  
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed

COMMAND_WARNINGS(/home/ansible.cfg) = False
DEFAULT_HOST_LIST(/home/ansible.cfg) = ['/home/hosts']
DEFAULT_LOG_PATH(/home/ansible.cfg) = /home/vars/ansible.log
DEFAULT_STDOUT_CALLBACK(/home/ansible.cfg) = default
DEPRECATION_WARNINGS(/home/ansible.cfg) = False
HOST_KEY_CHECKING(/home/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Container image based on official Python 3 image (python:3-buster).
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### STEPS TO REPRODUCE

install latest kubernetes.core by 
``` ansible-galaxy collection install git+https://github.com/ansible-collections/kubernetes.core.git ```

for easy generating specific length of string, 
I used community.general.random_string ( install it by ```ansible-galaxy collection install community.general```  )
even you use other method (text editor or others),  produced results are the same.

playbook snippet for test:

```yaml
- name: Start ansible x k8s test
  hosts: localhost
  gather_facts: no
  connection: local
  tasks: ...

---
- name: generate test data
  block:
   - name: generate testing lengths ( 1KB to 1MB)
     set_fact:
        lengths:
          - 1024
          - 2048
          - 4096
          - 5120
          - 8192
          - 16384
          - 32768
          - 65536
          - 1048576
        NAMESPACE: "testing"
   
   - name: setup kv
     set_fact:
        kv: |
          {{ kv|default([]) + [{ 
               'name' : 'str-' + (item|string),
               'val':   lookup('community.general.random_string', length=item, upper=false, special=false)
          }] }}
     with_items: "{{ lengths }}"


- name: testing k8s (create namespace)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ NAMESPACE }}"

- name: testing k8s apply configmap
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ NAMESPACE }}"
      data:
         val : >-
           {{ item.val }}
  with_items: "{{ kv }}"
```

##### EXPECTED RESULTS

It can create all entries in configmap without getting stuck., as following older ansible got succeeded.
```bash
the ansible version which could create all entries

pip list | grep ansible
ansible             2.10.6
ansible-base        2.10.5

it said:
   redirecting (type: modules) ansible.builtin.k8s to community.kubernetes.k8s
when executing k8s operation. and all succeeded.
```

##### ACTUAL RESULTS

It can create entries for shorter string (around 4096)
but cannot create entries for 5120 or longer string, 
because it get stuck while creating 5120 length string entry into k8s configmap.

```bash
kubectl get configmap -n testing
NAME       DATA   AGE
str-1024   1      126m
str-2048   1      126m
str-4096   1      126m
```

```paste below
:
TASK [testing k8s apply configmap] ******************************************************************************************************************************************
task path: /home/playbooks/ops/mine/test-ansible410.yaml:48
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1624168222.3945775-192-149792786770892 `" && echo ansible-tmp-1624168222.3945775-192-149792786770892="` echo /root/.ansible/tmp/ansible-tmp-1624168222.3945775-192-149792786770892 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.k8s to kubernetes.core.k8s
Using module file /root/.ansible/collections/ansible_collections/kubernetes/core/plugins/modules/k8s.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-153jzdrrtto/tmpqzuj3ybq TO /root/.ansible/tmp/ansible-tmp-1624168222.3945775-192-149792786770892/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1624168222.3945775-192-149792786770892/ /root/.ansible/tmp/ansible-tmp-1624168222.3945775-192-149792786770892/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1624168222.3945775-192-149792786770892/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1624168222.3945775-192-149792786770892/ > /dev/null 2>&1 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
changed: [localhost] => (item={'name': 'str-1024', 'val': 'k70ng9azk7j2oraokc2rsi2zks352nbwtafd29egepagwss0r9fmsjo3n6y5ge6xbo0xqa2bez1qkmljq5dgdle8av398h0gbepqki1mu9wa9vlhllkn64mnl8fckfuh9jqxrjerutn5vlnqgbqgaw66lf0ohn55ny5lua315cp3sdshchjy9szsa9wa220ebjx2b8wqthb9d85xerpl31v91v0metg88hna6axjjkjio806bn95ilsww0yd0fx95nq0ojlwu8ot2nrv1qlsnnnbn3ob2knv99anlk0q9145dt5szbh6nf1grouuic4kk3rjlomh81flwvwwabk95y99mwsmffhj4dlvwukxivj3ljqqack9hzvoiav66tfsxf49hh0n6x2gwd9pfsw8qvkiufx3eeeifh6en46tt8xxe6k397fsnvms898dmj7urcl7h2t00m00vppqwvcj83o39wly3zqlaaus0ho64pa611qw4egokzlwjlmv7vt7hekrrdyl48y758l3l5m78q53s96zsyoedbn4r0bvcyfizz1i9q7v0twq6dgpi05jfygmu41idgmrp5a8al99lgti6gpncs3em0d1thfuk7sv39zppnv2errrlw32vars8th5596krod3na8ls1ehad7npxk8xe08bwomirwp56i80iy105shqwgtdpihhxgik7x3g652n5234ig7h9xx88p2wfpd2dbl3w6o625zxtvindv284tx04ck6z1ovkoaimkxnbg7oabeeqmvn7ibw67kimdn55rqz4wjbn1ffg08pl6mr19e6g56l3bsuv2qratp2z4eyq6eda6v735fwh77wfycaedu4nztvin00vkre4ietfg6dcww1tn1o9uyk0uwfdwjq1kws8fevnvu7li8rygyi4pks1wdmvf4mmnm596t9loghq1f31ut1wu3e4t5md3o5hoafhucgqn
:
i9036cmaw8g9a11milgku2a9711hc5tqp4skqrq35eveqq0dmazxd7zhswbgiftofvtm1ssoju21g6xk8rxzmunth74y3rylhb5b8j3wybuyys0ugdpdluulgr7x2zsxuftx2hudg"
        },
        "kind": "ConfigMap",
        "metadata": {
            "creationTimestamp": "2021-06-20T03:04:16Z",
            "name": "str-4096",
            "namespace": "testing",
            "resourceVersion": "56272",
            "selfLink": "/api/v1/namespaces/testing/configmaps/str-4096",
            "uid": "c0cbe57b-987d-4f2a-a4fc-24cf5b400922"
        }
    }
}
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1624165306.0085475-1426-48794581659429 `" && echo ansible-tmp-1624165306.0085475-1426-48794581659429="` echo /root/.ansible/tmp/ansible-tmp-1624165306.0085475-1426-48794581659429 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/kubernetes/core/plugins/modules/k8s.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-1387wbfmrpn4/tmpl3_tad4a TO /root/.ansible/tmp/ansible-tmp-1624165306.0085475-1426-48794581659429/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1624165306.0085475-1426-48794581659429/ /root/.ansible/tmp/ansible-tmp-1624165306.0085475-1426-48794581659429/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1624165306.0085475-1426-48794581659429/AnsiballZ_k8s.py && sleep 0'

GET STUCK, then type CTRL-C
```
