### ISSUE TITLE
Add an update option for helm_repository

### ISSUE THREAD

**Issue by rendhalver** [ansible-collections/kubernetes.core#156]
##### SUMMARY

We need to add an option to update those repositories or add something that checks if the repo needs updating an perform that update.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

helm_repository

##### ADDITIONAL INFORMATION

Helm repositories are not static and are updated regularly.
From what I can tell the code does not perform an update or allow an update to be performed.

I am not sure how we would do this in code but the helm command to update a repo is
`helm repo update`
Unfortunately this will update all repos.

```yaml

```

**Comment by Akasurde** [comment]
@rendhalver Thanks for reporting this. Could you please provide a sample command or flag which is used to achieve this functionality? Thanks.

**Comment by rendhalver** [comment]
> @rendhalver Thanks for reporting this. Could you please provide a sample command or flag which is used to achieve this functionality? Thanks.

Ah sorry. I have updated the description to include the repo update command.

**Comment by abikouo** [comment]
@rendhalver the ``helm`` module is already running ``helm repo update`` when parameter ``update_repo_cache`` is set to True.

**Comment by rendhalver** [comment]
Ah I had seen that before but didn't want to update the cache each time.
I have found a way around this by using the `chart_repo_url` option on the `helm` module which seems to do the job.

I will close this for now.

Thanks for the help.

**Comment by DrackThor** [comment]
Hi @rendhalver! Could you please post your task?
I did not quite understand how you've achieved to update your added helm repos only once?
I've tried with..
`yaml
- name: repo update
  kubernetes.core.helm:
    update_repo_cache: yes
`
.. but this does not work :/

**Comment by mohag** [comment]
> Hi @rendhalver! Could you please post your task? I did not quite understand how you've achieved to update your added helm repos only once? I've tried with..
> 
> ```yaml
> - name: repo update
>   kubernetes.core.helm:
>     update_repo_cache: yes
> ```
> 
> .. but this does not work :/

It works, with lots of gymnastics.... (some of this is due to bugs in the version bundled with Ansible 4.5., like HELM_KUBECONTEXT, which is fixed in the current version here)

The task equivalent to `helm repo update` is:

```yaml
  - name: helm repo update
    kubernetes.core.helm:
      state: absent
      binary_path: /usr/local/bin/helm3
      release_name: dummy # tricks needed to refresh in separate step
      kubeconfig: "{{ kubectl_config | default(omit) }}"  # This shouldn't talk to a cluster, but it does
      context: "{{ kubectl_context | default(omit) }}"
      release_namespace: kube-system
      update_repo_cache: true
    environment:
      HELM_DEBUG: "{{ ansible_verbosity > 1 }}"
      HELM_KUBECONTEXT: "{{ kubectl_context | default('') }}" # The context parameter on the modules seems to be ignored currently
```
(with some stuff specific to my playbooks)
