### ISSUE TITLE
not possible to replace/update objects via "apply: yes" or "force: yes" in OpenShift 3.11

### ISSUE THREAD

**Issue by c0desurfer** [ansible-collections/kubernetes.core#16]
##### SUMMARY
There are actually 2 problems we face. The first one is that large definitions are not updated at all when `apply: yes` is used. We have a file with CRD definition that has over 7500 lines. Ansible does not show any errors and it looks like the the update was made. However after inspecting the CRD on the server you can see that no update took place. You can use the Kafka CRD from the Strimzi project at https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.21.1/strimzi-crds-0.21.1.yaml to reproduce the issue. We tried `force: yes` but you can't really use it because the `resourceVersion` property is missing in the definition but is needed for `force: yes`.

The second problem is that objects are not really updated when using `apply: yes` (and yet again we can't use `force: yes` because the `resourceVersion` property is missing in the definition). We have a definition like the following one (few fields removed for simplification) on our OpenShift 3.11 cluster.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-name
  namespace: my-name-space
spec:
  entityOperator:
    template:
      tlsSidecarContainer:
        env:
          - name: TZ
            value: Europe/Zurich
[...]
```

Our new definition does not contain the path `spec.entityOperator.template.tlsSidecarContainer` anymore but after the following task runs, it is still in place and not removed on the server.

```
- name: deploy cluster
  k8s:
    namespace: "{{ project }}"
    state: present
    apply: yes
    definition: "{{ lookup('template', 'definition.j2') }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s module

##### ANSIBLE VERSION
```
ansible 2.10.5
  config file = ~/Code/Ansible/playbooks/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.pyenv/versions/3.9.1/envs/default/lib/python3.9/site-packages/ansible
  executable location = ~/.pyenv/versions/default/bin/ansible
  python version = 3.9.1 (default, Jan 30 2021, 21:53:22) [Clang 12.0.0 (clang-1200.0.32.29)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(~/Code/Ansible/playbooks/ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(~/Code/Ansible/playbooks/ansible.cfg) = True
DEFAULT_ROLES_PATH(~/Code/Ansible/playbooks/ansible.cfg) = ['/Users/b0rski/Code/Ansible/playbooks/roles']
DEFAULT_STDOUT_CALLBACK(~/Code/Ansible/playbooks/ansible.cfg) = yaml
INTERPRETER_PYTHON(~/Code/Ansible/playbooks/ansible.cfg) = ~/.pyenv/shims/python
```

##### OS / ENVIRONMENT
MacOS X Big Sur and Redhat Linux 7

##### STEPS TO REPRODUCE
Please use files and examples from description above (Strimzi CRDs).

##### EXPECTED RESULTS
We expect that paths get deleted if they're not defined in a definition anymore. No merge but replace must be done.

##### ACTUAL RESULTS
As described above fields are not removed and remain untouched in the definition on server.
