### ISSUE TITLE
helm diff not working when using kubernetes.core.helm with on-the-fly templating

### ISSUE THREAD

**Issue by SpikePy** [ansible-collections/kubernetes.core#174]
##### SUMMARY
When using the module _kubernetes.core.k8s_ with on-the-fly templating helm diff seems not to work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- kubernetes.core.helm

##### ANSIBLE VERSION
```paste below
ansible 2.10.11
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 19:27:32) [GCC 8.3.0]
```

##### COLLECTION VERSION
```paste below
kubernetes.core    2.1.1
```

##### CONFIGURATION
```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(env: ANSIBLE_LOAD_CALLBACK_PLUGINS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
debian buster

##### STEPS TO REPRODUCE

1. Install helm diff
2. Run this task on a target machine with a valid *values_redis.yml.j2*

```yaml
- name: Install/Upgrade redis
  kubernetes.core.helm:
    chart_repo_url: https://charts.bitnami.com/bitnami
    chart_ref: redis
    release_namespace: '{{ redis_namespace }}'
    name: redis
    chart_version: '{{ redis_helm_version }}'
    release_values: '{{ lookup("template", "values_redis.yml.j2") | from_yaml }}'
```

##### EXPECTED RESULTS
Chart gets deployed without errors

##### ACTUAL RESULTS
I get the following warning even when helm diff is installed

```paste below
[WARNING]: The default idempotency check can fail to report changes in certain cases. Install helm diff for better results.
```

**Comment by erikgb** [comment]
I can confirm this behavior, and I am running inside a container image - where I am sure `helm diff` is installed correctly.

````shell
ansible@941670c1fde5:~$ helm plugin list
NAME    VERSION DESCRIPTION
diff    3.1.3   Preview helm upgrade changes as a diff
ansible@941670c1fde5:~$
````

**Comment by gravesm** [comment]
Just looked into this and as @erikgb points out this is intentional. Up until about a month ago helm diff did not support the `--repo` option. Unfortunately, there is still no release of helm diff with this change.

**Comment by internetionals** [comment]
The latest release of the helm diff plugin (3.4.1) seems to have the `--repo` option.

**Comment by aramatev** [comment]
upgrade helm diff to newer version? 
at time of this writing, helm diff plugin is v 3.6.0
```
helm plugin install https://github.com/databus23/helm-diff
```

**Comment by aramatev** [comment]
upgrade helm diff to newer version? 
at time of this writing, helm diff plugin is v 3.6.0
```
helm plugin install https://github.com/databus23/helm-diff
```

**Comment by zarinbal** [comment]
I used the following task to install the latest version of helm diff and fixed the issue for my self
```
- name: Install Helm Diff
  tags: ["kube", "base"]
  become: false
  kubernetes.core.helm_plugin:
    plugin_path: "https://github.com/databus23/helm-diff"
    state: present
```
