### ISSUE TITLE
Namespace creation with wait_condition hangs

### ISSUE THREAD

**Issue by datYori** [ansible-collections/kubernetes.core#201]
##### SUMMARY

While doing 

```
- name: Make sure the desired raw namespace exists
  kubernetes.core.k8s:
    name: "some_namespace"
    api_version: v1
    kind: Namespace
    state: present
    wait: yes
    wait_sleep: 1
    wait_timeout: 30
    wait_condition:
      type: Active
```
I would expect playbook to go to next step wihtout error, this is not the case

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s
##### ANSIBLE VERSION

```paste below
ansible [core 2.11.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/yann/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/yann/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 2.11.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection      Version
--------------- -------
kubernetes.core 2.0.0
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```
