### ISSUE TITLE
Using dots for value keys in kubernetes.core.helm.values yields unexpected results

### ISSUE THREAD

**Issue by artiommocrenco** [ansible-collections/kubernetes.core#210]
##### SUMMARY
Using dots for value keys in kubernetes.core.helm.values yields unexpected results

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.helm

##### ANSIBLE VERSION
```
ansible [core 2.11.4] 
  config file = None
  python version = 3.9.2
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
Collection           Version
-------------------- -------
kubernetes.core      2.1.1  
```

##### CONFIGURATION
```paste below
default configuration
```

##### OS / ENVIRONMENT
Debian 11

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  become: false
  tasks:
    - kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"
    - kubernetes.core.helm:
        name: etcd
        chart_ref: bitnami/etcd
        release_namespace: bitnami-etcd
        create_namespace: true
        values:
          persistence.size: 10Gi
          auth.rbac.enabled: false
```

##### EXPECTED RESULTS

Executing this play:

Expected to yield a 10Gi PVC
Expected to not fail with any moment with `common.errors.upgrade.passwords.empty` bitnami validation error

Expected to be equivalent for

```
helm upgrade --install etcd bitnami/etcd \
  --namespace=bitnami-etcd \
  --create-namespace \
  --set persistence.size=10Gi \
  --set auth.rbac.enabled=false
```

##### ACTUAL RESULTS

Yields 8Gi (chart default) PVC
Fails occasionally with `common.errors.upgrade.passwords.empty` error

Main reason: variables with dots seem to be ignored completely

**Comment by artiommocrenco** [comment]
This seems to work
```yaml
    - kubernetes.core.helm:
        name: etcd
        chart_ref: bitnami/etcd
        release_namespace: bitnami-etcd
        create_namespace: true
        values:
          persistence:
            size: 10Gi
          auth:
            rbac:
              enabled: false
```
