### ISSUE TITLE
kubernetes.core.k8s_info kind: Event prints events in ansible-operator log

### ISSUE THREAD

**Issue by stiller-leser** [ansible-collections/kubernetes.core#214]
##### SUMMARY
```yaml
# EVENTS
    - name: Fetching v1/Events
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Event
        namespace: "{{ ansible_operator_meta.namespace }}"
      register: raw_events

    - name: Process API events to determine time we will use
      vars:
        new_timestamp: "{{ item.lastTimestamp | ternary({}, {'lastTimestamp': item.eventTime}) }}"
        current_event: "{{ item | combine(new_timestamp) }}"
      set_fact:
        processed_api_events: "{{ processed_api_events | default([]) + [current_event] }}"
      loop: "{{ raw_events['resources'] }}"

```

When used in the ansible-operator the events are printed to the log output, eventhough
```
        - --ansible-verbosity=1
        - --zap-log-level=error
```

I am aware that this is potentially an operator issue, but the "Events" part is the only one where everything is printed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s_info:

##### ANSIBLE VERSION

```paste below
ansible 2.9.19
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/openshift']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Aug 18 2020, 08:56:04) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

Using latest though I believe, below requirements.yml

---
collections:
  - name: kubernetes.core
  - name: operator_sdk.util
    version: "=0.2.0"
```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(env: ANSIBLE_GATHERING) = explicit
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/openshift']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible/roles']
```

##### OS / ENVIRONMENT

bash-4.4$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"

##### STEPS TO REPRODUCE

```yaml
See description
```

##### EXPECTED RESULTS

I would expect the events logs not being written.

##### ACTUAL RESULTS

Events logs are written
