### ISSUE TITLE
helm module should support the equivalent of the command line --history-max flag

### ISSUE THREAD

**Issue by dojones1** [ansible-collections/kubernetes.core#22]
##### SUMMARY
HELM module should allow equivalent configuration of the --history-max field.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.kubernetes.helm

##### ADDITIONAL INFORMATION
When the helm module is invoked to trigger an upgrade it results in additional secrets being created up to the default maximum (10) of the form: sh.helm.release.v1.<release>.v<deployment#>. 

This requires a large number of secrets being configured as the quota in the K8s cluster. If it supported the CLIs --history-max option, then deployments would be capped at a much lower threshold.

If run manually I would do helm upgrade -f file --history-max value release chart

Example configuration:
```yaml
  community.kubernetes.helm:
    name: test
    chart_ref: stable/grafana
    release_namespace: monitoring
    history_max: 2
```
