### ISSUE TITLE
label_selectors -set list of label dynamically

### ISSUE THREAD

**Issue by talcoh2x** [ansible-collections/kubernetes.core#224]
Hi all, need your help please 
I'm trying on k8s_info + jinja add list of label  dynamically.
for example label_selectors will get list of label dynamically

statis label:
```yaml  
- name: Get a list of all VM's
    k8s_info:
      kind: VirtualMachine
      namespace: "{{ metadata.namespace }}"
      label_selectors:
        - "key=vaule"
    register: vm_list
```

dynamic label:

```yaml  
- name: Get a list of all VM's
    k8s_info:
      kind: VirtualMachine
      namespace: "{{ metadata.namespace }}"
      label_selectors:
      {% for label in k8s_labels %}
        - {{ label }}
      {% endfor %}
    register: vm_list
```
