### ISSUE TITLE
k8s_exec's return value has no rc but 'return_code'

### ISSUE THREAD

**Issue by itaru2622** [ansible-collections/kubernetes.core#229]
##### SUMMARY

ansible document says about return value in https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#rc
```
(attribute) rc:
Some modules execute command line utilities or are geared for executing commands directly (raw, shell, command, and so on), this field contains ‘return code’ of these utilities.
```
k8s_exec doesn't have attribute 'rc' but 'return_value' as follows:
https://github.com/ansible-collections/kubernetes.core/blob/ddbc1611218c91cc608ee6efc950602783f61d78/plugins/modules/k8s_exec.py#L181-L187

as the result, migration cost increases ( from "command: kubectl exec" to "k8s_exec:" ).

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible [core 2.11.4] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list kubernetes.core
# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.1.1  

# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 1.2.1  
```

##### CONFIGURATION

```paste below
# ansible-config dump --only-changed

```

##### OS / ENVIRONMENT

debian:bullseye

##### STEPS TO REPRODUCE

```yaml
# before miguration (kubectl)
---
  block:
  - name: "execute cmd by kubectl"
    command: kubectl exec -n {{ namespace }} {{ pod }}  -c {{ container }} -- /bin/bash -c '{{ cmd }}'
    register: result
  - name: "result.rc == {{result.rc}}"
    debug:
      var: result

# after migration (k8s_exec)
---
  - name: "execute cmd by k8s_exec"
    kubernetes.core.k8s_exec:
       namespace:  "{{ namespace }}"
       pod:        "{{ pod }}"
       container:  "{{ container }}"
       command: /bin/bash -c '{{cmd}}'
    register: result
# following line will raise exception... then, migration requires additional 'set_fact:' for result.rc = result.return_code.
  - name: "result.rc == {{result.rc}}"
    debug:
      var: result
```

##### EXPECTED RESULTS

the above sample should succeeded without exception and result.rc should have value. 

##### ACTUAL RESULTS

it raises exception just after k8s_exec (i.e. accessing result.rc in debug).
```
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'rc'
```
to avoid excepion, extra set_fact requires for result.rc = result.return_code

```paste below

```
