### ISSUE TITLE
Unexpected CronJob behavior. Fails to create CronJob

### ISSUE THREAD

**Issue by aneurinprice** [ansible-collections/kubernetes.core#23]
##### SUMMARY
Attempting to create a cronjob with kind `CronJob` and apiVersion `batch/v1beta1` yields `"Failed to find exact match for v1.CronJob by [kind, name, singularName, shortNames]"`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```
ansible 2.9.14

```

##### CONFIGURATION
```
bash-5.0# ansible-config dump --only-changed

bash-5.0# 



```

##### OS / ENVIRONMENT
```
bash-5.0# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.3
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

Jenkins Docker Container
```

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  tasks:
    - name: Create Resource
      community.kubernetes.k8s:
        state: present
        definition:
          api_Version: batch/v1beta1
          kind: CronJob
          metadata:
            name: test-cronjob
            namespace: default
          schedule: "@daily"
          jobTemplate:
            spec:
              containers: 
                - name: test1
                  image: busybox

```

##### EXPECTED RESULTS

A cronjob called "test-cronjob" to be created in the default namespace

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find exact match for v1.CronJob by [kind, name, singularName, shortNames]"}


```
