### ISSUE TITLE
kybernetes.core dependency to "ansible.builtin.meta" plugin cannot be resolved and may not be declared properly

### ISSUE THREAD

**Issue by darac79** [ansible-collections/kubernetes.core#240]
##### SUMMARY

I am implementing a role that utilizes kybernetes.core and cloud.common collections to deploy to openshift using kubernetes.core.k8s. When executing the role locally (without a /meta/main.yml file in the role) it works without errors. As soon as I define its dependencies by creating a meta/main.yml (as I want to turn it into a galaxy role) a warning is prompted at the end of the execution. Functionality seems not to be affected - seems to be working properly .

`[WARNING]: errors were encountered during the plugin load for meta: ['ansible-collections.cloud.common.meta is not a valid collection reference', 'ansible-collections.kubernetes.core.meta is not a valid collection
reference']`

My assumption is that ansible.builtin.meta is used within one of the two collections - most probably kybernetes.core - using the relative name (without ansible.builtin prefix).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s

##### ANSIBLE VERSION

```
$ ansible --version
ansible [core 2.11.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dostricki/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/dostricki/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, May 20 2021, 11:41:59) [GCC 10.2.0]
  jinja version = 3.0.1
  libyaml = False
```

##### COLLECTION VERSION

```
$ ansible-galaxy collection list cloud.common
# /home/dostricki/.ansible/collections/ansible_collections
Collection   Version
------------ -------
cloud.common 2.0.4

$ ansible-galaxy collection list kubernetes.core
# /usr/local/lib/python3.8/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 1.2.1

# /home/dostricki/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.2.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Win 10
Cygwin v3.2.0(0.340/5/3)
Python v3.8.10
Ansible v2.11.1
kubernetes.core collection v2.2.0

##### STEPS TO REPRODUCE

```yaml
creating a role that utilizes k8s maybe in the tasks/main.yml
by executing e.g. a code snippet like that

- name: service cluster rollout
  kubernetes.core.k8s:
    api_version: v1
    validate_certs: no
    ca_cert: '{{ openshift.root_certificate }}'
    host: "{{ openshift_url }}"
    api_key: "{{ openshift.login.service_account_token }}"
    template: deployments.yaml
    state: present
  when: some_condition | bool


role should have a meta/main.yml with the following contents
dependencies: [] 
collections:
  - ansible.builtin
  - ansible-collections.cloud.common
  - ansible-collections.kubernetes.core
```

##### EXPECTED RESULTS
The playbook should execute without errors - all dependencies should be resolvable

##### ACTUAL RESULTS
Ansible prints a warning thatthe meta module could not be resolved.

```paste below

```

**Comment by Akasurde** [comment]
@darac79 Thanks for reporting this issue. The content should be - 

```yaml
dependencies: [] 
collections:
  - ansible.builtin
  - cloud.common
  - kubernetes.core
```
