### ISSUE TITLE
Expose `kubectl delete <type> <name> --force`

### ISSUE THREAD

**Issue by kaovilai** [ansible-collections/kubernetes.core#248]
##### SUMMARY

Enable force deletion of objects.
[See `kubectl` DeleteOptions](https://github.com/kubernetes/kubectl/blob/0f88fc6b598b7e883a391a477215afb080ec7733/pkg/cmd/delete/delete.go#L110)
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s
##### ADDITIONAL INFORMATION

This feature would be used to clean up infrastructure before clean re-deployment of workloads. Data loss is not a concern.

```yaml
- name: get remaining pods to force delete
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ ocs_namespace }}"
  register: leftover_pods
- name: remove csirbd pod
  k8s:
    state: absent
    definition: "{{ item }}"
    delete_options:
      gracePeriodSeconds: -1
      force: yes #<< add this field
  loop: leftover_pods.get('resources', [])
```
