### ISSUE TITLE
Apply resources from a directory containing kustomization.yaml

### ISSUE THREAD

**Issue by anantmishra** [ansible-collections/kubernetes.core#270]
##### SUMMARY
Apply resources from a directory containing kustomization.yaml. This is equivalent to running the command:

```bash
kubectl apply -k dir/
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
kubernetes.core.k8s

##### ADDITIONAL INFORMATION
Essentially it is equivalent to running the command **kubectl apply -k /path/to/my/manifest-directory** in case the state is present. Incase the state is absent the result is equivalent to the command **kubectl delete -k /path/to/my/manifest-directory**.

```yaml
- name: Apply all the manifest in the specified directory 
  kubernetes.core.k8s:
    state: present
    src: /path/to/my/manifest-directory
```
