### ISSUE TITLE
lookup plugin ignores K8S_AUTH_KUBECONFIG variable

### ISSUE THREAD

**Issue by jeromewaibel** [ansible-collections/kubernetes.core#277]
##### SUMMARY
The documentation says the kubeconfig parameter can also be specified in an environment variable ("Can also be specified via K8S_AUTH_KUBECONFIG environment variable.") yet this variable is ignored when set inside a playbook.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lookup('kubernetes.core.k8s')

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
kubernetes.core               1.2.1
```

##### CONFIGURATION
```paste below
(empty)
```

##### OS / ENVIRONMENT
Ubuntu 20.10

##### STEPS TO REPRODUCE

Run this playbook. The second task will fail.

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local

  environment:
    K8S_AUTH_KUBECONFIG: /path/to/kube.config

  tasks:

# this works fine
  - name: Ensure the Namespace exists.
    kubernetes.core.k8s:
      kind: Namespace
      name: "test"
      state: present

# this does not work
  - name: Fetch a list of namespaces
    set_fact:
      projects: "{{ lookup('kubernetes.core.k8s', api_version='v1', kind='Namespace') }}
```

##### EXPECTED RESULTS
Playbook should run and fetch a list of namespaces.

##### ACTUAL RESULTS
```paste below
TASK [Fetch a list of namespaces] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'kubernetes.core.k8s'. Error was a <class 'kubernetes.config.config_exception.ConfigException'>, original message: Invalid kube-config file. No configuration found."}
```
