### ISSUE TITLE
Module for creating Job from CronJob

### ISSUE THREAD

**Issue by stanislaw55** [ansible-collections/kubernetes.core#29]
##### SUMMARY

It may be very specific use case but I need to create Job using CronJob object. Right now, I have to resort to `command` module in order to do that:
```yaml
- name: Test my CronJob
  command: kubectl --namespace {{ namespace }} job --from=cronjob/my-cron test-job
  register: test_job
  failed_when:
    - test_job.rc != 0
    - "already exists" not in test_job.stdout
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s_job

##### ADDITIONAL INFORMATION

One use case would be to test CronJobs that are running very seldom. Other use case may that: there's already defined but complicated CronJob for some task i.e. creating backup from database. Creating Job from CronJob allows performing this action on demand.

```yaml
- name: Test CronJob using Job
  k8s_job:
    name: test-job
    from_cronjob: some-cronjob
    state: present
```
this module would need also other options from `k8s` module like for waiting and validation.

This is just very loose idea - it may be better to create more generic module or completely restructure my proposal in case of being generic.

**Comment by JtMotoX** [comment]
Just in case someone comes across this as I did, here is how I am doing it using the k8s module.

```yaml
- name: Get cronjob definition
  k8s_info:
    kind: CronJob
    name: my-cron
  register: cronjob_definition_response
  failed_when: (cronjob_definition_response.resources | default([]) | length) != 1

- name: Trigger the job
  k8s:
    state: present
    definition:
      kind: Job
      apiVersion: batch/v1
      metadata:
        name: "{{ cronjob_definition.metadata.name }}-init-{{ lookup('pipe', 'date +%s') }}"
        ownerReferences:
          - apiVersion: batch/v1
            kind: CronJob
            name: "{{ cronjob_definition.metadata.name }}"
            uid: "{{ cronjob_definition.metadata.uid }}"
      spec: "{{ cronjob_definition.spec.jobTemplate.spec }}"
    wait: true
    wait_timeout: 180
    wait_condition:
      type: Complete
      status: True
  vars:
    cronjob_definition: "{{ cronjob_definition_response.resources[0] }}"
  register: cronjob_trigger
  ignore_errors: true

- name: Fail if job is hung or failed
  fail:
    msg: "Job is hung or failed"
  when: (cronjob_trigger.failed | default(true)) | bool == true
```
