### ISSUE TITLE
k8s_drain not working properly with 'state: drain'

### ISSUE THREAD

**Issue by felipe4334** [ansible-collections/kubernetes.core#292]
##### SUMMARY
when using module k8s_drain with state: drain it outputs an error of "local variable 'pod_names' referenced before assignment"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s_drain  with option: "state: drain"

##### ANSIBLE VERSION

```paste below
2.11.6 and on 2.9
```

##### COLLECTION VERSION

```paste below
~/.ansible/collections/ansible_collections : 2.2.1
~/../lib/python3.8/site-packages/ansible_collections: 1.2.1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Cent OS 7

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Try draining a node with module like this:
```
    - name: drain the old nodes
      kubernetes.core.k8s_drain: 
        context: "{{ k8_cluster_context }}"
        state: drain  
        name: "{{ item }}"
        delete_options:
          terminate_grace_period: 900
      loop: "{{ k8_nodepool_privateips }}"
      register: k8_node_drain_results
```

##### ACTUAL RESULTS

```paste below
failed: [localhost] (item=10.50.133.187) => {"ansible_loop_var": "item", "changed": false, "item": "10.50.133.187", "msg": "Failed to list pod from node 10.50.133.187 due to: local variable 'pod_names' referenced before assignment"}
```
