### ISSUE TITLE
kustomize command failed with: Error: evalsymlink failure on './overlays/{{ env }}'

### ISSUE THREAD

**Issue by noahjd** [ansible-collections/kubernetes.core#299]
##### SUMMARY
Trying to use the kustomize lookup plugin to build resources in ansible like below:
kubernetes.core.k8s:
        state: present
        # definition: "{{ lookup('file', '{{ item }}.yaml') }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='./overlays/{{ env }}') }}"
        kubeconfig: ./kubeconfig
        context: "{{ k8s_cluster_context }}"
        wait: no
        wait_timeout: 600
        validate_certs: no
        apply: yes
        namespace: "{{ namespace }}"
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kustomize lookup plugin, k8s core module
##### ANSIBLE VERSION

```
ansible 2.10.15
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

##### COLLECTION VERSION

```
# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 1.2.0  

# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.2.0  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 20.04 docker container

##### STEPS TO REPRODUCE

1. Run a playbook with the code pasted above in ci/cd pipeline. With base/kustomization.yaml dir and overlays/dev/kustomization.yaml layout

```yaml
vars:
    env: "{{ lookup('env', 'ENVIRONMENT') }}"
    namespace: "{{ lookup('env', 'NAMESPACE') }}"
    k8s_cluster_context: "{{ lookup('env', 'KUBERNETES_CLUSTER_CONTEXT') }}"
kubernetes.core.k8s:
        state: present
        # definition: "{{ lookup('file', '{{ item }}.yaml') }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='./overlays/{{ env }}') }}"
        kubeconfig: ./kubeconfig
        context: "{{ k8s_cluster_context }}"
        wait: no
        wait_timeout: 600
        validate_certs: no
        apply: yes
        namespace: "{{ namespace }}"
```

##### EXPECTED RESULTS
I expected the overlay to get built from the plugin

##### ACTUAL RESULTS

Received an error described in title

```
TASK [Deploy individual Microservice Kubernetes Deployment - api] ******
task path: /home/jenkins/agent/workspace/microservices/deploy-microservices-test/deploy_to_kubernetes.yml:136
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'kubernetes.core.kustomize'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: kustomize command failed with: Error: evalsymlink failure on './overlays/{{ env }}' : lstat /home/jenkins/agent/workspace/microservices/deploy-microservices-test/overlays/{{ env }}: no such file or directory\n"
}
```
