### ISSUE TITLE
Missing flags on template module

### ISSUE THREAD

**Issue by Alfedi** [ansible-collections/kubernetes.core#313]
##### SUMMARY

Template command has a lot of flags not available in the `helm_template` module, for instance you cannot set a namespace to the generated template or a name.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`helm_template`
##### ADDITIONAL INFORMATION

This will simply add at least the same parameters as the `helm` module. This way the module will be as useful as the helm template command. It would be something like this:

```yaml
- name: Generate template of Prometheus chart
  kubernetes.core.helm_template:
    name: test
    chart_ref: stable/prometheus
    release_namespace: monitoring
    create_namespace: true
    include_crds: true
    disable_hook: true
```
