### ISSUE TITLE
Document usage of kubernetes.core.helm to do a `helm repo update`

### ISSUE THREAD

**Issue by VannTen** [ansible-collections/kubernetes.core#316]
##### SUMMARY

The documentation for `kubernetes.core.helm`, option `update_repo_cache` says the following (emphasis mine): 
```
- update_repo_cache
        Run `helm repo update' before the operation. Can be run as part of the
        package installation **or as a separate step**.
        [Default: False]
        type: bool
```
However, how to update the repo cache as a separate step is not obvious. One has to do ["lots of gymnastics"](156#issuecomment-990682141) :
```
  - name: helm repo update
    kubernetes.core.helm:
      state: absent
      binary_path: /usr/local/bin/helm3
      release_name: dummy # tricks needed to refresh in separate step
      release_namespace: kube-system
      update_repo_cache: true
```
This workaround should be documented, or maybe a more explicit way could be added ?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

kubernetes.core.helm

##### ANSIBLE VERSION

```
ansible [core 2.12.1]
  config file = /home/max/dev_com/kubespray/ansible.cfg
  configured module search path = ['/home/max/dev_com/kubespray/library']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/max/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```
