### ISSUE TITLE
support generateName or utils like that

### ISSUE THREAD

**Issue by alaypatel07** [ansible-collections/kubernetes.core#35]
##### SUMMARY

In order to make sure that resources created by k8s module has unique
name, there is some work involded to be done in ansible. kubernetes
api-server has a `metadata.generateName` field which can be used
to create a name that is within the limits of max chars allowed for the 
resource. It would be great if the k8s module allows creation of 
resources with generateName so the user does not have to take
care of limits of `metadata.Name`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s

##### ADDITIONAL INFORMATION

```yaml
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  generateName: utilitypod-
  namespace: blah-dev
  labels:
    purpose: utility-pod
spec:
  containers:
    - name: utilitypod
      image: blahblah/utilitypod:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 28800; done;" ]
      env:
        - name: KUBERNETES_SERVICE_HOST
          value: "api.dev.blah.internal"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
EOF

```

Taken from this stackoverflow thread https://stackoverflow.com/questions/48023475/add-random-string-on-kubernetes-pod-deployment-name
