### ISSUE TITLE
k8s_exec does not behave the same as kubectl exec on a pod with 2 containers.

### ISSUE THREAD

**Issue by asmacdo** [ansible-collections/kubernetes.core#358]
##### SUMMARY
k8s_exec does not handle pods with multiple containers the same way kubectl exec does.

kubectl will default to one of the containers, but k8s_exec fails with an unhelpful 400 Bad Request.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_exec

##### ANSIBLE VERSION
```
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/austin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/austin/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/austin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/austin/.local/bin/ansible
  python version = 3.9.9 (main, Nov 19 2021, 00:00:00) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
kubernetes.core               2.2.2  
```

##### OS / ENVIRONMENT
Fedora 33

##### STEPS TO REPRODUCE

1. Deploy a pod with 2 containers to the cluster
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-two-containers
  namespace: default
spec:
  containers:
    - name: ubi-minimal
      image: registry.access.redhat.com/ubi8/ubi:8.4-209
      command: ["/bin/sh", "-ec", "sleep 1000"]
    - name: ubi-minimal-2
      image: registry.access.redhat.com/ubi8/ubi:8.4-209
      command: ["/bin/sh", "-ec", "sleep 1000"]
```
2. 
`kubectl exec pod-with-two-containers -- echo "test"`
```
Defaulted container "ubi-minimal" out of: ubi-minimal, ubi-minimal-2
test
```

However with k8s_exec, we get a 400 error 

```
- name: Execute a command
  kubernetes.core.k8s_exec:
    namespace: default
    pod: pod-with-two-containers
    # container: manager  # fails when this is not set
    command: echo "hello"
```
```
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to execute on pod curl-pod due to : (0)\nReason: Handshake status 400 Bad Request\n"}`
```

##### EXPECTED RESULTS

I expected it to work, since kubectl exec did. But even if non-defaulting behavior is intended, the error message is not helpful. 

##### ACTUAL RESULTS

```
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to execute on pod curl-pod due to : (0)\nReason: Handshake status 400 Bad Request\n"}`
```
