### ISSUE TITLE
kubernetes.core.helm_plugin namespace option

### ISSUE THREAD

**Issue by txynidakis** [ansible-collections/kubernetes.core#365]
##### SUMMARY
Include a 'namespace' option to the module

the older community.kubernetes.helm_plugin had this option with 'release_name'

could this be ported to the new collection please?

##### ISSUE TYPE
- Feature enhancement

##### ADDITIONAL INFORMATION
|The older community.kubernetes.helm_plugin had this option with 'release_name'

Could this be ported to the new collection please?

**Comment by Akasurde** [comment]
@txynidakis Thanks for reporting this issue. I accidentally removed `release_namespace` or `namespace` via https://github.com/ansible-collections/community.kubernetes/pull/358. I think we need to add it again.

**Comment by Akasurde** [comment]
@txynidakis Can you please provide the output of `helm plugin list --namespace <NS>` and without namespace? I am not able to list plugins based upon namespace.

**Comment by txynidakis** [comment]
HI @Akasurde 
Apologies for the delay, I knew I had work coming up on the playbook that generated the error so waited until the sprint ticket started.

The original play was 
```yaml
- name: Install Helm env plugin
  community.kubernetes.helm_plugin:
    plugin_path: "{{ item }}"
    state: present
    release_namespace: default
    binary_path: /usr/local/bin/helm
  become: yes
  become_user: eksman
  loop:
    - "https://github.com/databus23/helm-diff --version master"
    - https://github.com/hypnoglow/helm-s3.git
```

where there was the option  'release_namespace: default'
I just blindly replaced the community name  and renamed the playbook which produced the error.

You are correct in saying helm repo doesn't need a namespace.

So the ansible play was re-coded to use 'community.kubernetes.helm_plugin' and removed the 'namespace' option and the playbook ran as expected.

Apologies I should have looked at the issue more holistically.

The issue can be closed
Thanks for the quick response through.
