### ISSUE TITLE
Scaling down of statefulset using kubernetes.core.k8s_scale fails with Resource scaling timed out on ppc64le only.

### ISSUE THREAD

**Issue by rayankiy** [ansible-collections/kubernetes.core#376]
We have a task to scale down the statefulset by using kubernetes.core.k8s_scale as shown below .  

```


- name: Scale etcd down for upgrade
  kubernetes.core.k8s_scale:
    api_version: v1
    kind: StatefulSet
    name: wml-deployments-etcd
    namespace: "{{ namespace }}"
    replicas: 0
    wait_timeout: 300

```
We see a peculiar behavior on power clusters (ppc64le) where in the above scale down fails with Resource scaling timed out.

```
TASK [Scale etcd down for upgrade] ********************************
^[[0;31mfatal: [localhost]: FAILED! => {"changed": false, "duration": 300, "msg": "Resource scaling timed out", "result": {"apiVersion": "apps/v1", "kind": "StatefulSet", "metadata": {"creationTimestamp": "2022-02-10T01:04:58Z", "generation": 2, "labels": {"app": "wml-deployments-etcd", "app.kubernetes.io/instance": "wml", "app.kubernetes.io/managed-by": "Tiller", "app.kubernetes.io/name": "wml", "chart": "ibm-wml-prod-3.5.10", "helm.sh/chart": "ibm-wml-prod-3.5.10", "heritage": "Tiller", "release": "wml"}, "managedFields": [{"apiVersion": "apps/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:labels": {".": {}, "f:app": {}, "f:app.kubernetes.io/instance": {}, "f:app.kubernetes.io/managed-by": {}, "f:app.kubernetes.io/name": {}, "f:chart": {}, "f:helm.sh/chart": {}, "f:heritage": {}, "f:release": {}}}, "f:spec": {"f:podManagementPolicy": {}, "f:replicas": {}, "f:revisionHistoryLimit": {}, "f:selector": {}, "f:serviceName": {}, "f:template": {"f:metadata": {"f:annotations": {".": {}, "f:cloudpakId": {}, "f:cloudpakInstanceId": {}, "f:cloudpakName": {}, "f:hook.activate.cpd.ibm.com/command": {}, "f:hook.deactivate.cpd.ibm.com/command": {}, "f:productChargedContainers": {}, "f:productCloudpakRatio": {}, "f:productID": {}, "f:productMetric": {}, "f:productName": {}, "f:productVersion": {}}, "f:labels": {".": {}, "f:app": {}, "f:app.kubernetes.io/instance": {}, "f:app.kubernetes.io/managed-by": {}, "f:app.kubernetes.io/name": {}, "f:chart": {}, "f:helm.sh/chart": {}, "f:heritage": {}, "f:icpdsupport/addOnId": {}, "f:icpdsupport/app": {}, "f:release": {}, "f:serviceSelector": {}}, "f:name": {}}, "f:spec": {"f:affinity": {".": {}, "f:nodeAffinity": {".": {}, "f:requiredDuringSchedulingIgnoredDuringExecution": {".": {}, "f:nodeSelectorTerms": {}}}, "f:podAntiAffinity": {".": {}, "f:preferredDuringSchedulingIgnoredDuringExecution": {}}}, "f:containers": {"k:{\"name\":\"etcd\"}": {".": {}, "f:command": {}, "f:env": {".": {}, "k:{\"name\":\"ETCDCTL_API\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCDCTL_CACERT\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_ADVERTISE_CLIENT_URLS\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_CERT_FILE\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_DATA_DIR\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_INITIAL_ADVERTISE_PEER_URLS\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_INITIAL_CLUSTER\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_INITIAL_CLUSTER_STATE\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_INITIAL_CLUSTER_TOKEN\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_KEY_FILE\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_LISTEN_CLIENT_URLS\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_LISTEN_PEER_URLS\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"ETCD_NAME\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"GOMAXPROCS\"}": {".": {}, "f:name": {}, "f:value": {}}, "k:{\"name\":\"POD_NAME\"}": {".": {}, "f:name": {}, "f:valueFrom": {".": {}, "f:fieldRef": {".": {}, "f:apiVersion": {}, "f:fieldPath": {}}}}, "k:{\"name\":\"ROOT_PASSWORD\"}": {".": {}, "f:name": {}, "f:valueFrom": {".": {}, "f:secretKeyRef": {".": {}, "f:key": {}, "f:name": {}}}}, "k:{\"name\":\"SET_NAME\"}": {".": {}, "f:name": {}, "f:value": {}}}, "f:image": {}, "f:imagePullPolicy": {}, "f:livenessProbe": {".": {}, "f:failureThreshold": {}, "f:initialDelaySeconds": {}, "f:periodSeconds": {}, "f:successThreshold": {}, "f:tcpSocket": {".": {}, "f:port": {}}, "f:timeoutSeconds": {}}, "f:name": {}, "f:ports": {".": {}, "k:{\"containerPort\":2379,\"protocol\":\"TCP\"}": {".": {}, "f:containerPort": {}, "f:name": {}, "f:protocol": {}}, "k:{\"containerPort\":2380,\"protocol\":\"TCP\"}": {".": {}, "f:containerPort": {}, "f:name": {}, "f:protocol": {}}}, "f:readinessProbe": {".": {}, "f:failureThreshold": {}, "f:initialDelaySeconds": {}, "f:periodSeconds": {}, "f:successThreshold": {}, "f:tcpSocket": {".": {}, "f:port": {}}, "f:timeoutSeconds": {}}, "f:resources": {".": {}, "f:limits": {".": {}, "f:cpu": {}, "f:memory": {}}, "f:requests": {".": {}, "f:cpu": {}, "f:memory": {}}}, "f:securityContext": {".": {}, "f:allowPrivilegeEscalation": {}, "f:capabilities": {".": {}, "f:drop": {}}, "f:privileged": {}, "f:readOnlyRootFilesystem": {}, "f:runAsNonRoot": {}, "f:runAsUser": {}}, "f:terminationMessagePath": {}, "f:terminationMessagePolicy": {}, "f:volumeMounts": {".": {}, "k:{\"mountPath\":\"/data/\"}": {".": {}, "f:mountPath": {}, "f:name": {}}, "k:{\"mountPath\":\"/var/etcd/certs/\"}": {".": {}, "f:mountPath": {}, "f:name": {}, "f:readOnly": {}}}}}, "f:dnsPolicy": {}, "f:restartPolicy": {}, "f:schedulerName": {}, "f:securityContext": {".": {}, "f:runAsUser": {}}, "f:serviceAccount": {}, "f:serviceAccountName": {}, "f:terminationGracePeriodSeconds": {}, "f:volumes": {".": {}, "k:{\"name\":\"data\"}": {".": {}, "f:emptyDir": {}, "f:name": {}}, "k:{\"name\":\"tls\"}": {".": {}, "f:name": {}, "f:secret": {".": {}, "f:defaultMode": {}, "f:secretName": {}}}}}}, "f:updateStrategy": {"f:rollingUpdate": {".": {}, "f:partition": {}}, "f:type": {}}, "f:volumeClaimTemplates": {}}}, "manager": "Go-http-client", "operation": "Update", "time": "2022-02-10T01:04:58Z"}, {"apiVersion": "apps/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:status": {"f:collisionCount": {}, "f:currentRevision": {}, "f:observedGeneration": {}, "f:replicas": {}, "f:updateRevision": {}}}, "manager": "kube-controller-manager", "operation": "Update", "time": "2022-02-10T19:01:10Z"}], "name": "wml-deployments-etcd", "namespace": "wml", "resourceVersion": "686948", "uid": "e7478a91-b13e-4b03-a81e-dc214cc9adaa"}, "spec": {"podManagementPolicy": "Parallel", "replicas": 0, "revisionHistoryLimit": 10, "selector": {"matchLabels": {"release": "wml", "serviceSelector": "wml-deployments-etcd"}}, "serviceName": "wml-deployments-etcd", "template": {"metadata": {"annotations": {"cloudpakId": "eb9998dcc5d24e3eb5b6fb488f750fe2", "cloudpakInstanceId": "66fe6453-9770-4a7d-89d7-167eedb13d38", "cloudpakName": "IBM Cloud Pak for Data", "hook.activate.cpd.ibm.com/command": "[\"date\"]", "hook.deactivate.cpd.ibm.com/command": "[\"date\"]", "productChargedContainers": "All", "productCloudpakRatio": "1:1", "productID": "eb9998dcc5d24e3eb5b6fb488f750fe2", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productName": "IBM Watson Machine Learning", "productVersion": "3.5.10"}, "creationTimestamp": null, "labels": {"app": "wml-deployments-etcd", "app.kubernetes.io/instance": "wml", "app.kubernetes.io/managed-by": "Tiller", "app.kubernetes.io/name": "wml", "chart": "ibm-wml-prod", "helm.sh/chart": "ibm-wml-prod-3.5.10", "heritage": "Tiller", "icpdsupport/addOnId": "wml", "icpdsupport/app": "api", "release": "wml", "serviceSelector": "wml-deployments-etcd"}, "name": "wml-deployments-etcd"}, "spec": {"affinity": {"nodeAffinity": {"requiredDuringSchedulingIgnoredDuringExecution": {"nodeSelectorTerms": [{"matchExpressions": [{"key": "beta.kubernetes.io/arch", "operator": "In", "values": ["amd64"]}]}]}}, "podAntiAffinity": {"preferredDuringSchedulingIgnoredDuringExecution": [{"podAffinityTerm": {"labelSelector": {"matchExpressions": [{"key": "release", "operator": "In", "values": ["wml"]}, {"key": "serviceSelector", "operator": "In", "values": ["wml-deployments-etcd"]}]}, "topologyKey": "kubernetes.io/hostname"}, "weight": 1}]}}, "containers": [{"command": ["/bin/sh", "-ec", "HOSTNAME=$(hostname -s)\nID=${HOSTNAME:(-1)}\necho \"==> The ID of the host is $ID\"\nDATA_DIR=/data/etcd/wml-deployments-etcd\n## Store member id for later member replacement\nstore_member_id() {\n  while ! etcdctl member list; do sleep 10; echo \"${ETCDCTL_ENDPOINTS}\"; done\n  etcdctl member list | grep `hostname -s` | awk '{ print $1}' | awk -F \":\" '{ print $1}' > ${DATA_DIR}/member_id\n  exit 0\n}\n## Create data dir if not exists\nif [ ! -d \"${DATA_DIR}\" ]; then\n  echo \"==> C{"level":"error","ts":1644519971.1768234,"logger":"logging_event_handler","msg":"","name":"wml-cr","namespace":"wml","gvk":"wml.cpd.ibm.com/v1beta1, Kind=WmlBase","event_type":"runner_on_failed","job":"957710640784578849","EventData.Task":"Scale etcd down for upgrade","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/4.0.6/roles/wml-base/tasks/upgrade.yml:376","error":"[playbook task failed]"}
```

**Comment by asmacdo** [comment]
Does scaling down work with kubectl?

**Comment by gravesm** [comment]
@rayankiy Could you try #391 and see if that fixes your problem? I'm not sure why it would only fail on ppc64le as you mentioned, but we did fix a bug in k8s_scale when scaling down to 0 replicas.

**Comment by rayankiy** [comment]
@asmacdo @gravesm :  Recently I observed the behaviour on x86 also .  So it is not ppc specific . 

As suggested above should I go with below playbook changes in my case to overcome the timeout error ?

```
## scale down etcd STS...
- name: Scale etcd down for upgrade
  kubernetes.core.k8s_scale:
    api_version: v1
    kind: StatefulSet
    name: wml-deployments-etcd
    namespace: "{{ namespace }}"
    replicas: 0
    wait_timeout: 3000
    wait: yes
 register: output

- assert:
      that:
        - output.result.status.replicas == 0
  
  ```

**Comment by gravesm** [comment]
I think you are probably experiencing the bug that #391 fixes. Increasing the wait timeout won't help. If you need a workaround until that fix is released you can try something like:
```yaml
- kubernetes.core.k8s_scale:
    api_version: apps/v1
    kind: StatefulSet
    name: wml-deployments-etcd
    namespace: "{{ namespace }}"
    replicas: 0
    wait: no

- kubernetes.core.k8s_info:
    kind: StatefulSet
    api_version: apps/v1
    namespace: "{{ namespace }}"
    name: wml-deployments-etcd
  register: result
  until: result.resources[0].status.replicas == 0
  retries: 12
  delay: 10
```

**Comment by rayankiy** [comment]
@gravesm: I tried the above code changes for statefulset and it works , but when I try the same for deployment it is failing with error.

```
- name: Scale wml-deployment-envoy down for upgrade
  kubernetes.core.k8s_scale:
    api_version: v1
    kind: Deployment
    name: wml-deployment-envoy
    namespace: "{{ namespace }}"
    replicas: 0
    wait: no


- name: Check status of Scale down for envoy
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Deployment
    name: wml-deployment-envoy
    namespace: "{{ namespace }}"
  register: eresult
  until: eresult.resources[0].status.replicas == 0
  retries: 12
  delay: 10
  ```
  
  
  ```
  1347 
   1348 --------------------------- Ansible Task StdOut -------------------------------
   1349 ^M
   1350 TASK [4.0.7/roles/wml-base : Check status of Scale down for envoy] *************^M
   1351 ^[[1;30mtask path: /opt/ansible/4.0.7/roles/wml-base/tasks/upgrade.yml:550^[[0m
   1352 
   1353 -------------------------------------------------------------------------------
   1354 {"level":"info","ts":1646913584.2153416,"logger":"logging_event_handler","msg":"[playbook task start]","name":"wml-cr","namespace":"zen","gvk":"wml.cpd.ibm.com/v1beta1, Kind=WmlBase","event_type":        "playbook_on_task_start","job":"4665024797829244445","EventData.Name":"4.0.7/roles/wml-base : Check status of Scale down for envoy"}
   1355 {"level":"info","ts":1646913585.6274383,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/zen/deployments/wml-deployment-envoy",        "Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"zen","Resource":"deployments","Subresource":"","Name":"wml-deployment-envoy","Parts":["deployments","wml-deployment        -envoy"]}}
   1356 
   1357 --------------------------- Ansible Task StdOut -------------------------------
   1358 
   1359  TASK [Check status of Scale down for envoy] ********************************
   1360 ^[[0;31mfatal: [localhost]: FAILED! => {"msg": "The conditional check 'eresult.resources[0].status.replicas == 0' failed. The error was: error while evaluating conditional (eresult.resources[0].st        atus.replicas == 0): 'dict object' has no attribute 'replicas'"}^[[0m
   1361 
   1362 -------------------------------------------------------------------------------
   1363 {"level":"error","ts":1646913585.9111063,"logger":"logging_event_handler","msg":"","name":"wml-cr","namespace":"zen","gvk":"wml.cpd.ibm.com/v1beta1, Kind=WmlBase","event_type":"runner_on_failed","        job":"4665024797829244445","EventData.Task":"Check status of Scale down for envoy","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/4.0.7/roles/wml-base/tasks/upgrade.yml:550","err        or":"[playbook task failed]"}
   1364 
   1365 --------------------------- Ansible Task StdOut -------------------------------
   1366 ^M
   1367 TASK [set wml status to failed] ************************************************^M
   1368 ^[[1;30mtask path: /opt/ansible/wmlbase.yml:46^[[0m
   1369 
   ```
   
   `'dict object' has no attribute 'replicas'`
