### ISSUE TITLE
`kubernetes.core.k8s` fails to apply .yaml with error "Failed to create object: __init__() got multiple values for argument 'self'"

### ISSUE THREAD

**Issue by haroonb** [ansible-collections/kubernetes.core#385]
##### SUMMARY

`kubernetes.core.k8s` hat can't successfully apply a yaml
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`kubernetes.core.k8s`
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/butt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/butt/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.2.3

# /usr/share/ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.2.3
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_JINJA2_NATIVE(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
     - name: k8s apply bugged crds
 #      ignore_errors: yes
       no_log: false
       kubernetes.core.k8s:
         state: present
         definition: "{{ lookup('url', 'https://raw.githubusercontent.com/keycloak/keycloak-operator/16.1.0/deploy/crds/keycloak.org_keycloakrealms_crd.yaml', split_lines=False) }}"
         namespace: keyloak
```

##### EXPECTED RESULTS

The module applies the .yaml without error

##### ACTUAL RESULTS

The module throws a error, but the .yaml seems to be applied, when I check the cluster.

The full traceback is:

https://gist.githubusercontent.com/haroonb/c15516fa15cf9ed4997ada8b90cdfecc/raw/d5ed3b7ab96944810236deda4c51dac745cb8f28/gistfile1.txt

```paste below

```

**Comment by Akasurde** [comment]
@haroonb Thanks for reporting this issue. I am able to reproduce this on machine.

**Comment by Akasurde** [comment]
You can reproduce this same behavior using this CRD - 

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stars.example.crd.com
spec:
  group: example.crd.com
  scope: Namespaced
  names:
    kind: Star
    listKind: StarList
    plural: stars
    singular: star
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["type","location","self"]
          properties:
            type:
              type: "string"
              minimum: 1
            location:
              type: "string"
              minimum: 1
            self:
              type: "string"
              minimum: 1
  versions:
    - name: v1alpha1
      served: true
      storage: true
```

There is `self` in the `spec.properties` which is causing this error.
