### ISSUE TITLE
helm diff output

### ISSUE THREAD

**Issue by krisek** [ansible-collections/kubernetes.core#395]
##### SUMMARY
The Kubernetes returns with `--check --diff` CLI parameters, the actual diff that would be applied on the cluster. It would be great if the helm module would do the same.

##### ISSUE TYPE
- Feature

##### COMPONENT NAME
helm.py

##### ADDITIONAL INFORMATION
It would be a great enhancement for CI/CD pipelines.

```bash
ansible-playbook -i inventory.yaml  -e variable_host="play" --check --diff basic-service-deploy.yaml
```

```yaml
  - name: install helm package
    kubernetes.core.helm:
      chart_ref: "{{ chart_ref }}"
      chart_version: "{{ version }}"
      create_namespace: y
      context: "{{ inventory_hostname }}"
      release_name: hello
      release_namespace: hello-world
      release_state: present
```

**Comment by abikouo** [comment]
Hi @krisek 

Thanks for taking the time to report this feature. ``helm`` module does not support the ``diff`` mode for now, but this is a feature we may need to address later.

**Comment by krisek** [comment]
Yes, without helm diff it is definitely a mission impossible. The background is that I'm working on a dry-run CI/CD pipeline. I have a little issue with adding repos with `--check` enabled as well, but I need to investigate more, maybe I can solve without requiring a new features :)

**Comment by pauvos** [comment]
@krisek , you can achieve something like this by comparing the current and future release with helm_template and fact_diff.

Pseudo code:

```yaml
- name: "{{ release_name }} : fetch existing release info"
  kubernetes.core.helm_info:
    release_name: "{{ release_name }}"
    release_namespace: "{{ release_namespace }}"
  check_mode: false
  changed_when: false
  when: ansible_diff_mode
  register: existing_info

- name: "{{ release_name }} : render existing release"
  kubernetes.core.helm_template:
    chart_version: "{{ existing_info['status']['chart'][(chart_name|length + 1):] }}" # cut version from "somechart-1.2.3"
    release_values: "{{ existing_info['status']['values'] }}" # use values from last release
    validate: true # opened pull request #587 for this one
    ...
  ...
  register: existing_tpl

- name: "{{ release_name }} : render new release"
  kubernetes.core.helm_template:
    chart_version: "{{ new_version }}"
    release_values "{{ new_release_values }}"
    ...
  ...
  register: new_tpl

- name: "{{ release_name }} : diff"
  ansible.utils.fact_diff: 
    before: "{{ existing_tpl.stdout|default('')|trim }}"
    after: "{{ new_tpl.stdout|trim }}"
  ...
  changed_when: existing_tpl.stdout|default('')|trim != new_tpl.stdout|trim
```

`fact_diff` produces less verbose (only a few lines of changes) and more readable (green/red diff lines) output than running kubernetes.core.helm in diff_mode. If no current release exists, all new manifests will be displayed.
