### ISSUE TITLE
`k8s_cp` inconsistent behavior with parameter `local_path`

### ISSUE THREAD

**Issue by haroonb** [ansible-collections/kubernetes.core#421]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/butt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/butt/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection           Version
-------------------- -------
amazon.aws           3.1.1
ansible.netcommon    2.0.1
ansible.posix        1.3.0
ansible.utils        2.0.2
cloud.common         2.1.0
community.aws        3.1.0
community.crypto     1.7.1
community.docker     2.2.1
community.general    4.6.1
community.grafana    1.3.3
community.kubernetes 2.0.1
community.postgresql 2.1.2
community.vmware     1.0.0
google.cloud         1.0.2
kubernetes.core      2.3.0

```

##### CONFIGURATION

```paste below

CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_JINJA2_NATIVE(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

You can repoduce this with the following steps:
* copy  `from_pod` to `local_path`
* copy  `to_pod` from same `local_path` 

```yaml
---
- hosts: devops-m1
  gather_facts: no
  tasks:

    - name: create busy box
      kubernetes.core.k8s:
        wait: yes
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: concept
            namespace: default
          spec:
            containers:
            - name: busybox
              image: busybox
              args:
              - sleep
              - infinity

    - name: create a file
      kubernetes.core.k8s_exec:
        pod: concept
        namespace: default
        command: touch /tmp/test.file

    - name: copy from_pod to local_path
      kubernetes.core.k8s_cp:
        state: from_pod
        pod: concept
        namespace: default
        remote_path: /tmp/test.file
        local_path: /tmp/test.file

    - name: check if file exists
      stat:
        path: /tmp/test.file
        get_checksum: yes
      register: result

    - name: copy to_pod from local_path
      kubernetes.core.k8s_cp:
        state: to_pod
        pod: concept
        namespace: default
        remote_path: /tmp/file.test
        local_path: /tmp/test.file
      when: result.stat.exists
```

##### EXPECTED RESULTS

I expected the module to use the same `local_path` on the remote host to read the file from, which it used to write the files to.

The documentation of the module.
```
# kubectl cp /tmp/foo some-namespace/some-pod:/tmp/bar -c some-container
- name: Copy /tmp/foo local file to /tmp/bar in a remote pod in a specific container
  kubernetes.core.k8s_cp:
    namespace: some-namespace
    pod: some-pod
    container: some-container
    remote_path: /tmp/bar
    local_path: /tmp/foo
    no_preserve: True
    state: to_pod
```

##### ACTUAL RESULTS

The modules tries to copy from the ansible controller

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/usr/share/ansible/collections/ansible_collections/kubernetes/core/plugins/action/k8s_cp.py", line 271, in get_file_realpath
    return self._find_needle("files", local_path)
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/__init__.py", line 1364, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python3/dist-packages/ansible/parsing/dataloader.py", line 341, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])
ansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/test.file' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [devops-m1]: FAILED! => {
    "changed": false,
    "msg": "/tmp/test.file does not exist in local filesystem"
}

```
