### ISSUE TITLE
diff when running `kubernetes.core.k8s` in check mode

### ISSUE THREAD

**Issue by rekup** [ansible-collections/kubernetes.core#426]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/share/virtualenvs/foo-r-OLon9H/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/share/virtualenvs/foo-r-OLon9H/bin/ansible
  python version = 3.10.3 (main, Mar 18 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.1.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below
kubernetes.core               2.2.3  
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

- create kubernetes cluster: `minikube start --kubernetes-version=v1.22.8`
- run the following playbook (`ansible-playbook play.yml --diff`)

```yaml
- name: example
  hosts: localhost

  tasks:
  - name: "test"
    kubernetes.core.k8s:
      kubeconfig: /home/user/.kube/minikube
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          namespace: default
        spec:
          selector:
            matchLabels:
              app: nginx
          replicas: 2
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                - containerPort: 80

```
- run the same playbook again in check mode (`ansible-playbook play.yml --diff --check`)

##### EXPECTED RESULTS

I expected that the tasks does not change and has no diff

##### ACTUAL RESULTS

```paste below
TASK [test] ******************************************************************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -4,17 +4,12 @@
             "spec": {
                 "containers": [
                     {
-                        "imagePullPolicy": "IfNotPresent",
                         "name": "nginx",
                         "ports": [
                             {
-                                "containerPort": 80,
-                                "protocol": "TCP"
+                                "containerPort": 80
                             }
-                        ],
-                        "resources": {},
-                        "terminationMessagePath": "/dev/termination-log",
-                        "terminationMessagePolicy": "File"
+                        ]
                     }
                 ]
             }

changed: [localhost]

```
(`-vvv` output: https://gist.github.com/rekup/4633ced86427c5a689e15e54ebde3e6e)
If I run the playbook without `--check` there is no change but as soon as I run it in check mode the diff appears.
Similar issues seem to occur also with other ressources (other than Deployments)
