### ISSUE TITLE
kubernetes.core.k8s: Service None: Failed to delete object

### ISSUE THREAD

**Issue by bastienbosser** [ansible-collections/kubernetes.core#428]
##### SUMMARY

It is impossible to remove a service via a label_selectors with the kubernetes.core.k8s module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s

##### ANSIBLE VERSION

```paste below
2.9.25
```

##### COLLECTION VERSION

```paste below
2.3.0
```

##### CONFIGURATION

```paste below
Standard
```

##### OS / ENVIRONMENT

RHEL 8.5 / Kubernetes 1.21.4

##### STEPS TO REPRODUCE

Deploy this service on your cluster
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: regionadmin
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: registry
  type: LoadBalancer
```

try to delete it with this task
```yaml
- name: Delete registry service resources
  kubernetes.core.k8s:
    api_version: v1
    namespace: regionadmin
    kind: Service
    state: absent
    label_selectors:
      - app=registry
```

##### EXPECTED RESULTS

changed: [tank1]

##### ACTUAL RESULTS

```paste below
fatal: [tank1]: FAILED! => changed=false 
  error: 405
  msg: 'Service None: Failed to delete object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server does not allow this method on the requested resource","reason":"MethodNotAllowed","details":{},"code":405}\n'''
  reason: Method Not Allowed
  status: 405
```
