### ISSUE TITLE
k8s is not respecting the "omit" option

### ISSUE THREAD

**Issue by rabin-io** [ansible-collections/kubernetes.core#431]
##### SUMMARY

When deploying a CR from a template which contain an `omit` option, the place holder is not removed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.1]
  config file = ./ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/.local/lib/python3.10/site-packages/ansible
  ansible collection location = $HOME/.ansible/collections:/usr/share/ansible/collections
  executable location = $HOME/.local/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION

```paste below
kubernetes.core 2.2.3  

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
# Prerequisites
#
#     A Linux bridge must be configured and attached on every node.

- name: Deploy Network Attachment Definition
  hosts: localhost
  vars:
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    cluster_domain: "{{ lookup('env', 'CLUSTER_DOMAIN') }}"
    default_kubeconfig_file: "~/{{ cluster_domain }}/{{ cluster_name }}/auth/kubeconfig"
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') | default(default_kubeconfig_file, true) }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  tasks:

    - block:
        - name: Deploy Network Attachment Definition
          kubernetes.core.k8s:
            state: present
            template: "templates/cr/NetworkAttachmentDefinition.yaml.j2"
          vars:
            bridge_interface: brcnv
            network_attachment_definition_name: brcnv
            # _namespace: default
          register: deploymeny
          until: deploymeny.failed == false
          retries: 3
          delay: 10

      rescue:
        - name: Dump Debug Information
          ansible.builtin.debug:
            var: "{{ item }}"
          loop:
            - default_kubeconfig_file
            - kubeconfig
            - cluster_name
            - cluster_domain
```

and the template
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ network_attachment_definition_name | default('bridge_interface', true) }}
  namespace: {{ _namespace | default('default', true) }}
  annotations:
    description: "{{ description | default(omit) }}"
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/{{ bridge_interface }}
spec:
  config: >-
    {
      "cniVersion": "0.3.1",
      "name": "{{ network_attachment_definition_name | default('bridge_interface', true) }}",
      "plugins": [
        {
          "type": "cnv-bridge",
          "bridge": "{{ bridge_interface }}",
          "vlan": 1
        },
        {
          "type": "cnv-tuning"
        }
      ]
    }
```

output of ansible run
```diff
TASK [Deploy Network Attachment Definition] ***************************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 metadata:
   annotations:
-    description: __omit_place_holder__565ee1d852fcc8d27a325b9aca711683b17ca133
-  resourceVersion: '571831'
+    description: __omit_place_holder__f5a9c0ea6c4434007dd6bb295da6b85e379f5376
+  resourceVersion: '574700'

changed: [localhost] => changed=true 
  attempts: 1
  method: patch
  result:
    apiVersion: k8s.cni.cncf.io/v1
    kind: NetworkAttachmentDefinition
    metadata:

```

##### EXPECTED RESULTS
To drop the key which defined as omit

##### ACTUAL RESULTS
Each run will update the resource with a new value of a random generated omit string.
