### ISSUE TITLE
wait_condition on kubernetes.core.k8s_info causing fail_json error

### ISSUE THREAD

**Issue by sachintanna-lab** [ansible-collections/kubernetes.core#433]
We are utilizing the kubernetes.core.k8s_info module to confirm the successful installation of the ClusterServiceVersion (Operator) we are installing. However, we are receiving the following error:

```
AttributeError: 'K8sAnsibleMixin' object has no attribute 'fail_json'
```
We are **not** receiving this error when using kubernetes.core.k8s.

Our Ansible version is 2.10.8.
Our Python version is 3.9.4.
Our kubernetes.core version is 2.1.1 

An example of our implementation is:

```
- name: Check Status of Operator
  kubernetes.core.k8s_info:
    kind: ClusterServiceVersion 
    api_version: operators.coreos.com/v1alpha1
    name: "operator_name" 
    namespace: "test"
    wait: 'yes'
    wait_condition:
      reason: InstallSucceeded
      type: Succeeded
      status: True
```
Using MacOS Monterey.
