### ISSUE TITLE
kubeconfig parameter does not work with multiple config files

### ISSUE THREAD

**Issue by faisalchishtii** [ansible-collections/kubernetes.core#435]
##### SUMMARY
K8s module does not work when multiple configs are set up in KUBECONFIG env variable or passed as a parameter to k8s module.

```
- name: register cluster
  kubernetes.core.k8s:
    state: present
    kubeconfig: '~/.kube/config:~/.kube/config_remote'
    context: cluster-local
    namespace: argocd
    src: /tmp/secret.yaml
  delegate_to: localhost
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s

##### ANSIBLE VERSION
```
ansible 2.10.15
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Mar 19 2021, 05:13:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

##### COLLECTION VERSION

```
# /usr/local/lib/python3.6/site-packages/ansible_collections
Collection           Version
-------------------- -------
community.kubernetes 1.2.1  
```

```
##### OS / ENVIRONMENT
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

##### STEPS TO REPRODUCE
```
- name: register cluster
  kubernetes.core.k8s:
    state: present
    kubeconfig: '~/.kube/config:~/.kube/config_remote'
    context: cluster-local
    namespace: argocd
    src: /tmp/secret.yaml
  delegate_to: localhost
```

##### EXPECTED RESULTS
Should create a kubernetes object.

##### ACTUAL RESULTS
Fails with below error.

```
fatal: [10.87.3.140 -> localhost]: FAILED! => {"changed": false, "msg": "Failed to load kubeconfig due to Invalid kube-config file. Expected object with name cluster-local in /root/.kube/config/contexts list"}
```
