### ISSUE TITLE
k8s module issue when creating a LimitRange for openshift.io/Image & openshift.io/ImageStream in Openshift 4.10

### ISSUE THREAD

**Issue by vladuhul** [ansible-collections/kubernetes.core#449]
SUMMARY

 Message:
 'openshift.io/Image' is not one of ['Container', 'PersistentVolumeClaim', 'Pod']"
 Openshift documentation: https://docs.openshift.com/container-platform/4.7/nodes/clusters/nodes-cluster-limit-ranges.html
Normally it creates the LimitRange without a problem but for 4.10 this is not happening. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s core module creating a LimitRange for openshift.io/Image & openshift.io/ImageStream;
##### ANSIBLE VERSION 2.10.17

```
'openshift.io/Image' is not one of ['Container', 'PersistentVolumeClaim', 'Pod']
```

**Comment by vladuhul** [comment]
@gravesm Thank you for replying. 
Yaml file in question:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: 
  namespace: 
  selfLink: "..."
spec:
  limits:
  - type: Pod
    max:
      cpu: ".."
      memory: ...Mi
    min:
      cpu: ...m
      memory: ...Mi
  - type: Container
    max:
      cpu: "..."
      memory: ...Mi
    min:
      cpu: ...m
      memory: ...Mi
    default:
      cpu: ...
      memory: ...Mi
    defaultRequest:
      cpu: ...m
      memory: ...Mi
  - type: openshift.io/Image
    max:
      storage: ...Gi
  - type: openshift.io/ImageStream
    max:
      openshift.io/image-tags: "..."
      openshift.io/images: "..."
```
Regarding the kubernetes.core, can you please offer me more details? Are you reffering to the kubernetes version shown in the requirements sections here?
https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html#ansible-collections-kubernetes-core-k8s-info-module

![image](https://user-images.githubusercontent.com/60156963/167084550-e03cd6ce-9d9e-4132-9aee-dfc4bc89d17f.png)

**Comment by vladuhul** [comment]
@gravesm Thank you for taking the time to respond.
Yaml in question:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: ...
  namespace: ...
  selfLink: "..."
spec:
  limits:
  - type: Pod
    max:
      cpu: "2"
      memory: 3000Mi
    min:
      cpu: 5m
      memory: 20Mi
  - type: Container
    max:
      cpu: "2"
      memory: 3000Mi
    min:
      cpu: 5m
      memory: 20Mi
    default:
      cpu: 1
      memory: 500Mi
    defaultRequest:
      cpu: 10m
      memory: 60Mi
  - type: openshift.io/Image
    max:
      storage: 3Gi
  - type: openshift.io/ImageStream
    max:
      openshift.io/image-tags: "30"
      openshift.io/images: "50"
```

kubernetes.core version = 23.3.0

**Comment by gravesm** [comment]
I am not able to reproduce this using the following playbook:

```
- hosts: localhost
  tasks:
    - kubernetes.core.k8s:
        kind: Namespace
        name: testing

    - kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: LimitRange
          metadata:
            namespace: testing
            name: test-range
          spec:
            limits:
              - type: openshift.io/Image
                max:
                  storage: 1Gi
```
openshift 4.10.9
kubernetes.core 2.3.1
kubernetes 23.3.0
ansible 2.12.5

**Comment by vladuhul** [comment]
@gravesm Some remarks are in order to understand the big picture. 

I have an ansible role which is triggered in a playbook. The ansible role creates the object by referring to the template I posted above. I also tried to use j2 template -  same error.

```
- name: Create 
  k8s:
    name: ...
    namespace: "{{ ... }}"
    api_version: v1
    host: "{{ ... }}"
    api_key: "{{ ... }}"
    apply: true
    username: "{{ ... }}" 
    validate_certs: no
    state: present
    definition: "{{ lookup('file', 'resource.yaml') }}"
  tags: require
```

kubernetes 23.3.0
ansible.core 2.11.11

How do i find out the kubernetes.core version?
