### ISSUE TITLE
The kubernetes Python library missing with V1Eviction API

### ISSUE THREAD

**Issue by Aohzan** [ansible-collections/kubernetes.core#450]
##### SUMMARY

Hello,

I try to use `kubernetes.core.k8s_drain`:
```yaml
    - name: Cordon k8s node
      kubernetes.core.k8s_drain:
        state: cordon
        name: "{{ inventory_hostname }}"
```
but I got this error:
`"error": "No module named 'kubernetes'", "msg": "The kubernetes Python library missing with V1Eviction API"}`

I tried with multiple version of kubernetes pip package (last and 12.0.1):
```
pip3 list | grep kubernetes
kubernetes                              23.3.0
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.4]
  config file = /data/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.4 (main, Apr 20 2022, 05:30:59) [GCC 10.2.1 20210110]
  jinja version = 3.1.1
  libyaml = True
```

##### COLLECTION VERSION
```paste below
# /usr/local/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.0  

# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.1  
```

##### CONFIGURATION
```paste below
DEFAULT_BECOME(/data/ansible.cfg) = True
DEFAULT_REMOTE_USER(/data/ansible.cfg) = admoxa
DEFAULT_ROLES_PATH(/data/ansible.cfg) = ['/data/roles']
DEPRECATION_WARNINGS(/data/ansible.cfg) = False
DIFF_ALWAYS(/data/ansible.cfg) = True
HOST_KEY_CHECKING(/data/ansible.cfg) = False
INTERPRETER_PYTHON(/data/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/data/ansible.cfg) = False
VARIABLE_PRECEDENCE(/data/ansible.cfg) = ['all_plugins_play', 'groups_plugins_play', 'all_plugins_inventory', 'groups_plugins_inventory', 'all_inventory', 'groups_inventory']
```

##### OS / ENVIRONMENT
Docker image `FROM python:slim` with ansible installed

##### STEPS TO REPRODUCE
```yaml
    - name: Cordon k8s node
      kubernetes.core.k8s_drain:
        state: cordon
        name: "{{ inventory_hostname }}"
```

##### EXPECTED RESULTS
run the tasks

##### ACTUAL RESULTS
```paste below
"error": "No module named 'kubernetes'", "msg": "The kubernetes Python library missing with V1Eviction API"}
```

Thank you
