### ISSUE TITLE
Support kubectl apply from URL

### ISSUE THREAD

**Issue by interone-ms** [ansible-collections/kubernetes.core#451]
##### SUMMARY

It should be possible to specify a manifest URL in the `kubernetes.core.k8s` module that gets passed on to `kubectl apply -f <URL>` under the hood.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
kubernetes.core.k8s

##### ADDITIONAL INFORMATION

Due to firewall issues or nasty HTTPS-breaking sniffing software (e.g. Netskope) on an administrator's laptop, it may be desirable to specify the manifest URL in the module configuration, so that the target machine downloads the manifest and applies it.

`get_url` technically works, but needs an extra step in the playbook and a place to store the temporary file.

`resource_definition: "{{ lookup('url', 'https://internal.corp/foo/bar.yml') }}"` has the problem that the case of "the only network allowed to access the manifest is a specific VPC" is not supported (as lookup will only run on the administrator's laptop).

```yaml
    kubernetes.core.k8s:
      state: present
      manifest_url: "https://docs.projectcalico.org/archive/v3.21/manifests/calicoctl.yaml"
```
