### ISSUE TITLE
Helm module not inserting finalizer annotations to the resources 

### ISSUE THREAD

**Issue by anupchandak** [ansible-collections/kubernetes.core#467]
##### SUMMARY
If I use `kubernetes.core.helm` to create my resource in my ansible operator, I observe that it does not add `operator-sdk/primary-resource` or `operator-sdk/primary-resource-type` annotation to the created resources. I also don't see `ownerReferences` being injected when the namespace of CR and generated resources are identical.  
I have `finalizer` defined in my `watches.yaml` that as well doesn't get invoked. 

If I use `kubernetes.core.k8s` then I do not see the above problems.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.helm

##### ANSIBLE VERSION

```
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/Users/anupchandak/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/anupchandak/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:48:04) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.1
  libyaml = True

```

##### COLLECTION VERSION

```
Collection      Version
--------------- -------
kubernetes.core 2.3.1

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
- name: Create Namespace and deploy latest version of Test chart
  helm:
    release_name: test
    release_namespace: test-namespace
    create_namespace: yes
    release_state: present
    atomic: yes
    force: yes
    replace: no
    timeout: 5m
    wait: yes
    chart_ref: ../roles/testrole/files/helmcharts/test
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  register: deployed

```

##### EXPECTED RESULTS
1. Expected to have `operator-sdk/primary-resource` and `operator-sdk/primary-resource-type` annotations on each of the resources created by helm command.
2. If namespace of CR and resource is same then expected to have `ownerReferences` annotation on each of the resources created by helm command.
3. Usage of the helm module should not hinder the process of running finalizer as defined on CR.

##### ACTUAL RESULTS
Config map generated by the CR is as follows

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-cm-0231f94d-b61c-4113-94ec-4bcb53f21950
  namespace: test-namespace
  uid: 0929d26e-15b2-45b1-950b-b8c21047f439
  resourceVersion: '32698456'
  creationTimestamp: '2022-05-23T09:00:32Z'
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: test-namespace 
data:
  <some project specific data key: values>
```
