### ISSUE TITLE
Apply as root: "Failed to load kubeconfig due to Invalid kube-config file. No configuration found."

### ISSUE THREAD

**Issue by vonera** [ansible-collections/kubernetes.core#470]
##### SUMMARY

`apply` on a resource owned by root (using `become: true`) results in `Failed to load kubeconfig due to Invalid kube-config file. No configuration found.`
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = /Users/MYUSER/projects/infrastructure/soft-infra/server-build/ansible.cfg
  configured module search path = ['/Users/MYUSER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.6.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/MYUSER/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.1.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# ansible-galaxy collection list kubernetes.core

# /opt/homebrew/Cellar/ansible/5.6.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.0
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/PROJECT_PATH/ansible.cfg) = ['/PROJECT_PATH/environments/dev']
```

##### OS / ENVIRONMENT

target OS  Ubuntu 20.04 

##### STEPS TO REPRODUCE

- Create a resource file (in my case previously backed up secret holding a cert) that is owned by root
- Apply the file using `become: true`

hosts.yaml
```yaml
---
single_node_k3s_cluster:
  hosts:
    master: 
      ansible_user: ansiuser
      ansible_host: MYDOMAIN.com
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
```
> The k3s cluster is created using `xanmanning.k3s` role

example playbook
```yaml
---
- hosts: single_node_k3s_cluster

  tasks:
    - name: Restore cert from backup
      kubernetes.core.k8s:
        src: "{{ cert_backup_path }}"
        state: present
        apply: true
      become: true
```

##### EXPECTED RESULTS

The resource file gets applied 

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_kubernetes.core.k8s_payload__3j9urkd/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 266, in get_api_client
    _load_config()
  File "/tmp/ansible_kubernetes.core.k8s_payload__3j9urkd/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 233, in _load_config
    kubernetes.config.load_kube_config(config_file=None, **optional_arg)
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/config/kube_config.py", line 808, in load_kube_config
    loader = _get_kube_config_loader(
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/config/kube_config.py", line 767, in _get_kube_config_loader
    raise ConfigException(
fatal: [master]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "v1",
            "append_hash": false,
            "apply": true,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": null,
            "continue_on_error": false,
            "delete_options": null,
            "force": false,
            "generate_name": null,
            "host": null,
            "impersonate_groups": null,
            "impersonate_user": null,
            "kind": null,
            "kubeconfig": null,
            "label_selectors": null,
            "merge_type": null,
            "name": null,
            "namespace": null,
            "no_proxy": null,
            "password": null,
            "persist_config": null,
            "proxy": null,
            "proxy_headers": null,
            "resource_definition": null,
            "server_side_apply": null,
            "src": "/THE_RIGHT_PATH/cert.yaml",
            "state": "present",
            "template": null,
            "username": null,
            "validate": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "msg": "Failed to load kubeconfig due to Invalid kube-config file. No configuration found."
}
```
- Using kubectl on the target machine `sudo kubectl apply -f cert.yaml` works fine
- If the file is owned by ansible_user, everything works fine
- My workaround is to get the file contents first and then to apply it, but is it the right way?
```yaml
  tasks:
    - name: Slurp cert from remote
      slurp:
        src: "{{ cert_backup_path }}"
      register: slurped_cert
      become: true

    - name: Restore cert from backup
      kubernetes.core.k8s:
        resource_definition: "{{ slurped_cert['content'] | b64decode }}"
        state: present
        apply: true
```

**Comment by gravesm** [comment]
@vonera The problem is that the underlying kubernetes python library is looking for the default kubeconfig file at `~/.kube/config`. When you use `become` that expands to `/root/.kube/config`. I'm not sure why `sudo kubectl` is working for you. It fails for me because of the kube config location. Your options are to either not use `become` on the k8s task like you posted in your workaround, or to explicitly provide a fully expanded path to a kubeconfig. You could try setting the kubeconfig path before this task with something like:
```yaml
tasks:
  - set_fact:
      kubeconfig: "{{ '~/.kube/config' | expanduser }}"

  - name: Restore cert from backup
      kubernetes.core.k8s:
        src: "{{ cert_backup_path }}"
        state: present
        apply: true
        kubeconfig: "{{ kubeconfig }}"
      become: true
```
