### ISSUE TITLE
kubernetes.core.helm_repository to be stateful

### ISSUE THREAD

**Issue by edgan** [ansible-collections/kubernetes.core#480]
##### SUMMARY
kubernetes.core.helm_repository, or a new function, should be stateful, as in `state: present`. Currently it installs a repository, but can't verify if it is already installed. If it is already installed it will just throw an error saying it is already installed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
kubernetes.core.helm_repository

##### ADDITIONAL INFORMATION
Workaround code:
```
- name: "helm_repo_check_{{ nexus.helm.repo.name }}"
  changed_when: false
  shell:
    cmd: "helm repo list | grep {{ nexus.helm.repo.name }}"
```

```
- name: nexus_helm_repo
  kubernetes.core.helm_repository:
    name: "{{ nexus.helm.repo.name }}"
    repo_url: "nexus.helm.repo.url }}"
  when: helm_repo_nexus.rc == 1
`

**Comment by gravesm** [comment]
@edgan The module already supports this:

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - kubernetes.core.helm_repository:
        repo_url: https://charts.bitnami.com/bitnami
        name: bitnami

    - kubernetes.core.helm_repository:
        repo_url: https://charts.bitnami.com/bitnami
        name: bitnami
```
```
PLAY [localhost] ****************************************************************************************************************************

TASK [kubernetes.core.helm_repository] ******************************************************************************************************
changed: [localhost]

TASK [kubernetes.core.helm_repository] ******************************************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Could you provide more information about what version of the collection and what version of ansible you are using? Also, could you provide the output from running the playbook using `-vvv`?

**Comment by em-** [comment]
I got here because I got the `Repository already have a repository named $foo` error, but it happened to me because I already had it listed with a different URL.

I can reproduce the exact error with:

```
 hosts: localhost
  gather_facts: no
  tasks:
    - kubernetes.core.helm_repository:
        repo_url: https://charts.bitnami.com/bitnami
        name: bitnami

    - kubernetes.core.helm_repository:
        repo_url: https://charts.gitlab.io
        name: bitnami
```

```
$ ansible-playbook ansible-helm-repo.yaml 
TASK [kubernetes.core.helm_repository] 
changed: [localhost]

TASK [kubernetes.core.helm_repository] 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Repository already have a repository named bitnami"}
```

Maybe this was issue for the original reporter as well?

Note that `helm` gives a different message, but still does not point out that the issue is the different URL. I know it should be obvious, but my brain sometimes goes on vacation. :)

```
$helm repo add bitnami https://charts.gitlab.io/
Error: repository name (bitnami) already exists, please specify a different name
```

**Comment by yurnov** [comment]
Just checked:
```
root@daa35e998ee4:/# /usr/local/bin/helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" already exists with the same configuration, skipping
root@daa35e998ee4:/# /usr/local/bin/helm repo add bitnami https://charts.bitnami.com/bitnami/
Error: repository name (bitnami) already exists, please specify a different name
root@daa35e998ee4:/#
```

Fixed as #1121, after fix:
```
PLAY [localhost] *******************************************************************************************************

TASK [kubernetes.core.helm_repository] *********************************************************************************
changed: [localhost]

TASK [kubernetes.core.helm_repository] *********************************************************************************
ok: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by RobinR1** [comment]
If I understand this correctly, a trailing slash in the URL is now always stripped? As this may well be the cause why my play now fails with the  error: "Repository already have a repository named cilium".
The repository is already registered, with a trailing slash, like I configured in my play. So the URL I use in Ansible is identical to the one in the helm repo, but now it fails with the above error, I assume because the trailing slash is removed from the Ansible value-URL before comparing with the url of the existing repo, that does contain a trailing slash?

**Comment by yurnov** [comment]
> If I understand this correctly, a trailing slash in the URL is now always stripped? As this may well be the cause why my play now fails with the error: "Repository already have a repository named cilium". The repository is already registered, with a trailing slash, like I configured in my play. So the URL I use in Ansible is identical to the one in the helm repo, but now it fails with the above error, I assume because the trailing slash is removed from the Ansible value-URL before comparing with the url of the existing repo, that does contain a trailing slash?

Hi @RobinR1,

Most probably, `force: true` will help in your case; however, at the cost of idempotency

I have reproduced the issue with the following:
```yaml
- name: helm_repository fails on a repo registered with a trailing slash
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    repo_name: cilium
    repo_url: https://helm.cilium.io/          # <- trailing slash
    helm_home: /tmp/repro-1121

  environment:
    HELM_REPOSITORY_CONFIG: "{{ helm_home }}/repositories.yaml"
    HELM_REPOSITORY_CACHE: "{{ helm_home }}/cache"

  tasks:
    - name: Start from an empty repository config
      ansible.builtin.file:
        path: "{{ helm_home }}"
        state: absent

    - name: Pre-existing repo, added with the trailing slash
      ansible.builtin.command: helm repo add {{ repo_name }} {{ repo_url }}
      changed_when: true

    - name: Show what helm has on disk
      ansible.builtin.command: helm repo list --output=yaml
      register: repo_list
      changed_when: false

    - name: Same name, same URL - expected to be an idempotent no-op
      kubernetes.core.helm_repository:
        name: "{{ repo_name }}"
        repo_url: "{{ repo_url }}"
      register: result
      ignore_errors: true

    - name: Result
      ansible.builtin.assert:
        that:
          - result is failed
          - "'already have a repository named' in (result.msg | default(''))"
        success_msg: >-
          Reproduced. helm has {{ (repo_list.stdout | from_yaml)[0].url }},
          the module compares it against the stripped {{ repo_url | regex_replace('/$', '') }}
          and fails with: {{ result.msg | default('') }}

    - name: Workaround - force bypasses the comparison, at the cost of idempotency
      kubernetes.core.helm_repository:
        name: "{{ repo_name }}"
        repo_url: "{{ repo_url }}"
        force: true
```

To have it tracked, going to close the separate linked Issue and fix it
