### ISSUE TITLE
simplify the helm repo update scenario

### ISSUE THREAD

**Issue by rgl** [ansible-collections/kubernetes.core#483]
##### SUMMARY

Currently its quite awkward to update the helm repo cache. The [documented way](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html#examples) seems rather complex:

```yaml
- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true
```

Since there is already a `helm_repository` module, why not make it also update the cache like the `apt` module?

For example, by adding `update_cache` and `cache_valid_time`:

```yaml
- name: Add jetstack repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    update_cache: yes
    cache_valid_time: 10800 # 3h
```

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

helm_repository
