### ISSUE TITLE
k8s_cp doc issue

### ISSUE THREAD

**Issue by meihui** [ansible-collections/kubernetes.core#485]
##### SUMMARY

Last example for the k8s_cp is with typo

```
# copy content into a file in the remote pod
- name: Copy /tmp/foo from a remote pod to /tmp/bar locally
  kubernetes.core.k8s_cp:
    state: to_pod
    namespace: some-namespace
    pod: some-pod
    remote_path: /tmp/foo.txt
    content: "This content will be copied into remote file"
```
The state shall be from_pod and content field shall be removed.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```
