### ISSUE TITLE
`kubernetes.core.k8s` silently ignores CRD validation error.

### ISSUE THREAD

**Issue by reitermarkus** [ansible-collections/kubernetes.core#490]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`kubernetes.core.k8s`

##### ANSIBLE VERSION

```paste below
2.13.1
```

##### COLLECTION VERSION

```paste below
2.3.2
```

##### CONFIGURATION

```paste below
VARIABLE_PLUGINS_ENABLED(ansible.cfg) = ['host_group_vars', 'community.sops.sops']
```

##### OS / ENVIRONMENT

macOS 12.4

##### STEPS TO REPRODUCE

Given the file `traefik/tlsstore.yml` with content

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-system
spec:
  invalid: key
  defaultCertificate:
    secretName: example.com
```

and given Traefik and its CRDs are deployed, run the following task

```yaml
- name: Deploy Traefik TLS store
  kubernetes.core.k8s:
    src: traefik/tlsstore.yml
```

##### EXPECTED RESULTS

The task should fail since the Traefik CRD does not contain the `invalid` key.

##### ACTUAL RESULTS

The task succeeds without any errors, but does not actually deploy the CR. It returns the current version of the resource.

When deploying the same with `kubectl apply -f traefik/tlsstore.yml`, an error is correctly shown:

```
error: error validating "traefik/tlsstore.yml": error validating data: ValidationError(TLSStore.spec): unknown field "invalid" in us.containo.traefik.v1alpha1.TLSStore.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

##### ADDITIONAL NOTES

I also tried specifying `apply: true`, which does not change anything, as well as using `validate: { fail_on_error: true, strict: true }`, which merely outputs this warning:

```
[WARNING]: TLSStore default: Could not find schema for object kind TLSStore with API version traefik.containo.us/v1alpha1 in Kubernetes version 1.24 (possibly Custom Resource?)
```
