### ISSUE TITLE
Make name optional indicating all objects

### ISSUE THREAD

**Issue by anon-software** [ansible-collections/kubernetes.core#504]
##### SUMMARY

Currently kubernetes.core.k8s requires either "name" or "label_selector" to be specified. I want to be able to run an operation on all objects.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

kubernetes.core.k8s

##### ADDITIONAL INFORMATION

Effectively, I am proposing an equivalent to kubectl --all option. For example, I would like to be able to delete all pods like this:

```yaml
- name: Delete all pods
  kubernetes.core.k8s:
    kind: Pod
    namespace: mynamespace
    state: absent
```
