### ISSUE TITLE
Support stdin in k8s_exec

### ISSUE THREAD

**Issue by mbaldessari** [ansible-collections/kubernetes.core#506]
##### SUMMARY
Currently there is no way to to pass anything via stdin using the k8s_exec module, since Stdin is explicitly disabled [1]
Both command and shell ansible builtins support a stdin: parameter which could be used to pass data to a command inside container.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
k8s_exec

##### ADDITIONAL INFORMATION
Currently if you want to inject data inside a container with ansible, most of the times you need to resort to using approaches like:
`echo foo | kubectl exec -it -n ns pod -- sh -c "cat - > /tmp/foo-content"`

k8s_cp is very often a no-go as it requires tar to be installed inside the container, which has become less and less likely as people try to slim down containers all the time.

```yaml
kubernetes.core.k8s_exec:
  namespace: "{{ vault_ns }}"
  pod: "{{ vault_pod }}"
  command:  bash -e -c "cat - > /tmp/destfile"
  stdin: "{{ data_to_inject }}"
```

[1] https://github.com/ansible-collections/kubernetes.core/blob/main/plugins/modules/k8s_exec.py#L191-L202
