### ISSUE TITLE
Impossible to understand wait_condition

### ISSUE THREAD

**Issue by yajo** [ansible-collections/kubernetes.core#511]
##### SUMMARY

I'm trying to set up a wait condition, but the docs aren't very clear. Considering CRDs in k8s can define almost any behavior, either the docs are unclear about how to match a condition, or are unclear about the limitations of `wait_condition`.

[The docs in question](https://github.com/ansible-collections/kubernetes.core/blob/77dd2496d0eaccdf5073796e58d4936094264c2e/docs/kubernetes.core.k8s_module.rst):
![imagen](https://user-images.githubusercontent.com/973709/190124745-36c32a57-6940-4a49-9da1-a33b09a97102.png)

The object I'm trying to wait for is [a CRD](https://rook.io/docs/rook/v1.9/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/#obc-custom-resource-after-bucket-provisioning) that ends up with `status: {phase: Bound}` when done. No reason, no type.

My expectations is that I should be able to add this to the ansible task:

```yaml
- name: deploy stuff
  template: definition.yaml.jinja
  wait: true
  wait_condition:
    status:
      phase: Bound
```

Of course, that doesn't work, as `status` only accepts True, False or Unkown.

So, how would I declare the required values in `wait_condition` for it to deploy this CRD and wait for it to be bound?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

kubernetes.core.k8s

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0]
  config file = /var/home/yajo/prodevel/moduground/ansible.cfg
  configured module search path = ['/var/home/yajo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/rb1qdfk9mm6v7vv0cdszlsvrrdliqbmi-python3.9-ansible-core-2.13.0/lib/python3.9/site-packages/ansible
  ansible collection location = /nix/store/dg05xa69pn8hamhmvvjbv1szxr7q7k9s-ansibleDeps/collections
  executable location = /nix/store/rb1qdfk9mm6v7vv0cdszlsvrrdliqbmi-python3.9-ansible-core-2.13.0/bin/ansible
  python version = 3.9.13 (main, May 17 2022, 14:19:07) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by gravesm** [comment]
@yajo The `wait_condition` is specifically for working with the `status.conditions` array. If you need to wait on an arbitrary property you will need to use something like `k8s_info` with `until`. For example:

```yaml
- kubernetes.core.k8s_info:
    kind: ObjectBucketClaim
    name: ceph-bucket
    namespace: default
  register: result
  until: result.resources[0].status.phase == "Bound"
  retries: 5
  delay: 10
```

**Comment by yajo** [comment]
OK I understand now, thanks!

I think your comment should be in the module docs. It clarifies a lot how these properties work.

**Comment by yajo** [comment]
FWIW it can actually be in a single task, in case its deployment is idempotent and declarative (which most likely is when using ansible and k8s):

```yaml
- name: deploy stuff
  register: result
  until: result.result..status.phase | d(None) == "Bound"
  retries: 5
  delay: 10
  kubernetes.core.k8s:
    template: definition.yaml.jinja
```
