### ISSUE TITLE
k8s_info has an incorrect type in the default value!

### ISSUE THREAD

**Issue by howardjones** [ansible-collections/kubernetes.core#529]
##### SUMMARY

The default value for wait_condition.status is True, not "True", causing a warning about incorrect types from Ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s_info

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.10.17
  python version = 3.8.0 (default, Oct 28 2019, 16:14:01) [GCC 8.3.0]
```

##### COLLECTION VERSION

```paste below
2.3.2
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/home/howie/WebstormProjects/platform-tester/experiments/ansible.cfg) = minimal
```

##### OS / ENVIRONMENT

Linux (Ubuntu 20 LTS)
Azure AKS as kubernetes target (1.23.8)

##### STEPS TO REPRODUCE

```yaml
  - name: Wait for job to finish
    kubernetes.core.k8s_info:
      kind: Pod
      kubeconfig: "{{ kube_config }}"
      context: "{{ k8s_mgmt_context }}"
      label_selectors:
      - "job-name = {{ random_test_job }}"
      namespace: "{{ namespace }}"
      wait_sleep: 10
      wait_timeout: 1200 # 20 minutes should be plenty!
      wait: yes
      wait_condition:
        reason: PodCompleted
        type: Initialized
```

##### EXPECTED RESULTS

Waitin for Pod to finish, with no error output.

##### ACTUAL RESULTS

```paste below
 "warnings": [
            "The value \"True\" (type bool) was converted to \"'True'\" (type string). If this does not look like what you expect, quote the entire value to ensure it does not change."
        ]
```
the wait still worked, but above error indicates that the **default** value for `status:` is True not "True". Adding

    status: "True"

inside the `wait_condition:` did indeed stop the error.

**Comment by gravesm** [comment]
@howardjones Thanks for reporting this.

**Comment by abikouo** [comment]
@howardjones  This is one seems fixed now right ? 
I successfully run the following playbook 

```
- hosts: localhost
  connection: local

  gather_facts: False

  collections:
    - kubernetes.core
  
  vars:
    test_namespace: "wait"

  tasks:
    - k8s:
        kind: namespace
        name: "{{ test_namespace }}"

    - name: Create a job that calculates 7
      k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: int-compute
            namespace: "{{ test_namespace }}"
          spec:
            template:
              spec:
                containers:
                  - name: busybox
                    image: busybox
                    command: ["sleep", "30"]
                restartPolicy: Never

    - name: Wait for job to finish
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ test_namespace }}"
        wait_sleep: 10
        wait_timeout: 1200
        wait: yes
        wait_condition:
          reason: PodCompleted
          type: Initialized
```
