### ISSUE TITLE
helm "values.yml" files left in `/tmp`

### ISSUE THREAD

**Issue by jcpunk** [ansible-collections/kubernetes.core#530]
##### SUMMARY
When using the `kubernetes.core.helm` task, the temporary files used to populate the chart values is left behind.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.helm

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible [core 2.12.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.11.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# ansible-galaxy collection list kubernetes.core

# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.2  

# /usr/lib/python3.8/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.2.3  
```

##### CONFIGURATION

```paste below
# ansible-config dump --only-changed

```

##### OS / ENVIRONMENT

CentOS Stream 8

##### STEPS TO REPRODUCE

```yaml
- name: "Install helm package {{ kubernetes_dashboard_helm_package_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ kubernetes_dashboard_helm_package_name }}"
    chart_ref: "{{ kubernetes_dashboard_helm_repo_name }}/{{ kubernetes_dashboard_helm_package_name }}"
    namespace: "{{ kubernetes_dashboard_namespace }}"
    chart_version: "{{ kubernetes_dashboard_helm_version }}"
    create_namespace: "{{ kubernetes_dashboard_create_namespace }}"
    state: present
    values:
      metricsScraper:
        enabled: "{{ kubernetes_dashboard_metrics_scraper_enabled }}"
      metrics-server:
        enabled: false
      serviceAccount:
        create: true
      rbac:
        clusterReadOnlyRole: "{{ kubernetes_dashboard_helm_make_ro_role | bool }}"
      extraArgs:
        - --enable-skip-login
        - "--namespace={{ kubernetes_dashboard_namespace }}"
```

##### EXPECTED RESULTS

The file created in `/tmp` which is passed as an argument to `helm` would be delted

##### ACTUAL RESULTS

The temporary file is left behind.

```paste below
tmp0cfdd5p6.yml  tmp4cpjmz7l.yml  tmpasne8_0y.yml  tmpgvhfb6sf.yml  tmppa2janmc.yml  tmpwzx9_oec.yml
tmp0r0_i83t.yml  tmp6l3g8kgs.yml  tmpb4yh_h8c.yml  tmpip9nmurl.yml  tmpqg7awckq.yml  tmpyvicyxns.yml
tmp0wk8fitl.yml  tmp6npl5hly.yml  tmpd1bz9hpj.yml  tmpiskzsf40.yml  tmp_qglo6li.yml  tmpzlu70xfr.yml
tmp168tv1xq.yml  tmp75r9lnoj.yml  tmpd1o7rky0.yml  tmplbqh9afe.yml  tmpr6_z0ao_.yml  tmpztaxq3iz.yml
tmp16wd8wt2.yml  tmp8g_fa5ja.yml  tmpfc9b8wsp.yml  tmplle7dn20.yml  tmpu5e6rjzz.yml
tmp17wcxabs.yml  tmp8gzdrq1s.yml  tmpg0me5uph.yml  tmplp17d60u.yml  tmpun3zr5qh.yml
tmp1voaopeq.yml  tmp92i1qz24.yml  tmpgmjr6dr5.yml  tmpmy3r5yzp.yml  tmpwsbrjcr4.yml
tmp2b09y_9s.yml  tmpanewf114.yml  tmpgpc8uird.yml  tmpo7189de9.yml  tmpwuy8k5g1.yml
```
