### ISSUE TITLE
Json merge_type is not applying 

### ISSUE THREAD

**Issue by rgordill** [ansible-collections/kubernetes.core#54]
##### SUMMARY
When using json merge, the playbook is running ok but not doing anything. It is the same as https://github.com/ansible/ansible/issues/65897 that was automatically closed by the repo migration.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rgordill/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

Fedora release 33 (Thirty Three)
Linux musashi 5.11.11-200.fc33.x86_64 ansible-collections/community.kubernetes#1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

1) Start a simple minikube with:
`minikube start -addons ingress`
2) See the configuration of the ingress deployment with
`kubectl get deployments.apps -n kube-system ingress-nginx-controller -o yaml`
3) Execute the following ansible tasks

```yaml
- name: Patch Nginx to support ssl-passthough
  community.kubernetes.k8s:
    state: present
    kind: deployment
    api_version: apps/v1
    name: ingress-nginx-controller
    namespace: kube-system
    merge_type: 
    - json
    definition:
    - op: add
      path: '/spec/template/spec/containers/0/args/-'
      value: '--enable-ssl-passthrough'
```
4) Check with the same `kubectl`command, that the deployment is exactly the same
5) Try to do it manually with
```
kubectl patch deployment \
  ingress-nginx-controller \
  --namespace kube-system \
  --type='json' \
  -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--enable-ssl-passthrough"}]'
```
6) Again get the deployment, now the merge has been applied.

##### EXPECTED RESULTS
Merge patch successfully applied as in kubectl.

##### ACTUAL RESULTS

[result.txt](https://github.com/ansible-collections/community.kubernetes/files/6296112/result.txt)
