### ISSUE TITLE
Proxy param does not accept authentication header

### ISSUE THREAD

**Issue by senpai-d** [ansible-collections/kubernetes.core#55]
##### SUMMARY
When setting a proxy url in the proxy param, the username:password header is not read. It only accesses the URL, which returns a 407 if authentication is required for the proxy.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION
```paste below
ansible 2.9.0
   config file = /home/user/.ansible.cfg
   configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   ansible python module location = /home/user/projects/python_envs/ansible-env/lib/python3.6/site-packages/ansible
   executable location = /home/user/projects/python_envs/ansible-env/bin/ansible
   python version = 3.6.9 (default, Jan 26 2021, 15:33:00)
```

##### CONFIGURATION
```paste below
DEFAULT_ROLES_PATH(/home/user/.ansible.cfg) = ['/home/user/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
RETRY_FILES_ENABLED(/home/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
WSL Ubuntu 18.03
Pythion 3.6 virtual environment

##### STEPS TO REPRODUCE
With a proxy url such as http://USERNAME:PASSWORD@proxy.com:3001, the USERNAME:PASSWORD header is not loaded in, resulting in a 401 due to authentication required with proxy.

```yaml
- name: Set up namespace
  hosts: localhost
  tasks:
    - name: create namespace
      k8s:
        host: "https://kube-cluster.com"
        api_key: "api_token"
        proxy: "http://USERNAME:PASSWORD@proxy.com:3001"
        state: present
        name: "new-default-namespace"
        api_version: "v1"
        state: present
```

##### EXPECTED RESULTS
Expected for the namespace to be created.

##### ACTUAL RESULTS
Received a 407 from proxy server.

```paste below
kubernetes.client.rest.ApiException: (401)
Reason: authenticationrequired
```

The rest of the output is proxy server error being returned.

**Comment by abikouo** [comment]
Hi @senpai-d 
Thanks for reporting this issue, I will try to reproduce

**Comment by abikouo** [comment]
@senpai-d 
could you please check with this pull request https://github.com/ansible-collections/kubernetes.core/pull/58 ?

**Comment by senpai-d** [comment]
Hi @abikouo ,

I have installed the collection locally to test it out and the proxy_headers variable was picked up but it still returned an authentication required.

Does the username:password need to be encoded or anything?

Thanks.

**Comment by abikouo** [comment]
@senpai-d could you please display the version of the kubernetes python api you are using ? 
```
python -c "import kubernetes;print(kubernetes.__version__)"
```

**Comment by abikouo** [comment]
@senpai-d using this simple playbook I can talk to the kubernetes api via proxy. 

```
- name: create namespace
  hosts: localhost
  gather_facts: false
  tasks:
  - name: create namespace proxy
    kubernetes.core.k8s:
      kind: namespace
      name: proxy
      proxy: "http://192.168.123.7:3128" => This is my proxy host and port
      proxy_headers: "ansible:test"  => username = 'ansible' and password = 'test' set in clear in the playbook
      state: present
```
