### ISSUE TITLE
Task with k8s definition and state=absent (to delete a resource) fails if the resource kind does not exist

### ISSUE THREAD

**Issue by aristapimenta** [ansible-collections/kubernetes.core#553]
##### SUMMARY

I have a task that deploys a `ScaledObject` (CRD from https://keda.sh/). When the KEDA CRD does not currently exist in the cluster (because KEDA itself is not installed in that cluster yet) and I set `state: absent` to delete the `ScaledObject` (which already does not exist!), the module fails with the error:

```
TASK [hadoop : Deploy nodemanager scaledobject] ********************************
fatal: [localhost]: FAILED! => changed=false 
  msg: Failed to find exact match for keda.sh/v1alpha1.ScaledObject by [kind, name, singularName, shortNames]
```

The task should succeed instead, because the `ScaledObject` resource necessarily already does not exist (since the CRD itself does not exist).

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/home/prod/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/prod/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.8 (main, Nov 10 2022, 12:59:17) [GCC 11.2.1 20220219]
  jinja version = 3.1.2
  libyaml = False
```

##### COLLECTION VERSION

```
# /usr/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.2  
```

##### OS / ENVIRONMENT

We are installing the pip package https://pypi.org/project/ansible/6.6.0/ in a Docker image based from Golang:

```
FROM golang:1.19.4-alpine3.16
```

##### STEPS TO REPRODUCE

0. Prepare a kubernetes cluster. It doesn't need to have anything in particular installed on it. It's *not* necessary to install KEDA (actually, installing KEDA would mess the reproduction of the issue).

1. Have a KEDA `ScaledObject` definition like this in a file `./templates/hadoop-nodemanager-scaledobject.yml.j2`:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nodemanager
  namespace: hadoop
spec:
  ...
```

2. Run a task like this:

```yaml
- name: Deploy nodemanager scaledobject
  k8s:
    state: absent
    merge_type:
    - merge
    definition: "{{ lookup('template', './templates/hadoop-nodemanager-scaledobject.yml.j2') | from_yaml }}"
```

##### EXPECTED RESULTS

```
TASK [hadoop : Deploy nodemanager scaledobject] ********************************
ok: [localhost]
```

##### ACTUAL RESULTS

```
TASK [hadoop : Deploy nodemanager scaledobject] ********************************
fatal: [localhost]: FAILED! => changed=false 
  msg: Failed to find exact match for keda.sh/v1alpha1.ScaledObject by [kind, name, singularName, shortNames]
```
