### ISSUE TITLE
Missing option to set release_name in helm_template?

### ISSUE THREAD

**Issue by sfhl** [ansible-collections/kubernetes.core#555]
##### SUMMARY
Hi there,
i am it seems that i am not able to set `release_name` or `.Release.Name` for the `helm_template` module, resulting in deployments like the following. How may i be able to set `release_name` when using `helm_template`?

```
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME
...
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`helm_template`

##### ANSIBLE VERSION

```paste below
2.9.27
```

##### COLLECTION VERSION

```paste below
2.3.2
```

##### STEPS TO REPRODUCE
Try to template a helm chart without `.Release.Name` set.

```yaml
---

- name: Render templates to specified directory
  kubernetes.core.helm_template:
    chart_ref: "{{ _helm_chart.1.ref }}"
    chart_version: "{{ _helm_chart.1.version | default(omit) }}"
    include_crds: "{{ _helm_chart.1.include_crds | default('yes') | bool }}"
    release_namespace: "{{ _helm_chart.0.name }}"
    values:
    update_repo_cache: yes
  loop: "{{ _k8s_cluster['namespace_list']|default([])|subelements('helm_charts',{'skip_missing':true})|list }}"
  loop_control: {loop_var: _helm_chart}
  environment:
    HELM_CONFIG_HOME: "./.helm"
  register: _render

- name: "Create helm manifest files"
  ansible.builtin.copy:
    content: "{{ _chart.stdout }}"
    dest: "{{ [k8s_state_dir, _k8s_cluster.name, _filename] | join('/') }}"
    mode: 0600
    force: yes
  vars:
    _filename: "{{ ['helm', _chart._helm_chart.0.name, _chart._helm_chart.1.ref  ]|join('_')|regex_replace('[^A-Za-z0-9]+','_') ~ '.yml' }}"
  loop: "{{ _render.results }}"
  loop_control: {loop_var: _chart}
```

##### EXPECTED RESULTS
`RELEASE-NAME` does not exist in resulting manifest files.

##### ACTUAL RESULTS
`RELEASE-NAME` does exist in resulting manifest files.

```
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME
...
```
