### ISSUE TITLE
Failed to load kubeconfig due to Invalid kube-config file

### ISSUE THREAD

**Issue by danielburrell** [ansible-collections/kubernetes.core#56]
##### SUMMARY

When k8s_info module runs on a non-controller host, it looks for a kubeconfig file on the controller host, but returns "invalid kube-config file" error even though the kubeconfig file on the controller is valid. 

To demonstrate this I have 2 scenarios to be compared; the first scenario (CI) seems to work by co-incidence, the second scenario (local development) reveals the bug.

**CI Scenario:**
- I have a CI environment where two new servers are terraformed, one as control box, the other as target box. 
- CI will run the ansible playbook from the control box and deploy a kubernetes cluster to the target box as part of the playbook. - - As part of the playbook, the target box's kubeconfig file `~centos/.kube/config` is copied to the control box at the same location `~centos/.kube/config` near the end of the play. 
- At all times everything runs as 'centos' user. 
- When I run a k8s_info action in this scenario with `hosts: server` (target), specifying the kubeconfig file, I am able to confirm certain objects exist in my cluster. This works as intended.
`whoami` on all boxes would return `centos` and ansible_user would also return `centos`. The 2 boxes are basically the same, just different 'purpose'. This is the only scenario that works.

**Local Development Scenario**
- I have a developer computer which acts as a control box, I am logged in as myself e.g. `daniel` there is a target box configured the same way as the CI scenario (with a centos user).
- When I run the installation, I set `ansible-playbook .... -u centos`, the ssh user is `centos`, but I run the installer as `daniel`. so
`whoami` on the localhost would return `daniel` and anywhere else would be `centos`.
As above the kubeconfig file is in its place on the target machine, and as before gets copied to the control box. Note in the CI scenario, the copy was to an identical folder, `~centos/.kube/config`, but this time in this scenario, it's copied to `~daniel/.kube/config`

The documentation does not state where the kubeconfig file must be located, nor does it state that the k8s_info must be run on the control box. So up till now I had no reason to think anything was wrong. When my k8s_info task ran on the target machine, I assumed it was using the target machine kubeconfig (not the controlbox kubeconfig).

When I try to run a k8s_info action in this scenario with `hosts: server` (target) specifying the kubeconfig file as `~centos/.kube/config` then it says the file cannot be found on the AnsibleControl machine (of course it's now located at `~daniel/.kube/confing` on the control machine

This suggests that regardless of the `hosts`, the role is expecting to find the kubeconfig file on the control machine. Can you confirm this is the case?

Assuming this is true, if I tell the installer to use `~daniel/.kube/config` (which exists on the control machine), with `hosts: server` then it tells me that the config isn't valid! 

The only scenario that works with `hosts: server` is if my target and control both have a kubeconfig file in the same location.

This seems to be a bug as 
- I would have expected my config to be considered valid as below.
- I would expect the operation to work in locations other than the control machine.

Can you clarify the following:
- Where can these tasks run, `localhost` only? or anywhere?
- Which `kubeconfig` file is used, control? or the current `inventory_host`?
- Has this behaviour changed recently?

```
failed: [10.50.52.94] (item={'name': 'coredns', 'quantity': 1}) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "item": {"name": "coredns", "quantity": 1}, "msg": "Failed to load kubeconfig due to Invalid kube-config file. No configuration found."}
```

```
ls ~/.kube/config
/home/daniel/.kube/config
```

```
cat ~/.kube/config

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redactedbase64==
    server: https://10.50.52.94:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: redacted
    username: redacted
```
This is all very strange, as this causes the playbook to fail, and I am able to cat the file, and it's perfectly valid, and works with kubectl.

Any ideas?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s_info

##### ANSIBLE VERSION

```paste below
[WARNING]: Ansible is being run in a world writable directory (/home/daniel/projects/prom/project), ignoring it as an ansible.cfg source. For more
information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
ansible-playbook 2.10.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/daniel/.pex/installed_wheels/04c26471cb05787fcd8372d2f2bea63afb042678/ansible_base-2.10.6-py3-none-any.whl/ansible
  executable location = ansible-playbook
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

centos 7.9

##### STEPS TO REPRODUCE

```yaml

- name: Copy kubeconfig from the server to the control machine
  fetch:
   # in CI both control_user_id and ansible_user are centos, in development, control_user_id is daniel, ansible_user is centos
    src: ~{{ ansible_user }}/.kube/config
    dest: ~{{ control_user_id }}/.kube/config
    flat: yes
  become: no

# SNIP
# run once on host 'server' (target)
- name: "Verify k3s deployment"
  community.kubernetes.k8s_info:
    kind: Deployment
    wait: yes
    name: "{{ item.name }}"
    namespace: kube-system
    wait_timeout: 360
    wait_sleep: 10
   #apparently this kubeconfig file is supposed to be on the control box, can this be added to the docs?
    kubeconfig: "~{{ control_user_id }}/.kube/config"   #in development control_user_id  this is ~daniel in CI its centos
  register: deployment_status
  run_once: true
  become: yes
  until: (deployment_status.resources[0].status.readyReplicas | default(0) == item.quantity)
  retries: 5
  loop:
    - { name: 'coredns', quantity: 1 }
```

##### EXPECTED RESULTS

I would have expected my kubeconfig file to be considered valid.

##### ACTUAL RESULTS

```
failed: [10.50.52.94] (item={'name': 'coredns', 'quantity': 1}) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "item": {"name": "coredns", "quantity": 1}, "msg": "Failed to load kubeconfig due to Invalid kube-config file. No configuration found."}
```

```paste below

```
