### ISSUE TITLE
Failed to create object using `template` parameter of k8s module

### ISSUE THREAD

**Issue by profhase** [ansible-collections/kubernetes.core#560]
Probably related: https://github.com/ansible-collections/kubernetes.core/issues/115

##### SUMMARY
```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: assure namespace
      k8s:
        #definition: "{{ lookup('template', 'namespace.yml') }}"
        template: namespace.yml
      vars:
        name: "myname"

```
throws:
```
 {"changed": false, "error": "", "msg": "Failed to create object: The `items` field in the body must be populated when calling methods on a ResourceList", "reason": "", "status": ""}

```

It works if you uncomment the definition line and comment the template line.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```
kubernetes.core               2.3.2  

```

##### CONFIGURATION

```
ansible --version
  ansible [core 2.14.1]
  config file = None
  python version = 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] (/usr/bin/python3)


```

##### OS / ENVIRONMENT
Fedora 37

##### ACTUAL RESULTS

```
 {"changed": false, "error": "", "msg": "Failed to create object: The `items` field in the body must be populated when calling methods on a ResourceList", "reason": "", "status": ""}


```

**Comment by abikouo** [comment]
Hi @profhase, 

Using the Fully qualified collection name or adding collections keyword into playbook should resolve the issue, we need to investigate why this is not working when using only the module name.
Could you please try using one of the following 

```
- hosts: localhost
  
  collections:
  - kubernetes.core
 
  tasks:
   - name: assure namespace
     k8s:
       (...)
```

```
- hosts: localhost
  
  tasks:
   - name: assure namespace
     kubernetes.core.k8s:
       (...)
```
