### ISSUE TITLE
kubernetes.core.k8s module annotation documentation missing

### ISSUE THREAD

**Issue by mipam007** [ansible-collections/kubernetes.core#564]
##### SUMMARY
Missing key information about metadata and annotations. It is not clear, how you can define e.g. taints and tolerations.

##### ISSUE TYPE
- Documentation Report
- There is no example, nor explanation of how you can combine yaml or json stanza for applying tolerations with Exists or Equal operators, keys and values and effect, e.g. on top of the namespace or other related k8s objects. 

##### COMPONENT NAME
kubernetes.core.k8s module, defining toleration on k8s objects

##### ANSIBLE VERSION

```
latest
```

**Comment by gravesm** [comment]
@mipam007 Thanks for opening an issue. Could you provide some more information on what you're having problems with? Tolerations can be applied to pods in the k8s definition exactly as you would using `kubectl`. For example:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - kubernetes.core.k8s:
        kind: Namespace
        name: testing

    - kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            namespace: testing
            name: nginx
            labels:
              env: test
          spec:
            containers:
            - name: nginx
              image: nginx
              imagePullPolicy: IfNotPresent
            tolerations:
            - key: "example-key"
              operator: "Exists"
              effect: "NoSchedule"
```

**Comment by mipam007** [comment]
Hi and many thanks for answering! I am trying to apply tolerations on namespace level via annotation as I described.

Example code, which I am not sure is working.


```- name: Tolerations
  kubernetes.core.k8s:
    api_key: "{{ api_key }}"
    validate_certs: "{{ validate_certs }}"
    host: "{{ auth.host }}"
    state: patched
    kind: Namespace
    name: "{{ item }}"
    definition:
      metadata:
        annotations:
          scheduler.alpha.kubernetes.io/defaultTolerations:
            '[{"operator": "Exists",
            "effect": "NoSchedule",
            "key": "node-role.kubernetes.io/infra"}]'
  loop:
    - project1
    - project2
    - project3
```

**Comment by gravesm** [comment]
As far as I can tell, it is working exactly as it should. Just to reiterate, for the most part, we don't touch the resource definition; it gets passed directly to kubernetes as is. You don't give any details about what your problem is, but based on your example, it's possible you may need to enable the [PodTolerationRestriction admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podtolerationrestriction), as this appears to be disabled by default.

`main.yml`:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - kubernetes.core.k8s:
        kind: Namespace
        name: testing

    - kubernetes.core.k8s:
        state: patched
        kind: Namespace
        name: testing
        definition:
          metadata:
            annotations:
              scheduler.alpha.kubernetes.io/defaultTolerations:
                '[{"operator": "Exists",
                "effect": "NoSchedule",
                "key": "node-role.kubernetes.io/infra"}]'

    - kubernetes.core.k8s_info:
        kind: Namespace
        name: testing
      register: result

    - debug:
        msg: "{{ result.resources[0].metadata.annotations }}"
```

output:
```
PLAY [localhost] ****************************************************************************************************************************

TASK [kubernetes.core.k8s] ******************************************************************************************************************
changed: [localhost] => {"changed": true, "method": "create", "result": {"apiVersion": "v1", "kind": "Namespace", "metadata": {"creationTimestamp": "2023-01-11T19:57:54Z", "labels": {"kubernetes.io/metadata.name": "testing"}, "managedFields": [{"apiVersion": "v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:labels": {".": {}, "f:kubernetes.io/metadata.name": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2023-01-11T19:57:54Z"}], "name": "testing", "resourceVersion": "641", "uid": "c0036215-98bc-4c83-b538-f10ae0ab3a11"}, "spec": {"finalizers": ["kubernetes"]}, "status": {"phase": "Active"}}}

TASK [kubernetes.core.k8s] ******************************************************************************************************************
changed: [localhost] => {"changed": true, "method": "patch", "result": {"apiVersion": "v1", "kind": "Namespace", "metadata": {"annotations": {"scheduler.alpha.kubernetes.io/defaultTolerations": "[{\"operator\": \"Exists\", \"effect\": \"NoSchedule\", \"key\": \"node-role.kubernetes.io/infra\"}]"}, "creationTimestamp": "2023-01-11T19:57:54Z", "labels": {"kubernetes.io/metadata.name": "testing"}, "managedFields": [{"apiVersion": "v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:annotations": {".": {}, "f:scheduler.alpha.kubernetes.io/defaultTolerations": {}}, "f:labels": {".": {}, "f:kubernetes.io/metadata.name": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2023-01-11T19:57:54Z"}], "name": "testing", "resourceVersion": "644", "uid": "c0036215-98bc-4c83-b538-f10ae0ab3a11"}, "spec": {"finalizers": ["kubernetes"]}, "status": {"phase": "Active"}}}

TASK [kubernetes.core.k8s_info] *************************************************************************************************************
ok: [localhost] => {"api_found": true, "changed": false, "resources": [{"apiVersion": "v1", "kind": "Namespace", "metadata": {"annotations": {"scheduler.alpha.kubernetes.io/defaultTolerations": "[{\"operator\": \"Exists\", \"effect\": \"NoSchedule\", \"key\": \"node-role.kubernetes.io/infra\"}]"}, "creationTimestamp": "2023-01-11T19:57:54Z", "labels": {"kubernetes.io/metadata.name": "testing"}, "managedFields": [{"apiVersion": "v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:annotations": {".": {}, "f:scheduler.alpha.kubernetes.io/defaultTolerations": {}}, "f:labels": {".": {}, "f:kubernetes.io/metadata.name": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2023-01-11T19:57:54Z"}], "name": "testing", "resourceVersion": "644", "uid": "c0036215-98bc-4c83-b538-f10ae0ab3a11"}, "spec": {"finalizers": ["kubernetes"]}, "status": {"phase": "Active"}}]}

TASK [debug] ********************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "scheduler.alpha.kubernetes.io/defaultTolerations": "[{\"operator\": \"Exists\", \"effect\": \"NoSchedule\", \"key\": \"node-role.kubernetes.io/infra\"}]"
    }
}

PLAY RECAP **********************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
