### ISSUE TITLE
idempotency problem with helm

### ISSUE THREAD

**Issue by sherlant** [ansible-collections/kubernetes.core#565]
Hello,
I have a problem with helm module. The idempotency don't work. this is my module definition : 
```yaml
- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    chart_version: 1.9.5
    values_files:
      - /tmp/cilium_values.yaml
    binary_path: /home/local_user/.local/bin/helm
    wait: true
    kubeconfig: /home/local_user/.kube/config"
  delegate_to: localhost
  become: yes
  become_user: local_user
```
helm diff is correctly installed. When I try my playbook for the first time, the chart is correctly deployed on the cluster. When i retry the playbook, i've got a changed on the task.

Thx

**Comment by gravesm** [comment]
I'm unable to reproduce this. As a start, you will need to provide us with the version of the collection, ansible, helm and helm-diff that you are using. We will also need to see the full output of running the playbook with `-vvv`.

**Comment by sherlant** [comment]
sure,
- kubernetes.core: 2.3.2
- helm: v3.10.0
- helm-diff: 3.6.0
- output off playbook with -vvv : in attachment
[playbook_vvv.log](https://github.com/ansible-collections/kubernetes.core/files/10403992/playbook_vvv.log)

**Comment by sherlant** [comment]
Hello,
you need more info ?

**Comment by gravesm** [comment]
I'm still unable to reproduce this. What do you get when you run ansible with `--check --diff`?

**Comment by miminar** [comment]
@sherlant I had the same issue using the same chart (cilium).  By default, cilium regenerates all the embedded TLS certificates, which triggers a change any time `helm upgrade` is run. This is the diff I was seeing:

```
helm diff upgrade -n cilium cilium cilium/cilium -f /tmp/ansible.za2fwbj7
cilium, cilium-ca, Secret (v1) has changed:
  # Source: cilium/templates/cilium-ca-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: cilium-ca
    namespace: cilium
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   ca.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   ca.key: '++++++++ # (1679 bytes)'

cilium, hubble-ca-secret, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/ca-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-ca-secret
    namespace: cilium
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   ca.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   ca.key: '++++++++ # (1679 bytes)'

cilium, hubble-relay-client-certs, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/relay-client-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-relay-client-certs
    namespace: cilium
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   tls.crt: '-------- # (1200 bytes)'
-   tls.key: '-------- # (1679 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   tls.crt: '++++++++ # (1200 bytes)'
+   tls.key: '++++++++ # (1675 bytes)'
  type: kubernetes.io/tls

cilium, hubble-server-certs, Secret (v1) has changed:
  # Source: cilium/templates/hubble/tls-helm/server-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: hubble-server-certs
    namespace: cilium
  data:
-   ca.crt: '-------- # (1127 bytes)'
-   tls.crt: '-------- # (1237 bytes)'
-   tls.key: '-------- # (1679 bytes)'
+   ca.crt: '++++++++ # (1127 bytes)'
+   tls.crt: '++++++++ # (1237 bytes)'
+   tls.key: '++++++++ # (1679 bytes)'
  type: kubernetes.io/tls
```

Fortunately, one can configure cilium to use either certmanager or cron-job for TLS secrets generation / rotation. Here are the values I added to the values file to enable the latter:

```yaml
hubble:
  ...
  tls:
    auto:
      enabled: true
      method: cronJob

certgen:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
```

Once re-deployed, it produces empty diff => no change. Hope it helps.
