### ISSUE TITLE
Kubernetes module add rollout tasks

### ISSUE THREAD

**Issue by Theprim0** [ansible-collections/kubernetes.core#567]
##### SUMMARY

It would be interesting to include tasks into kubernetes.core to interact with ROLLOUT.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

kubectl rollout 

rollout history, rollout restart, etc...

##### ADDITIONAL INFORMATION

```yaml
Tasks as we would do with CLI:
kubectl rollout status Deployment/mi-deployment
```

**Comment by gravesm** [comment]
Thanks for filing a feature request. Could you be a bit more specific about what you would like to be able to do? I believe the collection should already support the functionality provided by `kubectl rollout`. The information from `status` and `history` should be available from the `k8s_info` module, but in a machine actionable format. The `k8s_rollback` module does what `undo` does. `pause` and `resume` can both be accomplished with a simple `k8s_json_patch` operation to set the `/spec/paused` property. The only thing that can't be done easily with the collection is the rolling restart.

**Comment by MarceloFCandido** [comment]
> Thanks for filing a feature request. Could you be a bit more specific about what you would like to be able to do? I believe the collection should already support the functionality provided by `kubectl rollout`. The information from `status` and `history` should be available from the `k8s_info` module, but in a machine actionable format. The `k8s_rollback` module does what `undo` does. `pause` and `resume` can both be accomplished with a simple `k8s_json_patch` operation to set the `/spec/paused` property. The only thing that can't be done easily with the collection is the rolling restart.

Which way do you suggest to do do `rollout restart` with the collection? I would like to apply the `rollout restart` that can be seen [here](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html) but without using the `ansible.builtin.shell` module.

**Comment by Theprim0** [comment]
@gravesm exactly, i see k8s_rollback module exists, but I mean "rollout".
As @MarceloFCandido says, we can't acomplish "rollout restart" with kubernetes.core module neither with k8s_rollback module.

**Comment by grsiepka** [comment]
+1 for this feature, but wonder if in the meantime, could you use the kubernetes.core.k8s_scale module to scale the deployment to 0, then back to what it was?

**Comment by JossWhittle** [comment]
The following works for anyone else who finds this thread. 

```
kubectl rollout status -w deployment/foo-bar -n foo
```

becomes...

```
- name: "k8s wait for deployment/foo-bar rollout"
  kubernetes.core.k8s_info:
    kind: Rollout
    namespace: "foo"
    name: "deployment/foo-bar"
    wait: true
    wait_condition:
      type: Succeeded
```

Maybe this could be added to the examples? https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html#examples

**Comment by besmirzanaj** [comment]
+1 for this. seems a very useful feature

**Comment by ShubhamRasal** [comment]
+1 for this. seems a very useful feature

**Comment by psyntium** [comment]
+1

**Comment by mohag** [comment]
> ```
> kubectl rollout status -w deployment/foo-bar -n foo
> ```
> becomes...
> ```
> - name: "k8s wait for deployment/foo-bar rollout"
>   kubernetes.core.k8s_info:
>     kind: Rollout
>     namespace: "foo"
>     name: "deployment/foo-bar"
>     wait: true
>     wait_condition:
>       type: Succeeded
> ```

That gives me a (green) output saying:
```
Failed to find API for resource with apiVersion "v1" and kind "Rollout"
```

**Comment by dyegoe** [comment]
+1

But, meanwhile, I found a way to restart a deployment. I was looking into restarting ArgoCD deployment after patching the configmap.

I achieved that using this:
```yaml
- name: Restart ArgoCD repo-server
  kubernetes.core.k8s:
    state: patched
    kind: Deployment
    name: argocd-repo-server
    namespace: "{{ argocd_namespace }}"
    definition:
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{ now(fmt='%Y-%m-%dT%H:%M:%SZ') }}"
```
