### ISSUE TITLE
kubernetes.core.k8s raises a fatal error when ensuring that a resource is absent if its resource definition does not exist

### ISSUE THREAD

**Issue by jsolbrig** [ansible-collections/kubernetes.core#569]
##### SUMMARY

When a resource type (i.e. a custom resource definition) has not been defined in a cluster, kubernetes.core.k8s encounters a fatal error when ensuring that a resource of that type is absent.

I would expect it to simply return `OK` or `SKIPPED` when encountering resources for which a resource definition does not exist if the requested state is `absent`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jsolbrig/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/jsolbrig/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Apr 21 2022, 07:55:08) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection      Version
--------------- -------
kubernetes.core 2.3.2 
```

##### CONFIGURATION

Nothing

##### OS / ENVIRONMENT

Output from `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

##### STEPS TO REPRODUCE

Create a file called `bad-resource-definition.yaml` with the following contents:
```yaml
apiVersion: bad.resource.io/v1
kind: BadResource
metadata:
  name: does-not-exist
data:                                                                                                                                                 
  foo: |
    bar
```

Create a playbook that attempts to delete the bad resource:

```yaml
- name: "Testing"                    
  hosts: localhost                   
  connection: local                  
  tasks:                             
  - name: Delete resource            
    kubernetes.core.k8s:             
      src: bad-resource-definition.yaml                                                                                                               
      state: absent
```

##### EXPECTED RESULTS

I would expect this to return either `OK` or `SKIPPED` when attempting to delete the non-existent resource, even if the CRD does not exist in the cluster.

##### ACTUAL RESULTS

When attempting to delete the resource, a fatal error is encountered.

```bash
PLAY [Testing] ***************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [localhost]

TASK [Delete resource] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find exact match for bad.resource.io/v1.BadResource by [kind, name, singularName, shortNames]"}

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
