### ISSUE TITLE
`module_defaults` for `group/k8s` is ignored by task of type `kubernetes.core.helm`

### ISSUE THREAD

**Issue by djpbessems** [ansible-collections/kubernetes.core#576]
##### SUMMARY
`module_defaults` for `group/k8s` is ignored by task of type `kubernetes.core.helm`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.helm

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection      Version
--------------- -------
kubernetes.core 2.3.2
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

Ubuntu 22.04

##### STEPS TO REPRODUCE

```yaml
- block:

    - name: Install longhorn chart
      kubernetes.core.helm:
        name: example
        chart_ref: /path/to/chart
        release_namespace: example
        create_namespace: yes
        wait: no
        values: "{{ chart_values }}"

  module_defaults:
    group/k8s:
      kubeconfig: "{{ kubeconfig.path }}"

```

##### EXPECTED RESULTS
Default configuration defined is used.

##### ACTUAL RESULTS

```paste below
Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: Kubernetes cluster unreachable: Get \"http://localhost:8080/version\": dial tcp 127.0.0.1:8080: connect: connection refused
```
