### ISSUE TITLE
Issue with quote when I create secret entries in kubernetes

### ISSUE THREAD

**Issue by sunilsankar** [ansible-collections/kubernetes.core#599]
##### SUMMARY
Noticed that when I create secret using this collection I see the secret value in quotes. But when I use kubectl I dont see the quotes for the secret value. Is there anywork around to add it without quotes

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sunil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sunil/ansible-kubernetes/sunil/lib/python3.9/site-packages/ansible
  ansible collection location = /home/sunil/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sunil/ansible-kubernetes/sunil/bin/ansible
  python version = 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0] (/home/sunil/ansible-kubernetes/sunil/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```
Collection        Version
----------------- -------
community.general 6.4.0  


```

##### CONFIGURATION

```
CONFIG_FILE() = /etc/ansible/ansible.cfg

```

##### STEPS TO REPRODUCE

```
secret.yml
- hosts: localhost
  vars:
    foo: "bar"
  tasks:
   - name: Create new secret
     kubernetes.core.k8s:
       state: present
       definition:
          apiVersion: v1
          data:
            foo: "{{ foo | to_json | b64encode }}"
          kind: secret
          metadata:
            namespace: test
            name: test
          type: Opaque

```
```
ansible-playbook -i inventory secret.yml 

PLAY [localhost] ******************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create new secret] **********************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
When you decode the value it is in quotes
```
 kubectl get secrets test -n test --template={{.data.foo}}| base64 --decode
"bar"
```
But when I use kubectl to create the secret the entry is without quotes
```
$ kubectl create secret generic test -n test --from-literal=foo=bar
secret/test created
```
```
$ kubectl get secrets test -n test --template={{.data.foo}}| base64 --decode
bar
```
```
```
##### ACTUAL RESULTS

Is there a way to get without quotes
```
 kubectl get secrets test -n test --template={{.data.foo}}| base64 --decode
bar
```
