### ISSUE TITLE
When using set_values arg with type file, deploy "fails" with error: control characters are not allowed

### ISSUE THREAD

**Issue by SomaGallai** [ansible-collections/kubernetes.core#627]
##### SUMMARY
When using `set_values` argument with `value_type: file`, deploy "fails" with error:

```bash
fatal: [localhost]: FAILED! => {"changed": false, "command": "/opt/homebrew/bin/helm get values --output=yaml secretnodename", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed\n", "stderr": "Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed\n", "stderr_lines": ["Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed"], "stdout": "", "stdout_lines": []}
```

The file that is meant to be attached to the deployment is in `jks` file format, but the same issue arose with `pfx` file format as well. The deployment actually succeeds hence the quotation mark in the title as well, BUT during re-deployments/upgrades it does not work as it just keeps throwing the same error without doing the deployment .  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: `kubernetes.core.helm`
parameter: `set_values`

##### ANSIBLE VERSION

```bash
ansible [core 2.13.4]
  config file = /Users/user/project/ansible/secret/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/Library/Python/3.10/lib/python/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/user/Library/Python/3.10/bin/ansible
  python version = 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```bash
$ansible-galaxy collection list kubernetes.core  

# /Users/user/Library/Python/3.10/lib/python/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0  

# /Users/user/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0  
```

##### CONFIGURATION

```bash
DEFAULT_ACTION_PLUGIN_PATH(/Users/user/project/ansible/secret/ansible.cfg) = ['/Users/user/project/ansible/plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/user/project/ansible/secret/ansible.cfg) = ['/Users/user/project/ansible/plugins/callback_plugins']
DEFAULT_HASH_BEHAVIOUR(/Users/user/project/ansible/secret/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/user/project/ansible/secret/ansible.cfg) = ['/Users/user/project/ansible/secret/inventory']
DEFAULT_ROLES_PATH(/Users/user/project/ansible/secret/ansible.cfg) = ['/Users/user/project/ansible/secret/roles', '/Users/user/project/ansible/roles']
DEFAULT_TIMEOUT(/Users/user/project/ansible/secret/ansible.cfg) = 400
DEFAULT_VAULT_PASSWORD_FILE(/Users/user/project/ansible/secret/ansible.cfg) = /Users/user/.vault.key
DEFAULT_VERBOSITY(/Users/user/project/ansible/secret/ansible.cfg) = 0
DEPRECATION_WARNINGS(/Users/user/project/ansible/secret/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/user/project/ansible/secret/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```bash
Host: macOS Ventura 13.4
Target: localhost
```
##### STEPS TO REPRODUCE

```yaml
some steps to pull secrets from save location in JSON format and make sure syntax is proper to convert to yaml

- name: Populate tmpvalues.yaml
  shell: echo "{{ values_vars | to_nice_yaml (width=64, explicit_start=True) }}" > tmpvalues.yaml

- name: Set pfx file for service
  copy: src=encrypted_some_com_pfx dest=tmp_some_com_pfx force=yes decrypt=true

- name: Deploy latest version of service
  kubernetes.core.helm:
    name: "{{ service_to_deploy | lower }}"
    chart_ref: "company-charts/{{ service_to_deploy | lower }}"
    release_namespace: generic-company-namespace
    create_namespace: yes
    wait: yes
    values_files: tmpvalues.yaml
    set_values:
      - value: somepfxContent=tmp_some_com_pfx
        value_type: file
```

##### EXPECTED RESULTS

Successful deployment of service and it's components.

##### ACTUAL RESULTS

Throws error that makes further upgrades and similar actions impossible, without manually removing the service from the Cluster first.

On last step (Deploy latest version of service) of shown Ansible playbook:
```bash
fatal: [localhost]: FAILED! => {"changed": false, "command": "/opt/homebrew/bin/helm get values --output=yaml secretnodename", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed\n", "stderr": "Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed\n", "stderr_lines": ["Error: unable to write YAML output: error converting JSON to YAML: yaml: control characters are not allowed"], "stdout": "", "stdout_lines": []}
```
