### ISSUE TITLE
Helm diff does not use set_values

### ISSUE THREAD

**Issue by PPACI** [ansible-collections/kubernetes.core#638]
hi..
Thank you for this great collection!
I encountered what I consider to be a bug while deploying Linkerd.

##### SUMMARY

When deploy helm chart with kubernetes.core.helm, the helm diff plugin will not use any `set_values`.
This prevent deployment even if not using --diff in terraform.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.helm .

##### ANSIBLE VERSION

```paste below
(venv) ➜  kubernetes git:(master) ✗ ansible-playbook --version                                                                    
ansible-playbook [core 2.14.5]
  config file = None
  configured module search path = ['/Users/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXX/Gitlab/ansible/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/XXX/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/XXX/Gitlab/ansible/venv/bin/ansible-playbook
  python version = 3.10.12 (main, Jun 15 2023, 07:49:25) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/pierrepaci/Gitlab/ansible/venv/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/XXX/Gitlab/ansible/venv/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0  

# /Users/XXX/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0 
```

##### STEPS TO REPRODUCE

You can use the following to see that helm diff doesn't pass the set values

```yaml
- name: Install Linkerd-control-plane chart
  kubernetes.core.helm:
    context: "{{ kubernetes_context }}"
    name: linkerd-control-plane
    chart_ref: linkerd-control-plane
    release_namespace: "{{ linkerd_namespace }}"
    chart_repo_url: https://helm.linkerd.io/stable
    chart_version: "{{ linkerd_control_plan_chart_version }}"
    wait: true
    wait_timeout: 300s
    set_values:
      # Trust anchor
      - value: "identity.issuer.scheme=kubernetes.io/tls"
        value_type: string
      - value: "identityTrustAnchorsPEM={{temp_dir.path}}/anchor-ca.crt"
        value_type: file
      # Webhook
      - value: "policyValidator.externalSecret=true"
        value_type: string
      - value: "policyValidator.caBundle={{temp_dir.path}}/webhook-ca.crt"
        value_type: file
      - value: "proxyInjector.externalSecret=true"
        value_type: string
      - value: "proxyInjector.caBundle={{temp_dir.path}}/webhook-ca.crt"
        value_type: file
      - value: "profileValidator.externalSecret=true"
        value_type: string
      - value: "profileValidator.caBundle={{temp_dir.path}}/webhook-ca.crt"
        value_type: file
    values: "{{ values_combined }}"
```

##### EXPECTED RESULTS

Being able to run a second time my playbook. The first deployment work since diff doesn't see the values.

##### ACTUAL RESULTS

```paste below
TASK [linkerd : Install Linkerd-control-plane chart] *****************************************************************************************
fatal: [XXX]: FAILED! => {"changed": false, "command": "/opt/homebrew/bin/helm diff upgrade linkerd-control-plane linkerd-control-plane --repo=https://helm.linkerd.io/stable --version=1.12.5 --reset-values -f=/var/folders/nj/_rfnr_wj13l5k7frc5bkfj_w0000gn/T/tmpqzl3msnd.yml", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: Failed to render chart: exit status 1: Error: execution error at (linkerd-control-plane/templates/identity.yaml:20:21): Please provide the identity issuer certificate\n\nUse --debug flag to render out invalid YAML\n\nError: plugin \"diff\" exited with error\n", "stderr": "Error: Failed to render chart: exit status 1: Error: execution error at (linkerd-control-plane/templates/identity.yaml:20:21): Please provide the identity issuer certificate\n\nUse --debug flag to render out invalid YAML\n\nError: plugin \"diff\" exited with error\n", "stderr_lines": ["Error: Failed to render chart: exit status 1: Error: execution error at (linkerd-control-plane/templates/identity.yaml:20:21): Please provide the identity issuer certificate", "", "Use --debug flag to render out invalid YAML", "", "Error: plugin \"diff\" exited with error"], "stdout": "", "stdout_lines": []}
```

##### WORKAROUND

Settings my values as `values` does work but I would still consider this a bug since `set_values` should be supported.
