### ISSUE TITLE
Kubernetes.core.helm 2.4.0 Kubernetes namespace not found

### ISSUE THREAD

**Issue by Guillaume-BVS** [ansible-collections/kubernetes.core#640]
##### SUMMARY
Hello :wave: 

I have upgraded my kubernetes.core version from 2.3.2 to 2.4.0 with 
```bash
ansible-galaxy collection install kubernetes.core
```
to use the set_values option in kubernetes.core.helm.

The problem is, now, when I try to run my ansible playbook to deploy my new Chart Helm version, ansible return an error:  my namespace isn't found. But my namespace exists and it doesn't have special restrictions.
```json
  "stdout": "Release \"my-project\" does not exist. Installing it now.\n",
  "stderr": "Error: create: failed to create: namespaces \"data\" not found\n",
  "command": "/bin/helm --version=1.0.0-22 --repo=https://my-repo.com/ upgrade -i --reset-values --wait --values=/opt/rke/dev/01-values.my-project.yml --values=/opt/rke/dev/99-values.override.yml -f=/tmp/tmptbkskwgx.yml my-project my-project",
  "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"data-analytic\" does not exist. Installing it now.\n\nstderr: Error: create: failed to create: namespaces \"data\" not found\n",
```
```bash
└─▶ kubectl get namespace
NAME                          STATUS   AGE
data                          Active   154d #<-----
default                       Active   321d
dev                           Active   321d
ingress-nginx                 Active   321d
kube-system                   Active   321d
local                         Active   320d
```

When I try to deploy on another environment with kubernetes.core version:2.3.2, I don't have this error. 

To complete my test, I rollbacked my version from 2.4.0 to 2.3.2 and retried the upgrade ; The problem disappeared. 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible version : 2.9.27
python version : 3.6.8
```

##### COLLECTION VERSION

```paste below
kubernetes.core 2.4.0
```

##### CONFIGURATION

```paste below
//
```

##### OS / ENVIRONMENT

RHEL 8

##### STEPS TO REPRODUCE

My Job :

```yaml
- name: "Deploy {{ my-project_chart_name }} chart {{ my-project_chart_version }}"
  kubernetes.core.helm:
    name: "{{ my-project_chart_name }}"
    chart_ref: "{{ my-project_chart_name }}"
    chart_version: "{{ my-project_chart_version }}"
    chart_repo_url: "{{my-repo}}"
    release_namespace: "data"
    values_files: "{{computed_files_list| sort}}"
    wait: true
```
Thanks for your help :smile:
