### ISSUE TITLE
kubernetes.core.helm failed with "no chart version found" even if the version is avalable.

### ISSUE THREAD

**Issue by Heniland** [ansible-collections/kubernetes.core#646]
##### SUMMARY
I tried to install `kube-prometheus-stack` with version `50.3.1` [here is a link to the chart](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack)

But Ansible is falling and complaining with 
```
Error: chart "kube-prometheus-stack" matching 50.3.1 not found in prometheus-community index. (try 'helm repo update'): no chart version found for kube-prometheus-stack-50.3.1
```

I did run `helm repo update`, and it is not helping. Plus, if I run the command manually, it works.
```
helm upgrade -i --reset-values --atomic --create-namespace prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --version 50.3.1 -f roles/shlomo/monitoring/files/values-prometheus-stack.yaml
```

Can someone help me out with what is going on?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.helm

##### ANSIBLE VERSION

```
ansible [core 2.15.0]
  config file = /code/infrastructure/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /code/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /code/.venv/bin/ansible
  python version = 3.9.10 (main, Mar  2 2022, 04:31:58) [GCC 10.2.1 20210110] (/code/.venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
kubernetes.core 2.4.0
```

##### CONFIGURATION

```
CONFIG_FILE() = /code/infrastructure/ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/code/infrastructure/ansible/ansible.cfg) = ['/code/infrastructure/ansible/plugins/>
DEFAULT_HOST_LIST(/code/infrastructure/ansible/ansible.cfg) = ['/code/infrastructure/ansible/inventories/sorte>
DEFAULT_ROLES_PATH(/code/infrastructure/ansible/ansible.cfg) = ['/root/.ansible/roles', '/code/infrastructure/>
DEFAULT_VAULT_PASSWORD_FILE(/code/infrastructure/ansible/ansible.cfg) = /root/.vault_pass
HOST_KEY_CHECKING(/code/infrastructure/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Running on Docker
```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

##### STEPS TO REPRODUCE

```yaml
- name: Add kube prometheus stack chart repo
  kubernetes.core.helm_repository:
    repo_name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install kube prometheus stack chart
  kubernetes.core.helm:
    atomic: true
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 50.3.1
    create_namespace: true
    release_namespace: monitoring
    # values: "{{ lookup('file', 'files/values-prometheus-stack.yaml') | from_yaml }}" # i includeded this for completnes but you can ignore this

```

##### EXPECTED RESULTS
helm should have installed the kube-prometheus-stack chart with specified version

##### ACTUAL RESULTS
Ansible failed to install the chart

```
fatal: [sx_master]: FAILED! => {
    "changed": false,
    "command": "/usr/sbin/helm --version=50.3.1 show chart prometheus-community/kube-prometheus-stack",
    "invocation": {
        "module_args": {
            "api_key": null,
            "atomic": true,
            "binary_path": null,
            "ca_cert": null,
            "chart_ref": "prometheus-community/kube-prometheus-stack",
            "chart_repo_url": null,
            "chart_version": "50.3.1",
            "context": null,
            "create_namespace": true,
            "dependency_update": false,
            "disable_hook": false,
            "force": false,
            "history_max": null,
            "host": null,
            "kubeconfig": null,
            "name": "prometheus",
            "post_renderer": null,
            "purge": true,
            "release_name": "prometheus",
            "release_namespace": "monitoring",
            "release_state": "present",
            "release_values": {},
            "replace": false,
            "set_values": null,
            "skip_crds": false,
            "timeout": null,
            "update_repo_cache": false,
            "validate_certs": true,
            "values_files": [],
            "wait": false,
            "wait_timeout": null
        }
    },
    "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: chart \"kube-prometheus-stack\" matching 50.3.1 not found in prometheus-community index. (try 'helm repo update'): no chart version found for kube-prometheus-stack-50.3.1\n",
    "stderr": "Error: chart \"kube-prometheus-stack\" matching 50.3.1 not found in prometheus-community index. (try 'helm repo update'): no chart version found for kube-prometheus-stack-50.3.1\n",
    "stderr_lines": [
        "Error: chart \"kube-prometheus-stack\" matching 50.3.1 not found in prometheus-community index. (try 'helm repo update'): no chart version found for kube-prometheus-stack-50.3.1"
    ],
    "stdout": "",
    "stdout_lines": []
}
```
