### ISSUE TITLE
 k8s_json_patch should not fail on op: remove

### ISSUE THREAD

**Issue by ppeereb1** [ansible-collections/kubernetes.core#648]
##### SUMMARY
This is my example configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2022-02-18T18:52:05Z
  name: game-config
  namespace: default
  resourceVersion: "516"
  uid: b4952dc3-d670-11e5-8cd0-68f728db1985
data:
  game.properties: |
    enemies=aliens
  ui.properties: |
    color.good=purple
```

I want to remove key data for example with task below:
```
- name: Remove key data from configmap
  kubernetes.core.k8s_json_patch:
    kind: ConfigMap
    api_version: v1
    name: game-config
    namespace: default
    patch:
      - op: remove
        path: /data/ui.properties
```

The first run succeeds, the second run fails:
```
  msg: 'Failed to patch existing object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server rejected our request due to an error in our request","reason":"Invalid","details":{},"code":422}\n'''
```

This is because the key no longer exists but it tries to remove the key anyways. It should be checked if the key exists before it is trying to remove the key.

A workaround is by retrieving the object info first and add a when statement to check if the key exists before removing it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 k8s_json_patch

##### ANSIBLE VERSION
```
ansible [core 2.15.3]
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection Name            Version
--------------------------- --------
community.general           7.2.0
kubernetes.core             2.4.0
```

##### OS / ENVIRONMENT
Ubuntu 22.04.3 LTS
