### ISSUE TITLE
Error msg when using kubernetes inventory

### ISSUE THREAD

**Issue by smutel** [ansible-collections/kubernetes.core#658]
##### SUMMARY

When I am using kubernetes inventory, I received this error message:
```
[WARNING]:  * Failed to parse /tmp/test/inventories/test/k8s.yml with ansible_collections.kubernetes.core.plugins.inventory.k8s plugin: 'AnsibleSequence' object has no attribute 'get'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible_collections.kubernetes.core.plugins.inventory.k8s

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.6]
  config file = /tmp/test/ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/.local/share/virtualenvs/test-hxkKlP5o/lib/python3.10/site-packages/ansible
  ansible collection location = /home/test/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/test/.local/share/virtualenvs/test-hxkKlP5o/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/test/.local/share/virtualenvs/test-hxkKlP5o/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
kubernetes.core 2.4.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /tmp/test/ansible.cfg
DEFAULT_BECOME(/tmp/test/ansible.cfg) = True
DEFAULT_FORKS(/tmp/test/ansible.cfg) = 30
DEFAULT_GATHERING(/tmp/test/ansible.cfg) = explicit
DISPLAY_SKIPPED_HOSTS(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = True
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/tmp/test/ansible.cfg) = False
INVENTORY_ENABLED(/tmp/test/ansible.cfg) = ['kubernetes.core.k8s']
```

##### OS / ENVIRONMENT

* Ubuntu 22.04.3 LTS
* Ansible inventory (inventories/test/k8s.yml):
```yaml
- name: Test                                                                                        
  plugin: kubernetes.core.k8s                                                                       
  connections:                                                                                      
    - name: Test                                                                                    
      kubeconfig: /home/test/.kube/default                                                        
      namespaces:                                                                                   
        - default
```
* Ansible.cfg:
```ini
[defaults]
host_key_checking = False
forks = 30
gathering = explicit

[inventory]
enable_plugins = kubernetes.core.k8s

[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null

[privilege_escalation]
become = yes
```

##### STEPS TO REPRODUCE

ansible-inventory --list -i inventories/test

##### EXPECTED RESULTS

Inventory displayed

##### ACTUAL RESULTS

```paste below
[WARNING]:  * Failed to parse /tmp/test/inventories/test/k8s.yml with ansible_collections.kubernetes.core.plugins.inventory.k8s plugin: 'AnsibleSequence' object has no attribute 'get'
[WARNING]: Unable to parse /tmp/test/inventories/test/k8s.yml as an inventory source
[WARNING]: Unable to parse /tmp/test/inventories/test as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

**Comment by beeankha** [comment]
Hi @smutel , thank you so much for filing this issue!

The error that you're seeing indicates that your example `inventories/test/k8s.yml` file has an invalid structure; Ansible inventory files require their contents to be in a dictionary format. Editing the inventory file like the following made the error go away for me:

```
---
plugin: kubernetes.core.k8s
connections:
  - name: Test
    kubeconfig: ~/.kube/config
    namespaces:
      - default
```

Please note that the inventory plugin is [slated for deprecation in `6.0.0`](https://github.com/ansible-collections/kubernetes.core/blob/b648f45e909b566aeabb24b6f40ad2aa360777f0/plugins/inventory/k8s.py#L22-L27). The following issues contain some details related to this planned deprecation:
- https://github.com/ansible-collections/kubernetes.core/issues/31
- https://github.com/ansible-collections/kubernetes.core/issues/570

I'm going to go ahead and close out this issue; if you have any further questions, please feel free to re-open it!
