### ISSUE TITLE
Ability to wait on arbitrary status value

### ISSUE THREAD

**Issue by dannystaple** [ansible-collections/kubernetes.core#66]
##### SUMMARY

Not all k8s resources implement the conditions in their status. However it may still be necessary to wait on them being ready. Since operations in K8s are asynchronous, an item later depending on this may fail.

A good example is the kind Service. This does not implement conditions as shown in https://github.com/kubernetes/kubernetes/issues/80828. My ansible may need to wait for this service to have acquired an External IP address before using in a further task - perhaps feeding that IP into a network infrastructure rule (firewall, DNS or other). 

A similar ticket exists for the Kubectl command - https://github.com/kubernetes/kubernetes/issues/83094 - waiting for an arbitrary json path.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

module k8s

##### ADDITIONAL INFORMATION

```yaml
- name: Deploy the dashboard service (lb)
  community.kubernetes.k8s:
    <<: *k8s_auth
    template: dash-service.yaml
    wait: yes
    wait_for: .status.loadBalancer.ingress[*].ip
```

Something like that could be waiting for an ingress IP to appear. Perhaps inspiration could come from https://github.com/kubernetes/kubernetes/issues/83094#issuecomment-715975514.
