### ISSUE TITLE
Weird bug with ingress-nginx installation with helm

### ISSUE THREAD

**Issue by lderugeriis** [ansible-collections/kubernetes.core#661]
##### SUMMARY
When using ansible to install ingress-nginx with helm chart some values don't get applied. If running the command produced by ansible manually everything works. This is happening even when using the shell module instead of helm module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
helm

##### ANSIBLE VERSION

```
ansible [core 2.15.0]
  config file = /Users/luca/.ansible.cfg
  configured module search path = ['/Users/luca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/luca/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 00:34:59) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.0.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
❯ ansible-galaxy collection list community.general

# /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.0.1

❯ ansible-galaxy collection list kubernetes.core

# /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0 
```

##### CONFIGURATION

```
COLLECTIONS_PATHS(/Users/luca/.ansible.cfg) = ['/Users/luca/.ansible/collections', '/usr/share/ansible/collections']
CONFIG_FILE() = /Users/luca/.ansible.cfg
DEFAULT_HOST_LIST(/Users/luca/.ansible.cfg) = ['/Users/luca/.ansible_hosts']
DEFAULT_REMOTE_USER(/Users/luca/.ansible.cfg) = root
HOST_KEY_CHECKING(/Users/luca/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Task runs on localhost wich is an Apple Silicon Mac

##### STEPS TO REPRODUCE

Trying to install a second ingress controller with values as per https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#how-can-i-easily-install-multiple-instances-of-the-ingress-nginx-controller-in-the-same-cluster

```
    - name: ingress-nginx external | Install ingress-nginx
      kubernetes.core.helm:
        name: ingress-nginx-external
        chart_ref: ingress-nginx
        chart_repo_url: https://kubernetes.github.io/ingress-nginx
        release_namespace: ingress-nginx-external
        create_namespace: true
        set_values:
        - value: controller.ingressClassResource.name=nginx-external
        - value: controller.ingressClass=nginx-external
        - value: controller.ingressClassResource.controllerValue="k8s.io/ingress-nginx-external"
        - value: controller.ingressClassResource.enabled=true
        - value: controller.ingressClassByName=true
```
##### EXPECTED RESULTS
To have a deployment with parameters like below:

```
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --publish-service=$(POD_NAMESPACE)/ingress-nginx-external-controller
        - --election-id=ingress-nginx-external-leader
        - --controller-class=k8s.io/ingress-nginx-external
        - --ingress-class=nginx-external
        - --configmap=$(POD_NAMESPACE)/ingress-nginx-external-controller
        - --validating-webhook=:8443
        - --validating-webhook-certificate=/usr/local/certificates/cert
        - --validating-webhook-key=/usr/local/certificates/key
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
```

##### ACTUAL RESULTS
Instead the deployment has the wrong (default?) --election-id parameter
```
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --publish-service=$(POD_NAMESPACE)/ingress-nginx-external-controller
        - --election-id=ingress-nginx-leader
        - --controller-class=k8s.io/ingress-nginx-external
        - --ingress-class=nginx-external
        - --configmap=$(POD_NAMESPACE)/ingress-nginx-external-controller
        - --validating-webhook=:8443
        - --validating-webhook-certificate=/usr/local/certificates/cert
        - --validating-webhook-key=/usr/local/certificates/key
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
```

This is the command produced by the helm module
```
/opt/homebrew/bin/helm --repo=https://kubernetes.github.io/ingress-nginx upgrade -i --reset-values --create-namespace --set controller.ingressClassResource.name=nginx-external --set controller.ingressClass=nginx-external --set controller.ingressClassResource.controllerValue=\"k8s.io/ingress-nginx-external\" --set controller.ingressClassResource.enabled=true --set controller.ingressClassByName=true ingress-nginx-external ingress-nginx
```
but even running a shell module like this
```
 "cmd": "helm install ingress-nginx-external ingress-nginx/ingress-nginx  --namespace ingress-nginx-external --set controller.ingressClassResource.name=nginx-external --set controller.ingressClass=nginx-external --set controller.ingressClassResource.controllerValue=\"k8s.io/ingress-nginx-external\" --set controller.ingressClassResource.enabled=true --set controller.ingressClassByName=true\n",
```
produces the same wrong election-id parameters.

Running those commands on the command line without ansible yelds the correct results.

Thanks.

**Comment by gravesm** [comment]
I just ran the following playbook:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - kubernetes.core.helm:
        name: ingress-nginx-external
        chart_ref: ingress-nginx
        chart_repo_url: https://kubernetes.github.io/ingress-nginx
        release_namespace: ingress-nginx-external
        create_namespace: true
        set_values:
          - value: controller.ingressClassResource.name=nginx-external
          - value: controller.ingressClass=nginx-external
          - value: controller.ingressClassResource.controllerValue="k8s.io/ingress-nginx-external"
          - value: controller.ingressClassResource.enabled=true
          - value: controller.ingressClassByName=true

    - kubernetes.core.k8s_info:
        kind: Deployment
        api_version: apps/v1
        namespace: ingress-nginx-external
      register: result

    - debug:
        msg: "{{ result.resources[0].spec.template.spec.containers[0].args }}"
```
and got the following output:
```
PLAY [localhost] *****************************************************************************************************************

TASK [kubernetes.core.helm] ******************************************************************************************************
changed: [localhost]

TASK [kubernetes.core.k8s_info] **************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "/nginx-ingress-controller",
        "--publish-service=$(POD_NAMESPACE)/ingress-nginx-external-controller",
        "--election-id=ingress-nginx-external-leader",
        "--controller-class=k8s.io/ingress-nginx-external",
        "--ingress-class=nginx-external",
        "--configmap=$(POD_NAMESPACE)/ingress-nginx-external-controller",
        "--validating-webhook=:8443",
        "--validating-webhook-certificate=/usr/local/certificates/cert",
        "--validating-webhook-key=/usr/local/certificates/key",
        "--ingress-class-by-name=true"
    ]
}

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
This seems to be the output you are expecting. The fact that it's not working even if you run a shell command in Ansible suggests the problem is not with this collection. I'm not sure what to suggest as I can't reproduce this.
