### ISSUE TITLE
Installed Helm diff plugin may break deploy

### ISSUE THREAD

**Issue by psmolkin** [ansible-collections/kubernetes.core#669]
##### SUMMARY
When you have the Helm Diff plugin installed, the `kubernetes.core.helm` module run the `diff ` command before deploy. But, the command line generation logic works different and put generated yaml of a `[release_]values` dict to the first place before `values_files`, that means that these generated values become hidden.

This is quite similar to the https://github.com/ansible-collections/kubernetes.core/issues/638 issue.
I'm going to raise a PR.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.helm

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.11]
```

##### COLLECTION VERSION

```paste below
kubernetes.core 3.0.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

doesn't matter

##### STEPS TO REPRODUCE

```yaml
 kubernetes.core.helm:
    atomic: true
    name: "{{ helm_release_name }}"
    chart_ref: "{{ playbook_dir + '/../helm/my_app/' }}"
    namespace: "{{ namespace }}"
    wait: true
    state: present
    force: true
    values_files: "{{ values_files | select | list }}"
    release_values:
      region: "hidden_one"
  vars:
    values_files:
      - "{{ playbook_dir }}/../helm/my_app/values-commons.yaml"
```
where `values-commons.yaml` is:
```yaml
region: default
```

##### EXPECTED RESULTS

The result `region:` value rendered to `hidden_one`

##### ACTUAL RESULTS

The result `region` value for `helm diff upgrade` will be `default` instead of `hidden_one`
