### ISSUE TITLE
How can I use kubernetes.core.kubectl connection to connect to the Supervisor of a VMware TKG cluster?

### ISSUE THREAD

**Issue by mbx64** [ansible-collections/kubernetes.core#673]
##### SUMMARY

When [connecting to the Supervisor of a VMware TKG cluster](https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-with-tanzu-installation-configuration/GUID-F5114388-1838-4B3B-8A8D-4AE17F33526A.html), you have to use the following command manually:

    kubectl vsphere login --server=<KUBERNETES-CONTROL-PLANE-IP-ADDRESS> --vsphere-username <VCENTER-SSO-USER>

After that, I have a kubeconfig file with which I can connect to my cluster with the modules of this collection. But is there a way I can pass arguments to the kubernetes.core.kubectl connection module, so that I can directly connect to my cluster, without executing `kubectl vsphere login` beforehand?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

kubectl

##### ANSIBLE VERSION

```paste below
nsible [core 2.15.8]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.9.17 (main, Aug 10 2023, 15:11:31) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

**Comment by gravesm** [comment]
This is not something the connection plugin supports.

**Comment by yurnov** [comment]
Hi @mbx64, did you try to do something like:

```
---
- hosts: localhost connection=local 
  gather_facts: no
  tasks: 
  - name: login to VMware TKG cluster
    ansible.builtin.shell: "kubectl vsphere login --server={{ vcenter-address }}  --vsphere-username {{ VCENTER-SSO-USER }}"

- hosts: localhost
  gather_facts: no
  gather_facts: no
  any_errors_fatal: yes
  vars:
    ansible_connection: "kubernetes.core.kubectl"
    ansible_kubectl_namespace: "test"
    ansible_kubectl_config: "{{ ansible_user_dir }}/.kube/config"
....
```
