### ISSUE TITLE
k8s_info - async is not supported for this task.

### ISSUE THREAD

**Issue by wmlynch** [ansible-collections/kubernetes.core#678]
##### SUMMARY

I see differences between indirect and direct references to k8s_info and the async task option.  I don't know if this a bug or working as designed.   Or if this a builtin redirect isssue?

This works...  
```
  - name: built-in redirect example (works)
    k8s_info:
   ...
    async: "120"
    poll: "1"
````
This doesn't work...
```
 - name: direct example (doesn't work)
    kubernetes.core.k8s_info:
   ...
    async: "120"
    poll: "1"
 ```
and fails with 
```
task path: /root/molecule/async-recreate.yml:25
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [localhost]: FAILED! => {"changed": false, "msg": "async is not supported for this task."}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes.core.k8s_info

##### ANSIBLE VERSION

```
ansible --version
ansible [core 2.14.14]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.venv/bin/ansible
  python version = 3.9.17 (main, Jun 13 2023, 16:05:09) [GCC 8.3.0] (/root/.venv/bin/python)
  jinja version = 3.1.3
  libyaml = True

```

##### COLLECTION VERSION

```ansible-galaxy collection list kubernetes.core
ansible-galaxy [core 2.14.14]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.venv/bin/ansible-galaxy
  python version = 3.9.17 (main, Jun 13 2023, 16:05:09) [GCC 8.3.0] (/root/.venv/bin/python)
  jinja version = 3.1.3
  libyaml = True
No config file found; using defaults

# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 3.0.0  

```

##### CONFIGURATION

```ansible-config dump --only-changed
ansible-config [core 2.14.14]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.venv/bin/ansible-config
  python version = 3.9.17 (main, Jun 13 2023, 16:05:09) [GCC 8.3.0] (/root/.venv/bin/python)
  jinja version = 3.1.3
  libyaml = True
No config file found; using defaults
CONFIG_FILE() = None
DEFAULT_VERBOSITY(env: ANSIBLE_VERBOSITY) = 2

```

##### OS / ENVIRONMENT

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### STEPS TO REPRODUCE

1.  export a KUBECONFIG of a kubernetes cluster
2. run `ansible-playbook async-recreate.yml`

async-crecreate.yml playbook
```
---
- name: Show the differences between direct and indirect
  hosts: localhost
  become: no
  tasks:
  - name: built-in redirect example (works)
    k8s_info:
      api_version: v1
      kind: Pod
      namespace: default
    register: _indirect_k8s_info
    until: _indirect_k8s_info is successful
    delay: "15"
    retries: "10"
    async: "120"
    poll: "1"

  - name: direct example (doesn't work)
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Pod
      namespace: default
    register: _direct_k8s_info
    until: _direct_k8s_info is successful
    delay: "15"
    retries: "10"
    async: "120"
    poll: "1"
```

##### EXPECTED RESULTS

```
See TASK [built-in redirect example (works)]  below
```

##### ACTUAL RESULTS

``` ansible-playbook async-recreate.yml 
ansible-playbook [core 2.14.14]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.venv/bin/ansible-playbook
  python version = 3.9.17 (main, Jun 13 2023, 16:05:09) [GCC 8.3.0] (/root/.venv/bin/python)
  jinja version = 3.1.3
  libyaml = True
No config file found; using defaults
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
redirecting (type: modules) ansible.builtin.k8s_info to kubernetes.core.k8s_info
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: async-recreate.yml ***************************************************************************************************************************************************************************************
1 plays in async-recreate.yml

PLAY [Show the differences between direct and indirect] ************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************
task path: /root/molecule/async-recreate.yml:2
ok: [localhost]

TASK [built-in redirect example (works)] ***************************************************************************************************************************************************************************
task path: /root/molecule/async-recreate.yml:6
redirecting (type: modules) ansible.builtin.k8s_info to kubernetes.core.k8s_info
redirecting (type: modules) ansible.builtin.k8s_info to kubernetes.core.k8s_info
ASYNC OK on localhost: jid=j996967061524.31767
ok: [localhost] => {"ansible_job_id": "j996967061524.31767", "api_found": true, "attempts": 1, "changed": false, "finished": 1, "resources": [], "results_file": "/root/.ansible_async/j996967061524.31767", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [direct example (doesn't work)] *******************************************************************************************************************************************************************************
task path: /root/molecule/async-recreate.yml:18
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [localhost]: FAILED! => {"changed": false, "msg": "async is not supported for this task."}

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  

```

**Comment by shubhamsugara22** [comment]
This behavior stems from how Ansible handles async with action plugins. kubernetes.core.k8s_info has an associated action plugin (plugins/action/k8s_info.py), and Ansible disallows async for action plugins by default unless the plugin explicitly declares support for it.

When using the short name k8s_info:, Ansible resolves it through the ansible.builtin.k8s_info redirect, which bypasses or re-routes the action plugin lookup in a way that async gets permitted. Using the FQCN kubernetes.core.k8s_info: directly hits the action plugin, which lacks the _supports_async = True flag.

**Comment by yurnov** [comment]
Triage note — re-checked against `main` @ `e475d06` (7.0.0-dev0).

This is an ansible-core limitation rather than something this collection can fix.

`k8s_info` ships an action plugin (`plugins/action/k8s_info.py`), and ansible-core's
`ActionBase._supports_async` defaults to `False` — core raises when `self._task.async_val` is
set on a plugin that hasn't opted in. `git grep supports_async -- plugins/` returns nothing on
`main`.

The asymmetry in the report is the giveaway: the short-name `k8s_info:` form resolved to
something that didn't route through the collection's action plugin, while the FQCN form does.

It's not specific to this collection either — ansible-core's own `copy` action plugin has the
same constraint, so there's no established pattern for opting a plugin of this shape into
async.

**Suggest closing** as a known limitation, ideally with a one-line note in the module docs so
the next person doesn't have to rediscover it. PR #630 exists if anyone does want to pursue
real async support, but it's a non-trivial rework rather than a flag flip.

For parallelism today, running the tasks across hosts with forks, or `loop` + `throttle`,
achieves most of what `async` would here.

---
_Part of a sweep over all 91 open issues; index in #1215. Happy to see this reopened if it can still be reproduced on a current release._

**Comment by xSuiteHaroonButt** [comment]
Thanks for the suggestion.

I do not see how using `forks` or `loop` + `throttle` would solve this use case, or provide an equivalent workaround.

As an example in my restore role, all restore operations are delegated to the same Kubernetes master and run with `run_once`. The long-running commands are executed through `kubernetes.core.k8s_exec` ( which has the patch mentioned in #630 applied to it ), for example `rsync` and `mongorestore`, using:

```yaml
    - name: mongodb restore - run mongorestore
      kubernetes.core.k8s_exec:
        namespace: mongodb
        pod: mongo-restore
        container: mongo-restore
        command: su - mongodb -s /bin/sh -c "mongorestore --numInsertionWorkersPerCollection 8 --host {{ mongodb_primary['stdout_lines'][0] }} --username {{ mongodb_rs0_credentials.username }} --password {{ mongodb_rs0_credentials.password }} --authenticationDatabase admin /mongo"
      async: 86400
      poll: 0
      register: mongodb_restore_job
```

This allows the command to continue remotely while Ansible immediately starts the other independent restore operations. The role collects all returned job IDs and waits for them later with `async_status`.

As I understand it:

- `forks` provides concurrency across different Ansible hosts.
- `throttle` limits concurrency across hosts.
- A normal Ansible `loop` executes its iterations sequentially and waits for each iteration to finish before starting the next one.

Since these restore tasks are delegated to one host and use `run_once`, increasing forks would not distribute the work. `loop` + `throttle` would also not allow the restore commands to run concurrently; Ansible would still wait for each loop item to complete before starting the next one.

Therefore, replacing `async` with forks or `loop` + `throttle` would require redesigning my workflow ( which might be the proper approach for my case ), for example by creating separate Kubernetes `Job` resources and monitoring them. It would not be a general workaround for the current `k8s_exec` async requirement.

Please let me know if I am misunderstanding how `loop` + `throttle` is expected to provide parallel execution on a single delegated host.
