### ISSUE TITLE
Inventory plugin should prefix groups with cluster name  (bug?!)

### ISSUE THREAD

**Issue by ieugen** [ansible-collections/kubernetes.core#69]
##### SUMMARY
Hello,

I'm using the inventory plugin with two clusters (one for prod and one for dev) and I've noticed that it merges the groups from both clusters and I get the following warning:

```
[WARNING]: Found both group and host with same name: k2
[WARNING]: Found both group and host with same name: k1
```

On a second note, I believe there are cases where multiple configurations files for this plugin make sense.
One can generate the files.
In this case working with a single file is not easy. 

##### COMPONENT NAME

The inventory plugin handles this.

##### ADDITIONAL INFORMATION

My inventory plugin config `k8s.yml` .
```yaml
# Use a custom config file, and a specific context.
plugin: kubernetes.core.k8s
connections:
  - name: k1
    kubeconfig: secrets/k1.cluster-access.yml
    context: default
  - name: k2
    kubeconfig: secrets/k1.cluster-access.yml
    context: default
```

**Comment by Akasurde** [comment]
@ieugen Thanks for reporting this issue.

**Comment by abikouo** [comment]
@ieugen I did not managed to reproduce the issue, could you please clarify.
Details here on my testing environment

```
---
plugin: kubernetes.core.k8s
connections:
  - name: kube0
    kubeconfig: /k8s/kube0.config
    namespaces:
      - dev
  - name: kube1
    kubeconfig: /k8s/kube1.config
    namespaces:
      - dev
```
using ``kubectl`` I can validate that there are running pods

```
kubectl get pods -n dev --kubeconfig=kube1.config 
NAME    READY   STATUS    RESTARTS   AGE
kube1   1/1     Running   0          26m

kubectl get pods -n dev --kubeconfig=kube0.config 
NAME    READY   STATUS    RESTARTS   AGE
kube0   1/1     Running   0          26m
```

then running ``ansible-inventory -i inventory.yaml --list`` I got the following output

```
{
    "_meta": {
        "hostvars": {
            "kube0_kube0": {  ## Hosts are prefixed with the cluster name
                "annotations": {},
                "ansible_connection": "kubernetes.core.kubectl",
                "ansible_kubectl_container": "kube0",
                "ansible_kubectl_namespace": "dev",
                "ansible_kubectl_pod": "kube0",
                "ansible_remote_tmp": "/tmp/",
                (...)
            },
            "kube1_kube1": { ## Hosts are prefixed with the cluster name
                "annotations": {},
                "ansible_connection": "kubernetes.core.kubectl",
                "ansible_kubectl_container": "kube1",
                "ansible_kubectl_namespace": "dev",
                "ansible_kubectl_pod": "kube1",
                "ansible_remote_tmp": "/tmp/",
                (...)
            }
        }
    },
    "all": {
        "children": [
            "kube0",
            "kube1",
            "ungrouped"
        ]
    },
    "kube0": { ## one group per cluster
        "children": [
            "namespace_dev"
        ]
    },
    "kube1": {
        "children": [
            "namespace_dev"
        ]
    },
    "namespace_dev": {  ## Is this group you expected to be prefixed with the cluster name ??
        "children": [
            "namespace_dev_pods",
            "namespace_dev_services"
        ]
    },
    "namespace_dev_pods": {
        "hosts": [
            "kube0_kube0",
            "kube1_kube1"
        ]
    }
}
```
