### ISSUE TITLE
How can I set node labels? 

### ISSUE THREAD

**Issue by ieugen** [ansible-collections/kubernetes.core#72]
##### SUMMARY

I would like to set node lables in a kubernetes cluster.
(I'm writing this as I have not seen a way to do it via ansible right now) 

I need node labels because cloud nodes have access to cloud volumes while dedicated nodes don't have.
I need to be able to deploy pods based on labels to these nodes.

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
I would like to be able to use an ansible task to set node labels for a bunch of nodes in my inventory.
Ideally the labels would be set via a list/array variable. 

Because of how the kubernetes API works I believe ansible should expose two modules:
- one for adding node labels
- one for removing node labels

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#step-one-attach-label-to-the-node

```yaml

hosts:
   worker1:
     - k8s_add_labels:
        - label1=value1
        - label2=value2
     - k8s_remove_labels:
        -  label3
        # Remove label4 only if it has value4 ?! 
        - label4=value4
```

**Comment by ieugen** [comment]
I have found a solution with shell execution:
```
- name: Set add node labels
  ansible.builtin.command: kubectl --kubeconfig={{ kubeconfig_path }} label node --overwrite {{ inventory_hostname }} {{ item }}
  delegate_to: localhost
  loop: "{{ k8s_add_node_labels }}"
  when: k8s_add_node_labels is defined

- name: Set remove node labels
  ansible.builtin.command: kubectl --kubeconfig={{ kubeconfig_path }} label node {{ inventory_hostname }} {{ item }}-
  delegate_to: localhost
  loop: "{{ k8s_remove_node_labels }}"
  when: k8s_remove_node_labels is defined
```

**Comment by Akasurde** [comment]
@ieugen Do you think we can close this issue since the above solution works for you?

**Comment by gravesm** [comment]
@ieugen You can use the k8s module to manage labels on nodes:

```
- kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ node_name }}"
        labels:
          foo: baz
```
