### ISSUE TITLE
Question, can I use template language on a whole line?

### ISSUE THREAD

**Issue by Evantage-WS** [ansible-collections/kubernetes.core#721]
Hi,

I am using ansible to deploy a Helm chart, can I use the templating to achieve an empty line or a complete line?

```
              annotations:
                "{{ extra_annotations }}"
```
In some cases the extra annotations must be 
```
              annotations:
                 cert-manager.io/cluster-issuer: letsencrypt-prod
```

In other cases a complete empty line, like:
```
              annotations:
```

Can this be achieved without creating extra files?

I am trying to use a variable on a whole line, but I do get: Expected: object, given: string

Thanks!

**Comment by yurnov** [comment]
sure, you may have something like:
```
  - set_facts:
      additional_values: 
         annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
    when: something
  - name: Deploy my Helm chart
    kubernetes.core.helm:
      kubeconfig: "{{ kubeconfig }}"
      namespace: "{{ namespace }}"
      name: "{{ chart_name }}"
      chart_ref: "{{ chart_name }}/{{ chart_release }}"
      chart_version: "{{ chart_version }}"
      timeout: 60m
      values: "{{ some_base_values | combine(additional_values|default(''), recursive=true) }}"
```
