### ISSUE TITLE
Isn't possible delete pods using label_selectors 

### ISSUE THREAD

**Issue by monique77** [ansible-collections/kubernetes.core#742]
Hello guys,

I would like help to delete all pods in specific label in my K8s. I can do it when I use namespace, but the parameter label_selectors doesn't work.
I will appreciate your help, because I didn't found any information in ansible documentation when we use label_selectors to get only labels and execute delete on pods.

My versions app:
ansible==9.6.0
ansible-core==2.16.7
kubernetes==29.0.0
openshift==0.13.2

My task ansible

    - name: Delete all pods in specific label in my K8s
      kubernetes.core.k8s:
        state: absent 
        api_version: v1 
        kind: pod
        label_selectors:
        - "app=monitoring"
        name: "{{ item }}"
      loop: "{{ pod_list | json_query('resources[*].metadata.name') }}"

The return message:
ok: [localhost] => (item=my-app-server-74b8b789c8-cbbg4) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "v1",
            "append_hash": false,
            "apply": false,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": null,
            "continue_on_error": false,
            "delete_options": null,
            "force": false,
            "generate_name": null,
            "host": null,
            "impersonate_groups": null,
            "impersonate_user": null,
            "kind": "pod",
            "kubeconfig": null,
            "label_selectors": [
                "app=monitoring"
            ],
            "merge_type": null,
            "name": "my-app-server-74b8b789c8-cbbg4",
            "namespace": null,
            "no_proxy": null,
            "password": null,
            "persist_config": null,
            "proxy": null,
            "proxy_headers": null,
            "resource_definition": null,
            "server_side_apply": null,
            "src": null,
            "state": "absent",
            "template": null,
            "username": null,
            "validate": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "item": "my-app-server-74b8b789c8-cbbg4",
    "method": "delete",
    "result": {}
}

PLAY RECAP *******************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by yurnov** [comment]
Hi @monique77,

to answer your question it is better to know how you get your `pod_list` or what is inside that list.

**Comment by monique77** [comment]
@yurnov tks for your message. So,  in my pod_list there are all pods that have label named monitoring. If I change to namepace it works, but if I use label doesn't work.

**Comment by yurnov** [comment]
@monique77 

you can try something like:

```
---
- hosts: localhost
  gather_facts: no
  vars:
    kubeconfig: /root/.kube/config
    my_app: "app=monitoring"
  tasks:
    - name: Get My App pod info based on label
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        # namespace: "{{ namespace }}"
        kind: Pod
        label_selectors: "{{ my_app}}"
      register: my_app_pod

    - set_fact:
        namespace_list: "{{ my_app_pod | json_query('resources[*].metadata.namespace') | unique}}"
        pod_list: "{{ my_app_pod | json_query('resources[*].metadata.name') }}"

    - name: Delete all pods in specific label in my K8s
      kubernetes.core.k8s:
        state: absent 
        api_version: v1 
        kind: pod
        label_selectors: "{{ my_app }}"
        namespace: "{{ item.0 }}"
        name: "{{ item.1 }}"
      with_nested:
        - "{{ namespace_list }}"
        - "{{ pod_list }}"
```
