### ISSUE TITLE
Kubernetes version v1.2X is not supported by kubernetes-validate

### ISSUE THREAD

**Issue by gr33npr** [ansible-collections/kubernetes.core#768]
##### SUMMARY
we have OpenShift Server Version: 4.15.19 with Kubernetes Version v1.28.10+a2c84a5. Running an ansible task with validate-option, the following error appears:

Kubernetes version v1.28.10+a2c84a5 is not supported by kubernetes-validate"

Its possible to set the version manually. 1.27 works, but 1.28 and higher not.

`  kubernetes.core.k8s:
    validate:
      fail_on_error: true
      version: 1.27
`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Option/parameter "validate" of module kubernetes.core.k8s

##### ANSIBLE VERSION

```
ansible [core 2.14.14]
  config file = /home/gruens/.ansible.cfg
  configured module search path = ['/home/gruens/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/gruens/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, May 16 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3.0.1)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection      Version
--------------- -------
kubernetes.core 5.0.0
```

##### CONFIGURATION

```
CONFIG_FILE() = /home/user/.ansible.cfg
DEFAULT_VAULT_PASSWORD_FILE(/home/user/.ansible.cfg) = /home/user/.vaultpw
```

##### OS / ENVIRONMENT

Local:
Red Hat Enterprise Linux release 9.4 (Plow)

Remote:
Red Hat Enterprise Linux release 8.10 (Ootpa)

##### STEPS TO REPRODUCE

1. Install OpenShift > 4.15 (probably K8s > 1.28 also works)
2. Create Ansible-Task (collection kubernetes.core must be present)
e.g.: Create Secret in default namespace

```yaml
kubernetes.core.k8s:
    validate:
      fail_on_error: true
    wait: true
    wait_timeout: 60
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: test
        namespace: "default"
      type: Opaque
      data:
        bindPassword: "{{ oleole | b64encode }}"

```

##### EXPECTED RESULTS

successful task

##### ACTUAL RESULTS

Kubernetes version v1.28.10+a2c84a5 is not supported by kubernetes-validate"

```paste below

```
