### ISSUE TITLE
Support proxy configuration for lookup/query

### ISSUE THREAD

**Issue by vflaux** [ansible-collections/kubernetes.core#775]
##### SUMMARY

Support all proxy settings available in kubernetes.core.k8s & kubernetes.core.k8s_info modules in the kubernetes.core.k8s lookup.

Parameters : no_proxy, proxy, proxy_headers
Environment variables: K8S_AUTH_NO_PROXY, K8S_AUTH_PROXY, K8S_AUTH_PROXY_HEADERS_BASIC_AUTH, K8S_AUTH_PROXY_HEADERS_PROXY_BASIC_AUTH, K8S_AUTH_PROXY_HEADERS_USER_AGENT 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

kubernetes.core.k8s lookup

##### ADDITIONAL INFORMATION

We need to pass through a proxy to access our kubernetes clusters and we define the K8S_AUTH_PROXY environement variable.
As it is not supported by the lookup we cannot use lookup/query and have to use kubernetes.core.k8s_info module and register the returned values.

```yaml
- name: Fetch a list of namespaces
  set_fact:
    projects: "{{ query('kubernetes.core.k8s', api_version='v1', kind='Namespace') }}"
```
