### ISSUE TITLE
kubernetes.core.k8s_cp intermittently copying incomplete files to pod

### ISSUE THREAD

**Issue by danfinn** [ansible-collections/kubernetes.core#776]
##### SUMMARY
Occasionally I've noticed that when using the kubernetes.core.k8s_cp module the file that gets copied is not complete.  This isn't happening all the time but it is causing issues for us.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s_cp

##### ANSIBLE VERSION
quay.io/ansible/ansible-builder:latest

##### STEPS TO REPRODUCE
```
 - name: Copy metricbeat index template to elasticsearch master pod
   kubernetes.core.k8s_cp:
     kubeconfig: "{{ context_file }}"
     context: "{{ aks_name }}"
     namespace: "{{ namespace }}"
     pod: "{{ prefix_type }}-elasticsearch-master-0"
     container: "{{ prefix_type }}-elasticsearch"
     local_path: "{{ role_path }}/files/metricbeat_template.json"
     remote_path: /tmp/metricbeat_template.json
   no_log: "{{ no_log }}"
```

##### EXPECTED RESULTS
file to be copied in it's entirety

##### ACTUAL RESULTS
source file:
```
wc -l metricbeat_template.json
35766 metricbeat_template.json
```

file on pod after running above ansible task:
```
wc -l /tmp/metricbeat_template.json
35225 /tmp/metricbeat_template.json
```

this doesn't happen every time but I've caught this happening twice now.

re-running the playbook results in the file being copied in it's entirety (from the pod):
```
wc -l /tmp/metricbeat_template.json
35766 /tmp/metricbeat_template.json
```
