### ISSUE TITLE
kubernetes.core.kustomize lookup: support http proxy

### ISSUE THREAD

**Issue by bh-tt** [ansible-collections/kubernetes.core#783]
##### SUMMARY

Kubernetes.core.kustomize lookup does not allow setting a HTTP proxy. This means we cannot use it to run kustomize with remote (e.g. github) bases/resources, since our ansible controller is on a system without direct access to the internet.  I'd like to add a `proxy` (or maybe `http_proxy`) setting to the plugin to allow setting the proxy for use with this lookup.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

kubernetes.core.kustomize

##### ADDITIONAL INFORMATION

It allows ansible controllers behind a http proxy to access remote kustomize bases/resources. I've looked at several alternatives:
 - using the `pipe` plugin, as that allows setting the HTTPS_PROXY variable, but that is not really usable as the PWD of the lookup becomes the playbook file, whereas most of our lookups will happen in roles
 - simply using `ansible.builtin.command`, but again that results in PWD issues
 - adding a reverse proxy (say github.example.com) to our infrastructure and directing the calls there, but that seems needlessly complicated

```yaml
- name: kustomize
   ansible.builtin.set_fact:
      resources: "{{ lookup('kubernetes.core.kustomize', dir='../files/', proxy='http://proxy') }}"
```

**Comment by yurnov** [comment]
Hi @bh-tt,

Lookup plugin `kubernetes.core.kustomize` (please take a look to [the code](https://github.com/ansible-collections/kubernetes.core/blob/main/plugins/lookup/kustomize.py)) is a ansible-wrapper on the `kubectl` or `kustomize` binary, so, as proxy is not supported by the `kubectl` is can't be added (at least to be easily added) to `kubernetes.core.kustomize`

**Comment by bh-tt** [comment]
Kubectl is a Go binary. By default, Go accepts the HTTP_PROXY, HTTPS_PROXY  and NO_PROXY variable for the standard HTTP client. In my tests it has worked by simply adding the `HTTP_PROXY` or 'HTTPS_PROXY` environment variable.

For now I've managed to make this work using the pipe plugin and the 'playbook_dir' and 'role_path` ansible variables, like so:
```
- name: deploy
  kubernetes.core.k8s:
    definition: "{{ lookup('pipe', 'HTTPS_PROXY=http://proxy:3128 kubectl kustomize ' + role_path + '/files') | from_yaml_all }}"
```

If you want to implement the proxy setting that would be nice, but it is no longer an issue for us, so closing is fine as well.

**Comment by yurnov** [comment]
I see

Have you tried to use:

```
    - name: kustomize
      environment:
        HTTPS_PROXY: "http://proxy:3128"
      ansible.builtin.set_fact:
        resources: "{{ lookup('kubernetes.core.kustomize', dir='../files/', proxy='http://proxy') }}"
```

on the first look, it should work if kubectl supports HTTP_PROXY and HTTPS_PROXY environment variables.

**Comment by bh-tt** [comment]
Yes I have, but the plugin does not seem to pass the environment on to the command by default, since the `environment` is meant to be set on the remote host, whereas a lookup plugin runs on the ansible controller.

See https://github.com/ansible-collections/kubernetes.core/blob/c8a9326306e65c0edf945fb3e99a67937cbe9375/plugins/lookup/kustomize.py#L95

**Comment by yurnov** [comment]
Thanks @bh-tt for the clarification, I know how to improve it and will create PR.

**Comment by yurnov** [comment]
Hi @bh-tt,

could you please check [this one](https://github.com/yurnov/kubernetes.core/tree/support_local_env_for_kustomize), I don't have env to test it on my side right now.

BR/Yurii

**Comment by bh-tt** [comment]
I'm afraid this method does not work, as the `environment` keyword only sets the remote environment. The [docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_environment.html#setting-the-remote-environment) explicitly say this has no impact on the execution of filters or lookups: 'The environment: keyword does not affect Ansible itself, Ansible configuration settings, the environment for other users, or the execution of other plugins like lookups and filters.'

You could add an 'environment' variable to the task itself?

**Comment by yurnov** [comment]
I see.

But with PR #786  `env HTTPS_PROXY="http://proxy:3128" ansible-playbook playbook.yaml` should work with something like:

```
- hosts: localhost
  tasks:
    - name: kustomize
      ansible.builtin.set_fact:
        resources: "{{ lookup('kubernetes.core.kustomize', dir='../files/', use_local_env='True') }}"
```

Parameter `use_local_env` enable environment variable for `kubectl` or `kustomize`, please [check](https://github.com/yurnov/kubernetes.core/blob/ca39be5ac11f5e69ea406b4b5c681b86b3998a46/plugins/lookup/kustomize.py#L161C1-L166C64):
```
        if use_local_env:
            environ = dict(os.environ)
        else:
            environ = None

        (ret, out, err) = run_command(command, environ=environ)
```
 [and](https://github.com/yurnov/kubernetes.core/blob/ca39be5ac11f5e69ea406b4b5c681b86b3998a46/plugins/lookup/kustomize.py#L109C1-L114C42):

```
def run_command(command, environ=None):
    cmd = subprocess.Popen(
        command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=environ
    )
    stdout, stderr = cmd.communicate()
    return cmd.returncode, stdout, stderr
```

So, the local variable should be considered by the `command` (in this case by the `kubectl` or `kustomize`. 

Yep, I can add `variable` for the tasks, not sure what is better. Will do to see how it work

**Comment by bh-tt** [comment]
I can confirm that adding the parameter in the actual ansible-playbook call works. You understand we would prefer not to set this environment value for every ansible call, especially since some tasks will need it while others may crash as they only communicate with local (e.g. not needing the http proxy) endpoints. Additionally, that would require a very good memory to remember which playbooks need it and which do not.

**Comment by yurnov** [comment]
Hi @bh-tt,

now it should work in both ways, as the `env HTTPS_PROXY="http://proxy:3128" ansible-playbook playbook.yaml` and:

```
- hosts: localhost
  tasks:
    - name: kustomize
      ansible.builtin.set_fact:
        resources: "{{ lookup('kubernetes.core.kustomize', dir='../files/', enviroment='HTTPS_PROXY=http://proxy:3128') }}"
```

Same PR with this [state](https://github.com/yurnov/kubernetes.core/tree/053147a2cd097cde79eff6442e381f0007001a6d)
