### ISSUE TITLE
`diff: no` is not respected with k8s

### ISSUE THREAD

**Issue by benjdudas** [ansible-collections/kubernetes.core#88]
##### SUMMARY

When running a playbook with the diff option,  diff results are being listed when `diff: no` is  configured for the task. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.kubernetes.k8s

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bdudas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bdudas/dev-net/ansible_2_10/lib64/python3.9/site-packages/ansible
  executable location = /home/bdudas/dev-net/ansible_2_10/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```
```
Collection           Version
-------------------- -------
community.kubernetes 1.2.1
```

##### CONFIGURATION

```paste below
ANSIBLE_COW_SELECTION(/etc/ansible/ansible.cfg) = www
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
    - name: test diff on kube definition
      community.kubernetes.k8s:
        state: present
        apply: yes
        namespace: default
        definition: "{{ lookup('file', 'awx-secret.yml') }}"
        kubeconfig: "{{ kube_location }}"
      register: results
      diff: no

```

##### EXPECTED RESULTS

Diff results will be disabled for the task. 

https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html#using-diff-mode

##### ACTUAL RESULTS

Diff results for the task continue to be displayed in stdout
