### ISSUE TITLE
`kubernetes.core.helm_pull` module is not idempotent

### ISSUE THREAD

**Issue by oirtemed** [ansible-collections/kubernetes.core#889]
##### SUMMARY

`helm_pull` module is not idempotent. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- `kubernetes.core.helm_pull module`

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.4]
  config file = /home/oirtemed/projects/playground/ansible/ansible.cfg
  configured module search path = ['/home/oirtemed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oirtemed/projects/playground/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/oirtemed/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/oirtemed/projects/playground/.venv/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/home/oirtemed/projects/playground/.venv/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /home/oirtemed/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 5.1.0  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/oirtemed/projects/playground/ansible/ansible.cfg
HOST_KEY_CHECKING(/home/oirtemed/projects/playground/ansible/ansible.cfg) = False

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Debian GNU/Linux 12 (bookworm) running on WSL2.

##### STEPS TO REPRODUCE

Run the playbook below twice. The second time the task should not have made a change. 

```shell
$ ansible-playbook -i "localhost," donwload_artifacts_playbook.yaml 
```

```yaml
---
- name: Download artifacts
  hosts: localhost
  gather_facts: false
  become: false
  connection: local
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Download Chart using chart_name and repo_url
      kubernetes.core.helm_pull:
        chart_ref: hello-world
        chart_version: '0.1.0'
        repo_url: https://helm.github.io/examples
        untar_chart: false
        destination: /tmp
```

##### EXPECTED RESULTS

The second time that the play is run, the task should have not downloaded the Helm Chart since the artifact already exists and it is the same version.

##### ACTUAL RESULTS

The module always downloads the Helm Chart, even if the same version exists within the destination directory. 

```paste below
$ ansible-playbook -i "localhost," donwload_artifacts_playbook.yaml 

PLAY [Before cluster deployment] ******************************************************************************************************

TASK [Download Chart using chart_name and repo_url] ***********************************************************************************
changed: [localhost]

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

$ ansible-playbook -i "localhost," donwload_artifacts_playbook.yaml 

PLAY [Before cluster deployment] ******************************************************************************************************

TASK [Download Chart using chart_name and repo_url] ***********************************************************************************
changed: [localhost]

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
