### ISSUE TITLE
`kubernetes.core.k8s` deletes objects in check mode if `delete_options` are set

### ISSUE THREAD

**Issue by efussi** [ansible-collections/kubernetes.core#892]
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
<!--- Explain the problem briefly below -->
`kubernetes.core.k8s` deletes objects in check mode if `delete_options` are set

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->
plugins/module_utils/k8s/service.py

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
$ ansible --version
ansible [core 2.18.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/miniforge3/envs/dev/lib/python3.12/site-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vagrant/miniforge3/envs/dev/bin/ansible
  python version = 3.12.9 | packaged by conda-forge | (main, Mar  4 2025, 22:48:41) [GCC 13.3.0] (/home/vagrant/miniforge3/envs/dev/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
$ ansible-galaxy collection list kubernetes.core

# /home/vagrant/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 5.1.0  
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/vim

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
Ubuntu 20.04
```
$ pip3 show kubernetes
Name: kubernetes
Version: 31.0.0
Summary: Kubernetes python client
Home-page: https://github.com/kubernetes-client/python
Author: Kubernetes
Author-email: 
License: Apache License Version 2.0
Location: /home/vagrant/miniforge3/envs/dev/lib/python3.12/site-packages
Requires: certifi, durationpy, google-auth, oauthlib, python-dateutil, pyyaml, requests, requests-oauthlib, six, urllib3, websocket-client
Required-by: 
```

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
#!/usr/bin/env -S ansible-playbook -i localhost,
- hosts: localhost                                                                                                                                                                                                                                            
  connection: local                                                                                                                                                                                                                                           
  gather_facts: false                                                                                                                                                                                                                                         
  tasks:                                                                                                                                                                                                                                                      
    - kubernetes.core.k8s:                                                                                                                                                                                                                                    
        kind: ConfigMap                                                                                                                                                                                                                                       
        namespace: default                                                                                                                                                                                                                                    
        name: test-cm                                                                                                                                                                                                                                         
      check_mode: false                                                                                                                                                                                                                                       
    - kubernetes.core.k8s:                                                                                                                                                                                                                                    
        state: absent                                                                                                                                                                                                                                         
        kind: ConfigMap                                                                                                                                                                                                                                       
        namespace: default                                                                                                                                                                                                                                    
        name: test-cm                                                                                                                                                                                                                                         
        delete_options:                                                                                                                                                                                                                                    
          propagationPolicy: Background                                                                                                                                                                                                                      
    - kubernetes.core.k8s_info:                                                                                                                                                                                                                               
        kind: ConfigMap                                                                                                                                                                                                                                       
        namespace: default                                                                                                                                                                                                                                    
        name: test-cm                                                                                                                                                                                                                                         
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
When invoking the test playbook with `./test.yml -Cv` the configmap should still exist:
<!--- Paste verbatim command output between quotes -->
```paste below
: 
TASK [kubernetes.core.k8s] [CHECK MODE] ***************************************************************************************
changed: [localhost] => 
    changed: true
    method: delete
    result:
        apiVersion: v1
        details:
            kind: configmaps
            name: test-cm
            uid: b3419215-77ca-4307-b4e4-d27b732c023e
        kind: Status
        metadata: {}
        status: Success

TASK [kubernetes.core.k8s_info] [CHECK MODE] **********************************************************************************
ok: [localhost] => 
    api_found: true
    changed: false
    resources:
    -   apiVersion: v1
        kind: ConfigMap
        metadata:
            creationTimestamp: '2025-03-27T23:04:07Z'
            name: test-cm
            namespace: default
            resourceVersion: '343438472'
            uid: b3419215-77ca-4307-b4e4-d27b732c023e

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
The configmap is deleted despite check mode:
```
: 
TASK [kubernetes.core.k8s_info] [CHECK MODE] **********************************************************************************
ok: [localhost] => 
    api_found: true
    changed: false
    resources: []

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
Wondering if https://github.com/ansible-collections/kubernetes.core/blob/9ec69123257c8c68ceea358f6e6a9954efef380b/plugins/module_utils/k8s/service.py#L476 should be updated like so? 
```python
        if delete_options and not self.module.check_mode:                                                                                                                                                                                                                                    
            body = {                                                                                                                                                                                                                                          
                "apiVersion": "v1",                                                                                                                                                                                                                           
                "kind": "DeleteOptions",                                                                                                                                                                                                                      
            }                                                                                                                                                                                                                                                 
            body.update(delete_options)                                                                                                                                                                                                                       
            params["body"] = body                                                                                                                                                                                                                             
```
