### ISSUE TITLE
Expose the kubernetes client library connect timeout parameters

### ISSUE THREAD

**Issue by madAndroid** [ansible-collections/kubernetes.core#897]
##### SUMMARY
We frequently see timeouts when using the k8s_info module, it would be great if we could configure this in the parameters - the client libraries do expose this: https://github.com/kubernetes-client/python/blob/master/examples/watch/timeout-settings.md

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`k8s_info` - but applies to other components

##### ADDITIONAL INFORMATION
The default timeout seems very long, and causes our runs in Github Actions to hang for ages, since we implement retries - would be good to be able to adjust the value

```yaml
            - name: Check for 'vmware-system-tmc' namespace
              kubernetes.core.k8s_info:
                kubeconfig: "{{ kubeconfig_guest_cluster }}"
                api_version: v1
                kind: Namespace
                name: vmware-system-tmc
              register: namespace_info
              until: namespace_info is success
              retries: 3
              delay: 3
```
