### ISSUE TITLE
Unable to create k8s namespace and  no error

### ISSUE THREAD

**Issue by doing-cr7** [ansible-collections/kubernetes.core#900]
1. `exec`
```
 ansible -i inventory.ini all  -m ping
kce-server | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}


ansible-playbook -i inventory.ini deploy_kce.yml --tags create_namespace

PLAY [kce_hosts] *******************************************************************************************

TASK [kce_deployment : 2. 创建namespace] *******************************************************************
included: /usr/share/galaxy_ansible/roles/kce_deployment/tasks/create_namespace.yml for kce-server

PLAY RECAP *************************************************************************************************
kce-server                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

2. `inventory.ini`  
```
[kce_hosts]
kce-server ansible_host=10.xxxxx ansible_user=root ansible_port=22 ansible_ssh_private_key_file=~/.ssh/id_rsa
```

3. `deploy_kce.yml`
```
---
- hosts: kce_hosts
  gather_facts: false
  roles:
    - kce_deployment
```

4. `roles/deployment/tasks/create_namespace.yml`
```
---

- name: Ensure the myapp Namespace exists.
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: myapp
    state: present
```

**Comment by beeankha** [comment]
Hi @doing-cr7 , thank you for taking the time to file this issue!

There are several ways that we might be able to get you to see the results you are expecting.

1. You can rename your `create_namespace.yml` file to [`main.yml`](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#using-roles-at-the-play-level) 

2. If you do not want to rename your `create_namespace.yml` file, you can edit the content of the `deploy_kce.yml` playbook file like the following:
```
---
- hosts: kce_hosts
  gather_facts: false
  tasks:
    - name: Include specific task file from role
      include_role:
        name: kce_deployment
        tasks_from: test_playbook.yml
```

Whichever option you take, you will also need to run the command for the playbook _without_ the `--tags create_namespace` flag (i.e. just run `ansible-playbook -i inventory.ini deploy_kce.yml`), as the command will then be [looking for tasks that are tagged `create_namespace`](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#adding-tags-to-individual-tasks). 

Alternatively, if you prefer to run the command with the `--tag` flag, you will need to edit the contents of your role playbook (`create_namespace.yml` or the re-named `main.yml`) to the following:
```
---
- name: Ensure the myapp Namespace exists.
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: test-namespace
    state: present
  tags:
    - create_namespace
```

Please let me know if the above information fixes your issue of not being able to create a namespace and getting no error.
