### ISSUE TITLE
Error: chart requires kubeVersion: < 1.33.0-0 which is incompatible with Kubernetes v1.33.0

### ISSUE THREAD

**Issue by KoenDierckx** [ansible-collections/kubernetes.core#937]
##### SUMMARY
Error: chart requires kubeVersion: < 1.33.0-0 which is incompatible with Kubernetes v1.33.0

Happens after updating helm on the ansible controller node to the latest version

https://github.com/helm/helm/releases/tag/v3.18.0
https://github.com/helm/helm/commit/cc58e3f5a3aa615c6a86275e6f4444b5fdd3cc4e
This has upgraded the internal k8s.io go packages from 0.32.3 to 0.33.0

And thus, helm no defaults to this k8s version to check capabilities

```
❯ helm version
version.BuildInfo{Version:"v3.18.1", GitCommit:"f6f8700a539c18101509434f3b59e6a21402a1b2", GitTreeState:"clean", GoVersion:"go1.24.3"}
```

With native helm template
https://helm.sh/docs/helm/helm_template/

you can pass a --kube-version parameter to override the kubernetes version

But no such option exists for the ansible module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.helm_template

##### ANSIBLE VERSION
```ansible [core 2.18.4]
  config file = /mnt/wsl/home/projects/ansible/ansible/ansible.cfg
  configured module search path = ['/mnt/wsl/home/projects/ansible/ansible/library']
  ansible python module location = /mnt/wsl/home/projects/ansible/ansible/venv/lib/python3.12/site-packages/ansible
  ansible collection location = /mnt/wsl/home/.ansible/collections:/usr/share/ansible/collections
  executable location = /mnt/wsl/home/projects/ansible/ansible/venv/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/mnt/wsl/home/projects/ansible/ansible/venv/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION
```
❯ ansible-galaxy collection list kubernetes.core

# /mnt/wsl/home/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 5.3.0  

# /mnt/wsl/home/projects/ansible/ansible/venv/lib/python3.12/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 5.1.0 
```

##### CONFIGURATION
```
CACHE_PLUGIN(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = ansible.builtin.jsonfile
CACHE_PLUGIN_CONNECTION(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = .cache/facts
CACHE_PLUGIN_TIMEOUT(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = 7200
CONFIG_FILE() = /mnt/wsl/home/projects/ansible/ansible/ansible.cfg
DEFAULT_BECOME(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = root
DEFAULT_FORKS(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = 5
DEFAULT_HOST_LIST(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = ['/mnt/wsl/home/projects/ansible/ansible/inventory/vagrant_rke2']
DEFAULT_KEEP_REMOTE_FILES(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = False
DEFAULT_MODULE_PATH(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = ['/mnt/wsl/home/projects/ansible/ansible/library']
DEFAULT_STDOUT_CALLBACK(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = debug
DEFAULT_TIMEOUT(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = 10
EDITOR(env: EDITOR) = scite
HOST_KEY_CHECKING(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = False
INVENTORY_CACHE_PLUGIN(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = ansible.builtin.jsonfile
INVENTORY_ENABLED(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = ['vmware.vmware.vms', 'yaml', 'ini']
RETRY_FILES_SAVE_PATH(/mnt/wsl/home/projects/ansible/ansible/ansible.cfg) = /mnt/wsl/home/projects/ansible/ansible/retry

```

##### OS / ENVIRONMENT
Ubuntu 24.04 LTS

##### STEPS TO REPRODUCE
```
- name: Render rancher helm chart into Kubernetes manifests
  delegate_to: localhost
  kubernetes.core.helm_template:
    chart_ref: "{{ rancher_chart_ref }}"
    chart_version: "{{ rancher_chart_version | default('') }}"
    release_name: rancher
    release_namespace: "{{ rancher_namespace }}"
    dependency_update: true      # <–– pulls in missing charts for you
    update_repo_cache: true      # <–– update the repo cache
    include_crds: true          # <–– include CRDs in the rendered output
    release_values: "{{ rancher_release_values  }}"
  register: rancher_rendered_chart
  changed_when: false
```

##### EXPECTED RESULTS
ok: [p7kmgntc01 -> localhost] => {}

##### ACTUAL RESULTS
```
fatal: [p7kmgntc01 -> localhost]: FAILED! => {
    "changed": false,
    "command": "/usr/sbin/helm template rancher rancher-stable/rancher --dependency-update -n cattle-system -f=/tmp/tmp3n9lhavh.yml --include-crds"
}

STDERR:
Error: chart requires kubeVersion: < 1.33.0-0 which is incompatible with Kubernetes v1.33.0
Use --debug flag to render out invalid YAML

MSG:
Failure when executing Helm command. Exited 1.
stdout: 
stderr: Error: chart requires kubeVersion: < 1.33.0-0 which is incompatible with Kubernetes v1.33.0

Use --debug flag to render out invalid YAML
```
