### ISSUE TITLE
helm_registry_auth idempotency broken for logout with helm >= 3.18.0

### ISSUE THREAD

**Issue by yurnov** [ansible-collections/kubernetes.core#944]
##### SUMMARY
Idempotency is broken for module helm_registry_auth for logout operation with helm >= 3.18.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
helm_registry_auth

##### ANSIBLE VERSION
not related

##### COLLECTION VERSION
>= 5.1.0

##### CONFIGURATION

helm >= 3.18.0

##### OS / ENVIRONMENT
Linux AMD64, probably not related

##### STEPS TO REPRODUCE

```
    - name: Registry logout
      kubernetes.core.helm_registry_auth:
        host: testregistry:5000
        state: absent

    - name: Test logout idempotency
      kubernetes.core.helm_registry_auth:
        host: testregistry:5000
        state: absent
      register: _helm_registry_auth_logout_idempotency

    - name: Assert logout operation did not report change
      ansible.builtin.assert:
        that: _helm_registry_auth_logout_idempotency is not changed

```
##### EXPECTED RESULTS

Assertion passed

##### ACTUAL RESULTS

Assetrion failed
